//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVAirPlaySession.h"

@class NSObject<OS_dispatch_source>, NSObject<TVAirPlaySessionDelegate>, NSString, TVAirPlayPresentationView;

@interface TVAirPlayPresentationSession : NSObject <TVAirPlaySession>
{
    _Bool _deactivated;	// 8 = 0x8
    unsigned int _sessionID;	// 12 = 0xc
    NSObject<TVAirPlaySessionDelegate> *_delegate;	// 16 = 0x10
    TVAirPlayPresentationView *_presentationView;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_userActivityTimer;	// 32 = 0x20
}

@property(retain, nonatomic) NSObject<OS_dispatch_source> *userActivityTimer; // @synthesize userActivityTimer=_userActivityTimer;
@property(retain, nonatomic) TVAirPlayPresentationView *presentationView; // @synthesize presentationView=_presentationView;
@property(readonly, nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) __weak NSObject<TVAirPlaySessionDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool deactivated; // @synthesize deactivated=_deactivated;
- (void).cxx_destruct;	// IMP=0x0000000100012524
- (void)_cancelUserActivityTimer;	// IMP=0x00000001000123ec
- (void)_startUserActivityTimer;	// IMP=0x0000000100012308
- (void)userStop;	// IMP=0x0000000100012184
- (_Bool)performAction:(id)arg1 withOptions:(id)arg2 outInfo:(id *)arg3 error:(id *)arg4;	// IMP=0x000000010001209c
- (_Bool)setProperty:(id)arg1 qualifier:(id)arg2 value:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100012094
- (id)getProperty:(id)arg1 qualifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010001208c
- (_Bool)stopWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100011fb8
- (void)startWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100011c70
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long sessionType;
- (void)dealloc;	// IMP=0x0000000100011b74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

