//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVAirPlayResourceLoadingMediaItemDelegate.h"
#import "TVAirPlaySession.h"
#import "TVSPlaybackDelegate.h"

@class NSDictionary, NSMutableDictionary, NSNumber, NSObject<OS_dispatch_source>, NSObject<TVAirPlaySessionDelegate>, NSString, TVSPlayer, TVSPlaylist;

@interface TVAirPlayURLSession : NSObject <TVAirPlayResourceLoadingMediaItemDelegate, TVSPlaybackDelegate, TVAirPlaySession>
{
    _Bool _deactivated;	// 8 = 0x8
    _Bool _stoppedDueToUser;	// 9 = 0x9
    _Bool _audioOnly;	// 10 = 0xa
    _Bool _playerKVOObserversAdded;	// 11 = 0xb
    unsigned int _sessionID;	// 12 = 0xc
    NSObject<TVAirPlaySessionDelegate> *_delegate;	// 16 = 0x10
    TVSPlayer *_player;	// 24 = 0x18
    TVSPlaylist *_playlist;	// 32 = 0x20
    NSDictionary *_initialRequest;	// 40 = 0x28
    NSMutableDictionary *_resourceLoadingRequests;	// 48 = 0x30
    id _elapsedTimeObserverToken;	// 56 = 0x38
    NSObject<OS_dispatch_source> *_emptyPlaylistTimer;	// 64 = 0x40
    NSNumber *_audioSessionID;	// 72 = 0x48
}

+ (id)_mediaItemForParameters:(id)arg1;	// IMP=0x00000001000071b4
+ (id)_playerForParameters:(id)arg1 playlist:(id)arg2;	// IMP=0x0000000100006f10
@property(retain, nonatomic) NSNumber *audioSessionID; // @synthesize audioSessionID=_audioSessionID;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *emptyPlaylistTimer; // @synthesize emptyPlaylistTimer=_emptyPlaylistTimer;
@property(retain, nonatomic) id elapsedTimeObserverToken; // @synthesize elapsedTimeObserverToken=_elapsedTimeObserverToken;
@property(nonatomic) _Bool playerKVOObserversAdded; // @synthesize playerKVOObserversAdded=_playerKVOObserversAdded;
@property(retain, nonatomic) NSMutableDictionary *resourceLoadingRequests; // @synthesize resourceLoadingRequests=_resourceLoadingRequests;
@property(retain, nonatomic) NSDictionary *initialRequest; // @synthesize initialRequest=_initialRequest;
@property(retain, nonatomic) TVSPlaylist *playlist; // @synthesize playlist=_playlist;
@property(nonatomic) _Bool audioOnly; // @synthesize audioOnly=_audioOnly;
@property(nonatomic) _Bool stoppedDueToUser; // @synthesize stoppedDueToUser=_stoppedDueToUser;
@property(retain, nonatomic) TVSPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) __weak NSObject<TVAirPlaySessionDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool deactivated; // @synthesize deactivated=_deactivated;
- (void).cxx_destruct;	// IMP=0x0000000100007d14
- (void)_cancelEmptyPlaylistTimer;	// IMP=0x0000000100006ecc
- (id)_parametersWithAddedSessionOptions:(id)arg1;	// IMP=0x0000000100006e28
- (void)_removePlayerKVOObservers;	// IMP=0x0000000100006d80
- (void)_parseSessionOptions:(id)arg1;	// IMP=0x0000000100006c5c
- (_Bool)_handleFailedURLResponseWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100006714
- (id)_handleKeyResponseWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000063bc
- (void)mediaItem:(id)arg1 didRequestResource:(id)arg2;	// IMP=0x0000000100006240
- (_Bool)player:(id)arg1 shouldChangeToMediaAtIndex:(unsigned long long)arg2;	// IMP=0x0000000100006238
- (_Bool)player:(id)arg1 shouldChangeMediaInDirection:(long long)arg2;	// IMP=0x0000000100006174
- (_Bool)player:(id)arg1 shouldScanAtRate:(double)arg2;	// IMP=0x000000010000616c
- (_Bool)playerShouldPause:(id)arg1;	// IMP=0x0000000100006164
- (_Bool)playerShouldPlay:(id)arg1 timeFromWhichToPlay:(double *)arg2;	// IMP=0x000000010000615c
- (_Bool)player:(id)arg1 shouldSeekToTime:(double *)arg2 playbackDate:(id *)arg3;	// IMP=0x0000000100006154
- (_Bool)_removeItemWithInfo:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100005f14
- (void)_insertItemWithInfo:(id)arg1 afterItem:(id)arg2;	// IMP=0x0000000100005e2c
- (void)audioSessionInterrupted:(id)arg1;	// IMP=0x0000000100005d0c
- (void)playlistDidPlayToEnd:(id)arg1;	// IMP=0x0000000100005af4
- (void)itemDidChange:(id)arg1;	// IMP=0x0000000100005854
- (void)itemWillChange:(id)arg1;	// IMP=0x0000000100005648
- (void)itemDidPlayToEnd:(id)arg1;	// IMP=0x000000010000543c
- (void)_playerStateDidChange:(id)arg1;	// IMP=0x000000010000504c
- (void)userStop;	// IMP=0x0000000100004e84
- (_Bool)performAction:(id)arg1 withOptions:(id)arg2 outInfo:(id *)arg3 error:(id *)arg4;	// IMP=0x00000001000045d4
- (_Bool)setProperty:(id)arg1 qualifier:(id)arg2 value:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100003b18
- (id)getProperty:(id)arg1 qualifier:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000036e4
- (_Bool)stopWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100003494
- (void)startWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100002bd0
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long sessionType;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100002958
- (void)dealloc;	// IMP=0x00000001000028bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

