//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVCKAppDelegate.h"

#import "_TVInterfaceCreatingPrivate.h"

@class NSString, TVASAppInstallationJSNotifier;

@interface TVAppStoreDelegate : TVCKAppDelegate <_TVInterfaceCreatingPrivate>
{
    TVASAppInstallationJSNotifier *_jsNotifier;	// 8 = 0x8
}

@property(retain, nonatomic) TVASAppInstallationJSNotifier *jsNotifier; // @synthesize jsNotifier=_jsNotifier;
- (void).cxx_destruct;	// IMP=0x00000001000138cc
- (Class)collectionViewCellClassForElement:(id)arg1;	// IMP=0x0000000100013804
- (id)viewForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x0000000100013614
- (void)appController:(id)arg1 evaluateAppJavaScriptInContext:(id)arg2;	// IMP=0x00000001000134a4
- (id)init;	// IMP=0x0000000100013234

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

