//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CALayer, CAShapeLayer, TVASVibrantLabel, UIImage, UIImageView, UILabel, UIView, UIVisualEffectView, _TVASEnhancedAnimationsView, _UIFloatingContentView;

@interface TVASBuyButton : UIControl
{
    long long _backdropStyle;	// 8 = 0x8
    long long _textVibrancyStyle;	// 16 = 0x10
    UILabel *_pricingLabel;	// 24 = 0x18
    UILabel *_actionLabel;	// 32 = 0x20
    UIImage *_actionImage;	// 40 = 0x28
    long long _buyButtonState;	// 48 = 0x30
    double _progress;	// 56 = 0x38
    _UIFloatingContentView *_floatingView;	// 64 = 0x40
    UIVisualEffectView *_backdropView;	// 72 = 0x48
    UIImageView *_actionImageView;	// 80 = 0x50
    UIView *_overlayView;	// 88 = 0x58
    CALayer *_actionImageMask;	// 96 = 0x60
    UILabel *_pricingLabelMask;	// 104 = 0x68
    TVASVibrantLabel *_vibrantLabel;	// 112 = 0x70
    CAShapeLayer *_unfocusedPieLayer;	// 120 = 0x78
    CAShapeLayer *_focusedPieLayer;	// 128 = 0x80
    _TVASEnhancedAnimationsView *_viewProxy;	// 136 = 0x88
    unsigned long long _pieState;	// 144 = 0x90
    struct CGSize _buttonSize;	// 152 = 0x98
}

@property(nonatomic) unsigned long long pieState; // @synthesize pieState=_pieState;
@property(retain, nonatomic) _TVASEnhancedAnimationsView *viewProxy; // @synthesize viewProxy=_viewProxy;
@property(retain, nonatomic) CAShapeLayer *focusedPieLayer; // @synthesize focusedPieLayer=_focusedPieLayer;
@property(retain, nonatomic) CAShapeLayer *unfocusedPieLayer; // @synthesize unfocusedPieLayer=_unfocusedPieLayer;
@property(retain, nonatomic) TVASVibrantLabel *vibrantLabel; // @synthesize vibrantLabel=_vibrantLabel;
@property(retain, nonatomic) UILabel *pricingLabelMask; // @synthesize pricingLabelMask=_pricingLabelMask;
@property(retain, nonatomic) CALayer *actionImageMask; // @synthesize actionImageMask=_actionImageMask;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIImageView *actionImageView; // @synthesize actionImageView=_actionImageView;
@property(retain, nonatomic) UIVisualEffectView *backdropView; // @synthesize backdropView=_backdropView;
@property(retain, nonatomic) _UIFloatingContentView *floatingView; // @synthesize floatingView=_floatingView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) long long buyButtonState; // @synthesize buyButtonState=_buyButtonState;
@property(retain, nonatomic) UIImage *actionImage; // @synthesize actionImage=_actionImage;
@property(retain, nonatomic) UILabel *actionLabel; // @synthesize actionLabel=_actionLabel;
@property(retain, nonatomic) UILabel *pricingLabel; // @synthesize pricingLabel=_pricingLabel;
@property(nonatomic) struct CGSize buttonSize; // @synthesize buttonSize=_buttonSize;
@property(readonly, nonatomic) long long textVibrancyStyle; // @synthesize textVibrancyStyle=_textVibrancyStyle;
@property(readonly, nonatomic) long long backdropStyle; // @synthesize backdropStyle=_backdropStyle;
- (void).cxx_destruct;	// IMP=0x000000010000dcf0
- (void)_selectButtonAction:(id)arg1;	// IMP=0x000000010000d8e0
- (id)_contentView;	// IMP=0x000000010000d88c
- (_Bool)_shouldShowPie;	// IMP=0x000000010000d868
- (id)_pieLayerWithDiameter:(double)arg1;	// IMP=0x000000010000d73c
- (id)_progressPieLayerWithDiameter:(double)arg1;	// IMP=0x000000010000d464
- (id)_spinningPieLayerWithDiameter:(double)arg1;	// IMP=0x000000010000d324
- (void)_updatePieLayers;	// IMP=0x000000010000ce90
- (void)_removePieLayers;	// IMP=0x000000010000cdd8
- (void)_installPieLayers;	// IMP=0x000000010000c9e4
- (void)_updateButtonAppearance;	// IMP=0x000000010000c78c
- (void)willMoveToWindow:(id)arg1;	// IMP=0x000000010000c734
- (void)layoutSubviews;	// IMP=0x000000010000c2fc
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010000c280
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010000c16c
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010000c084
- (void)setBuyButtonState:(long long)arg1 withProgress:(double)arg2;	// IMP=0x000000010000bdd4
- (void)dealloc;	// IMP=0x000000010000b174
- (id)initWithFrame:(struct CGRect)arg1 backdropStyle:(long long)arg2 textVibrancyStyle:(long long)arg3;	// IMP=0x000000010000ac9c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010000ac88
- (void)tvas_configureWithViewElement:(id)arg1 suppressUpdate:(_Bool)arg2;	// IMP=0x000000010001273c
- (void)tvas_configureWithViewElement:(id)arg1;	// IMP=0x000000010001272c

@end

