//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKDaemonProxyDataUpdateDelegate.h"
#import "UIApplicationDelegate.h"

@class NSString, UIWindow;

@interface AppDelegateService : NSObject <UIApplicationDelegate, GKDaemonProxyDataUpdateDelegate>
{
}

- (void)setLocalPlayer:(id)arg1;	// IMP=0x00000001000134a4
- (void)refreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x000000010001346c
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100013464
- (id)init;	// IMP=0x0000000100013390

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

