//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionFocusingLayout.h"

@class NSDictionary;

@interface GKCollectionColumnLayout : GKCollectionFocusingLayout
{
    NSDictionary *_itemAttributes;	// 8 = 0x8
    NSDictionary *_headerAttributes;	// 16 = 0x10
    NSDictionary *_decorationAttributes;	// 24 = 0x18
}

@property(retain, nonatomic) NSDictionary *decorationAttributes; // @synthesize decorationAttributes=_decorationAttributes;
@property(retain, nonatomic) NSDictionary *headerAttributes; // @synthesize headerAttributes=_headerAttributes;
@property(retain, nonatomic) NSDictionary *itemAttributes; // @synthesize itemAttributes=_itemAttributes;
- (struct CGSize)collectionViewContentSize;	// IMP=0x000000010001a7f4
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x000000010001a790
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x000000010001a6b8
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x000000010001a62c
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x000000010001a04c
- (void)prepareLayout;	// IMP=0x0000000100019864
- (void)applyDefaults;	// IMP=0x0000000100019784
- (void)dealloc;	// IMP=0x00000001000196fc

@end

