//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionDataSource.h"

@class NSArray;

@interface GKDashboardTurnDataSource : GKCollectionDataSource
{
    _Bool _shouldShowPlay;	// 8 = 0x8
    _Bool _shouldShowQuit;	// 9 = 0x9
    NSArray *_matches;	// 16 = 0x10
}

@property(retain, nonatomic) NSArray *matches; // @synthesize matches=_matches;
@property(nonatomic) _Bool shouldShowQuit; // @synthesize shouldShowQuit=_shouldShowQuit;
@property(nonatomic) _Bool shouldShowPlay; // @synthesize shouldShowPlay=_shouldShowPlay;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100016280
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010001626c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100016100
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00000001000160f8
- (id)sectionHeaderText;	// IMP=0x0000000100015fe8
- (id)itemForIndexPath:(id)arg1;	// IMP=0x0000000100015f48
- (double)preferredCollectionHeight;	// IMP=0x0000000100015f34
- (long long)itemCount;	// IMP=0x0000000100015f1c
- (void)loadDataWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100015d50
- (void)setupCollectionView:(id)arg1;	// IMP=0x0000000100015ce0
- (void)dealloc;	// IMP=0x0000000100015c84
- (id)init;	// IMP=0x0000000100015c28

@end

