//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UIFloatingContentView.h"

@class GKDashboardPlayerPhotoView, UIImageView;

@interface GKDashboardPlayerPhotoFloatingContentView : _UIFloatingContentView
{
    GKDashboardPlayerPhotoView *_photoView;	// 8 = 0x8
    UIImageView *_unfocusedShadowView;	// 16 = 0x10
    UIImageView *_focusedShadowView;	// 24 = 0x18
    double _unfocusedShadowAlpha;	// 32 = 0x20
    double _focusedShadowAlpha;	// 40 = 0x28
}

@property(nonatomic) double focusedShadowAlpha; // @synthesize focusedShadowAlpha=_focusedShadowAlpha;
@property(nonatomic) double unfocusedShadowAlpha; // @synthesize unfocusedShadowAlpha=_unfocusedShadowAlpha;
@property(retain, nonatomic) UIImageView *focusedShadowView; // @synthesize focusedShadowView=_focusedShadowView;
@property(retain, nonatomic) UIImageView *unfocusedShadowView; // @synthesize unfocusedShadowView=_unfocusedShadowView;
@property(retain, nonatomic) GKDashboardPlayerPhotoView *photoView; // @synthesize photoView=_photoView;
- (void)setControlState:(unsigned long long)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100024ee4
- (_Bool)isSelected;	// IMP=0x0000000100024ec4
- (void)setFocusedShadowImage:(id)arg1;	// IMP=0x0000000100024c0c
- (void)setUnfocusedShadowImage:(id)arg1;	// IMP=0x0000000100024964
- (void)dealloc;	// IMP=0x00000001000248dc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100024610

@end

