//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKImageEffects : NSObject
{
}

+ (id)imageByApplyingBlurToImage:(id)arg1 withRadius:(double)arg2 tintColor:(id)arg3 saturationDeltaFactor:(double)arg4 maskImage:(id)arg5;	// IMP=0x000000010002214c
+ (id)imageByApplyingTintEffectWithColor:(id)arg1 toImage:(id)arg2;	// IMP=0x000000010002204c
+ (id)imageByApplyingDarkEffectToImage:(id)arg1;	// IMP=0x0000000100021fe0
+ (id)imageByApplyingExtraLightEffectToImage:(id)arg1;	// IMP=0x0000000100021f74
+ (id)imageByApplyingLightEffectToImage:(id)arg1;	// IMP=0x0000000100021f0c

@end

