//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (GKAchievementProgress)
- (id)_gkImageWithProgress:(double)arg1 achievement:(id)arg2 isDetail:(_Bool)arg3;	// IMP=0x000000010000f250
- (id)_gkMaskImageWithProgress:(double)arg1 isDetail:(_Bool)arg2;	// IMP=0x000000010000ed9c
- (id)_gkQuestionMarkImage;	// IMP=0x000000010000ed10
@end

