/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 22, 2017 at 9:08:53 AM Mountain Standard Time
* Operating System: Version 10.1 (Build 14U593)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACFGeneralMessageProtocol <NSCopying,NSObject,NSCoding>
@required
-(id)copy;
-(id)identifier;
-(void)setIdentifier:(id)arg1;
-(id)info;
-(void)setInfo:(id)arg1;
-(int)senderProcessID;
-(void)setSenderProcessID:(int)arg1;
-(id)senderProcessName;
-(void)setSenderProcessName:(id)arg1;
-(id)senderPortName;
-(void)setSenderPortName:(id)arg1;

@end

