/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 22, 2017 at 9:08:54 AM Mountain Standard Time
* Operating System: Version 10.1 (Build 14U593)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACFRunLoopScheduling <NSObject>
@required
-(void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;
-(void)unscheduleFromRunLoop:(id)arg1 forMode:(id)arg2;

@end

