/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 22, 2017 at 9:08:54 AM Mountain Standard Time
* Operating System: Version 10.1 (Build 14U593)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMAppleConnectPreferences.h>

@class NSData;

@interface ACMExternalAppleConnectPreferences : ACMAppleConnectPreferences

@property (nonatomic,retain) NSData * secret; 
-(id)createEnvironmentWithRealm:(id)arg1 ;
-(NSData *)secret;
-(void)setSecret:(NSData *)arg1 ;
@end

