//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface ADClientGlobalState : NSObject
{
    _Bool _carKitConnected;	// 8 = 0x8
    NSString *_audioSessionPortType;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_instanceQueue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010000b6c0
@property(nonatomic) NSObject<OS_dispatch_queue> *instanceQueue; // @synthesize instanceQueue=_instanceQueue;
@property(nonatomic) _Bool carKitConnected; // @synthesize carKitConnected=_carKitConnected;
@property(copy, nonatomic) NSString *audioSessionPortType; // @synthesize audioSessionPortType=_audioSessionPortType;
- (void)_notifyObserversOfStateChange;	// IMP=0x000000010000be18
- (void)_checkForNewAudioRoute;	// IMP=0x000000010000bce0
- (void)_audioRouteChanged:(id)arg1;	// IMP=0x000000010000bcd4
- (void)_screenDidDisconnect:(id)arg1;	// IMP=0x000000010000bcc8
- (void)_screenDidConnect:(id)arg1;	// IMP=0x000000010000bcbc
- (void)_checkForCarKitScreen;	// IMP=0x000000010000bbe4
@property(readonly, retain, nonatomic) NSArray *globalContextTags;
- (void)dealloc;	// IMP=0x000000010000b878
- (id)init;	// IMP=0x000000010000b738

@end

