//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (ADJSPropertyUtilities)
- (struct CGRect)_iAd_rectValue;	// IMP=0x00000001000205b8
- (id)_iAd_numberValueForKey:(id)arg1;	// IMP=0x0000000100020570
- (id)_iAd_stringValueForKey:(id)arg1;	// IMP=0x0000000100020528
- (id)_iAd_valueOfClass:(Class)arg1 forKey:(id)arg2;	// IMP=0x0000000100020434
@end

