//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPanGestureRecognizer.h"

@interface _HBTouchablePanGestureRecognizer : UIPanGestureRecognizer
{
}

- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003db2c
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003da20
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003d914

@end

