//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HBAppGridViewDataSource.h"
#import "HBAppGridViewDelegate.h"
#import "HBBubbleAnimatorViewProvider.h"
#import "HBFolderObserver.h"
#import "UIGestureRecognizerDelegate.h"

@class HBAlertController, HBAppDeleteHintView, HBAppGridView, HBFolder, HBFolderViewControllerTransitioningDelegate, HBRootItem, HBSingleCellHostView, HBUninstallConfirmationController, NSMutableArray, NSString, TVSStateMachine, UITapGestureRecognizer, UIView;

@interface HBAppGridViewController : UIViewController <HBAppGridViewDataSource, HBAppGridViewDelegate, HBBubbleAnimatorViewProvider, HBFolderObserver, UIGestureRecognizerDelegate>
{
    struct {
        unsigned int delegateDidFocusOnItem:1;
        unsigned int delegateDidFocusOnItemInDock:1;
        unsigned int delegateWillUnfocusOnItemInDock:1;
        unsigned int delegateItemMoveIntoDock:1;
        unsigned int delegateItemMoveOutOfDockReplaceWithItem:1;
        unsigned int delegateItemsBecameReady:1;
        unsigned int delegateEditingStateChanged:1;
        unsigned int delegateDidEndDecelerating:1;
        unsigned int delegateDidScrollCloseEnoughToTop:1;
    } _flags;	// 8 = 0x8
    _Bool _dockMode;	// 12 = 0xc
    double _touchHintDisplayStartTime;	// 16 = 0x10
    _Bool _updatePending;	// 24 = 0x18
    _Bool _needsUpdateForAnimatorCompletion;	// 25 = 0x19
    _Bool _shouldIgnoreFolderChanges;	// 26 = 0x1a
    _Bool _shouldCaptureFocusForFolderResign;	// 27 = 0x1b
    _Bool _stableEditingState;	// 28 = 0x1c
    id <HBAppGridViewControllerDelegate> _delegate;	// 32 = 0x20
    HBRootItem *_focusedItem;	// 40 = 0x28
    NSMutableArray *_items;	// 48 = 0x30
    HBSingleCellHostView *_editingSnapshotTransitionView;	// 56 = 0x38
    UITapGestureRecognizer *_editingMenuGesture;	// 64 = 0x40
    UITapGestureRecognizer *_editingTVButtonGesture;	// 72 = 0x48
    UITapGestureRecognizer *_editingSelectGesture;	// 80 = 0x50
    UITapGestureRecognizer *_editingPlayPauseGesture;	// 88 = 0x58
    HBFolderViewControllerTransitioningDelegate *_strongTransitioningDelegate;	// 96 = 0x60
    HBUninstallConfirmationController *_uninstallConfirmationController;	// 104 = 0x68
    HBAlertController *_editingAlertController;	// 112 = 0x70
    TVSStateMachine *_editingHintStateMachine;	// 120 = 0x78
    HBAppDeleteHintView *_hintView;	// 128 = 0x80
    HBAppGridView *_appGridView;	// 136 = 0x88
    HBFolder *_folder;	// 144 = 0x90
}

+ (id)_subItemsFromItems:(id)arg1 aroundIndex:(unsigned long long)arg2 amount:(unsigned long long)arg3;	// IMP=0x0000000100051174
+ (_Bool)_canRemoveApp:(id)arg1;	// IMP=0x0000000100050380
+ (void)initialize;	// IMP=0x000000010004a5c4
@property(retain, nonatomic) HBFolder *folder; // @synthesize folder=_folder;
@property(retain, nonatomic) HBAppGridView *appGridView; // @synthesize appGridView=_appGridView;
@property(nonatomic) _Bool stableEditingState; // @synthesize stableEditingState=_stableEditingState;
@property(retain, nonatomic) HBAppDeleteHintView *hintView; // @synthesize hintView=_hintView;
@property(retain, nonatomic) TVSStateMachine *editingHintStateMachine; // @synthesize editingHintStateMachine=_editingHintStateMachine;
@property(nonatomic) _Bool shouldCaptureFocusForFolderResign; // @synthesize shouldCaptureFocusForFolderResign=_shouldCaptureFocusForFolderResign;
@property(nonatomic) _Bool shouldIgnoreFolderChanges; // @synthesize shouldIgnoreFolderChanges=_shouldIgnoreFolderChanges;
@property(nonatomic) _Bool needsUpdateForAnimatorCompletion; // @synthesize needsUpdateForAnimatorCompletion=_needsUpdateForAnimatorCompletion;
@property(nonatomic, getter=isUpdatePending) _Bool updatePending; // @synthesize updatePending=_updatePending;
@property(retain, nonatomic) HBAlertController *editingAlertController; // @synthesize editingAlertController=_editingAlertController;
@property(retain, nonatomic) HBUninstallConfirmationController *uninstallConfirmationController; // @synthesize uninstallConfirmationController=_uninstallConfirmationController;
@property(retain, nonatomic) HBFolderViewControllerTransitioningDelegate *strongTransitioningDelegate; // @synthesize strongTransitioningDelegate=_strongTransitioningDelegate;
@property(retain, nonatomic) UITapGestureRecognizer *editingPlayPauseGesture; // @synthesize editingPlayPauseGesture=_editingPlayPauseGesture;
@property(retain, nonatomic) UITapGestureRecognizer *editingSelectGesture; // @synthesize editingSelectGesture=_editingSelectGesture;
@property(retain, nonatomic) UITapGestureRecognizer *editingTVButtonGesture; // @synthesize editingTVButtonGesture=_editingTVButtonGesture;
@property(retain, nonatomic) UITapGestureRecognizer *editingMenuGesture; // @synthesize editingMenuGesture=_editingMenuGesture;
@property(retain, nonatomic) HBSingleCellHostView *editingSnapshotTransitionView; // @synthesize editingSnapshotTransitionView=_editingSnapshotTransitionView;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) HBRootItem *focusedItem; // @synthesize focusedItem=_focusedItem;
@property(nonatomic) __weak id <HBAppGridViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100054280
- (id)_newEditingHintStateMachine;	// IMP=0x00000001000532f8
- (void)_handleTouchEndWhileWaitingForHintTimerExpireEvent;	// IMP=0x00000001000532d0
- (void)_handleMinimumShowHintOnTouchEndEvent;	// IMP=0x0000000100053208
- (void)_handleShowHintEventForTouchEvent;	// IMP=0x00000001000531cc
- (void)_handleTouchBeginWhileStableEvent;	// IMP=0x0000000100053170
- (void)_handleBeginStableEditingEvent;	// IMP=0x0000000100053154
- (void)_handleEndStableEditingEvent;	// IMP=0x000000010005312c
- (void)_postHintEndEventForTimer;	// IMP=0x00000001000530e4
- (void)_handleShowHintEvent:(double)arg1;	// IMP=0x0000000100052e78
- (void)_postWaitingToHintTimerExpireEvent;	// IMP=0x0000000100052e30
- (void)_handleHintBeginEvent;	// IMP=0x0000000100052e14
- (void)_handleHintDismissalForEvent;	// IMP=0x0000000100052c80
- (void)setNeedsUpdate;	// IMP=0x0000000100052b40
- (void)_enterIdleMode:(id)arg1;	// IMP=0x0000000100052a98
- (void)_applicationWillResignActive:(id)arg1;	// IMP=0x0000000100052a84
- (void)_completeTransitionFromApp:(id)arg1 toIndex:(long long)arg2 transitionView:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100052340
- (void)_zoomResignItemTransitionAnimationCompleteWithApp:(id)arg1 fromFolder:(id)arg2 transitionView:(id)arg3 resignTransitionToLeft:(_Bool)arg4;	// IMP=0x0000000100051c94
- (void)_resignApp:(id)arg1 toFolder:(id)arg2 resignTransitionToLeft:(_Bool)arg3;	// IMP=0x0000000100051980
- (void)_zoomLaunchItemTransitionAnimationCompleteWithApp:(id)arg1 transitionView:(id)arg2;	// IMP=0x00000001000517c4
- (void)_startTransitionFromApp:(id)arg1 toFolder:(id)arg2;	// IMP=0x0000000100051330
- (void)_preheatIconsAroundIndex:(unsigned long long)arg1;	// IMP=0x00000001000510b8
- (id)_snapshotOfFocusedCell;	// IMP=0x0000000100051008
- (void)_openFolder:(id)arg1;	// IMP=0x0000000100050d78
- (id)_proposedFolderNameForTargetApp:(id)arg1 editedApp:(id)arg2;	// IMP=0x0000000100050adc
- (id)_possibleDestinationFoldersForApp:(id)arg1;	// IMP=0x00000001000509b4
- (void)_attemptToRemoveApp:(id)arg1;	// IMP=0x0000000100050404
- (long long)_animationDirectionFromItem:(id)arg1 toItem:(id)arg2;	// IMP=0x0000000100050278
- (id)_appGridViewItemAtIndexPath:(id)arg1;	// IMP=0x00000001000501dc
- (id)_indexPathOfItem:(id)arg1;	// IMP=0x000000010005012c
- (void)_handlePlayPauseGestureWhileEditing:(id)arg1;	// IMP=0x000000010004f694
- (void)_handleGestureToEndEditing:(id)arg1;	// IMP=0x000000010004f62c
- (void)_commitItemsToFolder:(id)arg1;	// IMP=0x000000010004f558
- (void)_handleEditingStateChange;	// IMP=0x000000010004f0a0
- (void)_attemptToEndEditingWithReason:(long long)arg1 shouldSave:(_Bool)arg2;	// IMP=0x000000010004ee98
- (void)_startEditingWithSnapshotView:(id)arg1;	// IMP=0x000000010004ee0c
- (void)_startEditing;	// IMP=0x000000010004ed98
@property(readonly, nonatomic, getter=isEditing) _Bool editing;
- (id)viewsForAnimator:(id)arg1;	// IMP=0x000000010004e9dc
- (void)appGridViewDidEndStableEditing:(id)arg1;	// IMP=0x000000010004e97c
- (void)appGridViewDidBeginStableEditing:(id)arg1;	// IMP=0x000000010004e91c
- (void)appGridViewDidStableTouchEndWhileEditing:(id)arg1;	// IMP=0x000000010004e8d4
- (void)appGridViewDidStableTouchBeginWhileEditing:(id)arg1;	// IMP=0x000000010004e88c
- (void)appGridViewDidScrollCloseEnoughToTop:(id)arg1;	// IMP=0x000000010004e820
- (void)appGridViewDidEndDecelerating:(id)arg1;	// IMP=0x000000010004e7b8
- (void)appGridView:(id)arg1 didFocusItemAtIndexPath:(id)arg2;	// IMP=0x000000010004e6c4
- (void)appGridView:(id)arg1 didLongPressItemAtIndexPath:(id)arg2;	// IMP=0x000000010004e680
- (void)appGridView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010004e0e8
- (id)preferredFocusIndexPathInAppGridView:(id)arg1;	// IMP=0x000000010004e088
- (void)appGridView:(id)arg1 droppedItemAtIndexPathOutOfBounds:(id)arg2 isLeft:(_Bool)arg3;	// IMP=0x000000010004df40
- (void)_moveApp:(id)arg1 toFolder:(id)arg2;	// IMP=0x000000010004d9fc
- (void)_createFolderWithApp:(id)arg1;	// IMP=0x000000010004d4b0
- (void)_createFolderWithTargetApp:(id)arg1 editedApp:(id)arg2;	// IMP=0x000000010004cf48
- (void)appGridView:(id)arg1 droppedItemAtIndexPath:(id)arg2 onItemAtIndexPath:(id)arg3;	// IMP=0x000000010004ccf8
- (void)appGridView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;	// IMP=0x000000010004ca14
- (_Bool)appGridView:(id)arg1 canMoveItemAtIndexPath:(id)arg2;	// IMP=0x000000010004ca0c
- (id)appGridView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010004c8d8
- (unsigned long long)numberOfApplicationsInAppGridView:(id)arg1;	// IMP=0x000000010004c88c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010004c7ec
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010004c74c
- (void)loadView;	// IMP=0x000000010004c67c
@property(readonly, nonatomic, getter=isFirstCellFocused) _Bool firstCellFocused;
@property(readonly, nonatomic, getter=isDecelerating) _Bool decelerating;
- (void)_ensureFirstCellIsFocused;	// IMP=0x000000010004c3e4
- (void)moveFocusToFirstDockItem;	// IMP=0x000000010004c390
- (void)scrollToTop:(CDUnknownBlockType)arg1;	// IMP=0x000000010004c2f4
- (void)scrollToTop;	// IMP=0x000000010004c2e4
- (_Bool)isItemInDock:(id)arg1;	// IMP=0x000000010004c1b0
@property(retain, nonatomic) UIView *headerView;
@property(readonly, nonatomic) unsigned long long maxNumberOfItemsInDock;
- (void)_updateItems;	// IMP=0x000000010004b270
- (void)_bubbleAnimatorAnimatingDidChange:(id)arg1;	// IMP=0x000000010004b1c0
- (void)itemsDidChange:(id)arg1;	// IMP=0x000000010004b17c
@property(nonatomic) struct UIEdgeInsets editingClampInsets;
- (id)preferredFocusEnvironments;	// IMP=0x000000010004af50
- (_Bool)shouldUpdateFocusFromView:(id)arg1 toView:(id)arg2 heading:(unsigned long long)arg3;	// IMP=0x000000010004aef4
- (void)dealloc;	// IMP=0x000000010004ae18
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x000000010004abdc
- (id)initWithFolder:(id)arg1 dockMode:(_Bool)arg2;	// IMP=0x000000010004a660
- (id)initWithFolder:(id)arg1;	// IMP=0x000000010004a650
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010004a640
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010004a630

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

