//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HBFolderObserver.h"
#import "LSApplicationWorkspaceObserverProtocol.h"

@class HBFolder, NSString, NSURL;

@interface HBAppRoot : NSObject <LSApplicationWorkspaceObserverProtocol, HBFolderObserver>
{
    _Bool _savePending;	// 8 = 0x8
    _Bool _completedInitialUpdate;	// 9 = 0x9
    NSURL *_appRootURL;	// 16 = 0x10
    HBFolder *_rootFolder;	// 24 = 0x18
}

+ (id)_defaultAppRootURL;	// IMP=0x000000010001e424
+ (void)_folder:(id)arg1 withAppsRemoved:(id)arg2;	// IMP=0x000000010001d6ec
+ (void)_dedupeFolder:(id)arg1 visitedApps:(id)arg2;	// IMP=0x000000010001bf88
+ (id)_rootFolderFromURL:(id)arg1;	// IMP=0x000000010001bd9c
+ (id)defaultAppRoot;	// IMP=0x000000010001ab04
+ (void)initialize;	// IMP=0x000000010001aa98
@property(nonatomic) _Bool completedInitialUpdate; // @synthesize completedInitialUpdate=_completedInitialUpdate;
@property(nonatomic, getter=isSavePending) _Bool savePending; // @synthesize savePending=_savePending;
@property(retain, nonatomic) HBFolder *rootFolder; // @synthesize rootFolder=_rootFolder;
@property(retain, nonatomic) NSURL *appRootURL; // @synthesize appRootURL=_appRootURL;
- (void).cxx_destruct;	// IMP=0x000000010001e684
- (void)_updateWithAppState:(id)arg1;	// IMP=0x000000010001dec4
- (void)_updateInstallProgressWithProxies:(id)arg1;	// IMP=0x000000010001da10
- (void)_refreshAllProxiesFromWorkspace;	// IMP=0x000000010001d43c
- (void)_updateWithUninstalledAppProxies:(id)arg1;	// IMP=0x000000010001d224
- (id)_arrangeApps:(id)arg1 withAdditionalApps:(id)arg2;	// IMP=0x000000010001c734
- (void)_updateWithInstalledAppProxies:(id)arg1;	// IMP=0x000000010001c308
- (_Bool)_load;	// IMP=0x000000010001bcf4
- (_Bool)_save;	// IMP=0x000000010001ba40
- (void)_setNeedsSave;	// IMP=0x000000010001b988
- (void)_didSerializeAppRoot:(id)arg1;	// IMP=0x000000010001b828
- (void)folderChangeNeedsSaving:(id)arg1;	// IMP=0x000000010001b81c
- (void)_appStateMonitorDidChange:(id)arg1;	// IMP=0x000000010001b780
- (void)applicationInstallsDidChange:(id)arg1;	// IMP=0x000000010001b688
- (void)applicationInstallsDidStart:(id)arg1;	// IMP=0x000000010001b590
- (void)applicationsDidInstall:(id)arg1;	// IMP=0x000000010001b490
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x000000010001b390
- (_Bool)_completeInitialUpdate;	// IMP=0x000000010001b2cc
- (void)dealloc;	// IMP=0x000000010001b140
- (id)initWithAppRootURL:(id)arg1;	// IMP=0x000000010001ae84

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

