//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@interface HBDockBackdropView : UICollectionReusableView
{
}

+ (void)initialize;	// IMP=0x0000000100012870
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100012cbc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100012aa0

@end

