//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVImageStackCollectionViewCell.h"

#import "HBRootItemObserver.h"
#import "SBIconProgressViewDelegate.h"

@class CALayer, HBRootItem, NSString, PBSBadgeValue, SBIconProgressView, TVBadgeOverlayView, TVVolatileNamedLayerStack, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;

@interface HBRootCell : TVImageStackCollectionViewCell <SBIconProgressViewDelegate, HBRootItemObserver>
{
    _Bool _pendingProgressViewUpdate;	// 8 = 0x8
    _Bool _allowsProgressAnimation;	// 9 = 0x9
    _Bool _isIdle;	// 10 = 0xa
    struct {
        unsigned int delegateDidLongPress:1;
    } _flags;	// 12 = 0xc
    _Bool _paused;	// 16 = 0x10
    _Bool _editing;	// 17 = 0x11
    _Bool _inDock;	// 18 = 0x12
    id <HBRootCellDelegate> _delegate;	// 24 = 0x18
    HBRootItem *_item;	// 32 = 0x20
    TVVolatileNamedLayerStack *_icon;	// 40 = 0x28
    double _installPercentage;	// 48 = 0x30
    long long _installProgressState;	// 56 = 0x38
    PBSBadgeValue *_badgeValue;	// 64 = 0x40
    long long _dropState;	// 72 = 0x48
    UIView *_flashView;	// 80 = 0x50
    TVBadgeOverlayView *_badgeOverlayView;	// 88 = 0x58
    UILongPressGestureRecognizer *_editGesture;	// 96 = 0x60
    UITapGestureRecognizer *_removeGesture;	// 104 = 0x68
    UITapGestureRecognizer *_selectGesture;	// 112 = 0x70
    SBIconProgressView *_progressView;	// 120 = 0x78
}

+ (id)_badgeNumberFormatter;	// IMP=0x000000010002fa70
+ (double)_radiosityStrengthForUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010002f75c
+ (id)_iconImageConfigurationForUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010002f620
+ (id)_progressMaskImage;	// IMP=0x000000010002ee08
+ (void)_setFocusDuration:(double)arg1;	// IMP=0x000000010002ec78
+ (double)_focusDuration;	// IMP=0x000000010002ec6c
+ (_Bool)automaticallyNotifiesObserversOfInDock;	// IMP=0x000000010002e7b8
@property(nonatomic, getter=isInDock) _Bool inDock; // @synthesize inDock=_inDock;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(retain, nonatomic) SBIconProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UITapGestureRecognizer *selectGesture; // @synthesize selectGesture=_selectGesture;
@property(retain, nonatomic) UITapGestureRecognizer *removeGesture; // @synthesize removeGesture=_removeGesture;
@property(retain, nonatomic) UILongPressGestureRecognizer *editGesture; // @synthesize editGesture=_editGesture;
@property(retain, nonatomic) TVBadgeOverlayView *badgeOverlayView; // @synthesize badgeOverlayView=_badgeOverlayView;
@property(retain, nonatomic) UIView *flashView; // @synthesize flashView=_flashView;
@property(nonatomic) long long dropState; // @synthesize dropState=_dropState;
@property(retain, nonatomic) PBSBadgeValue *badgeValue; // @synthesize badgeValue=_badgeValue;
@property(nonatomic) long long installProgressState; // @synthesize installProgressState=_installProgressState;
@property(nonatomic) double installPercentage; // @synthesize installPercentage=_installPercentage;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(retain, nonatomic) TVVolatileNamedLayerStack *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) HBRootItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <HBRootCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010002fd34
- (void)_updateRadiosityStrength;	// IMP=0x000000010002f830
- (void)_updateStackedImageConfiguration;	// IMP=0x000000010002f774
- (void)_longPressGesture:(id)arg1;	// IMP=0x000000010002f578
- (void)_updateBadgeValueView;	// IMP=0x000000010002f2b8
- (void)_updateProgressView;	// IMP=0x000000010002f09c
- (void)_updateOverlayLayer;	// IMP=0x000000010002efe4
- (void)_updateBadgeValue;	// IMP=0x000000010002ed94
- (void)_updateDisplayName;	// IMP=0x000000010002ed20
- (void)_updateInstallState;	// IMP=0x000000010002ec84
- (void)_updateForInDockState;	// IMP=0x000000010002ebd8
- (void)_unbindInDock;	// IMP=0x000000010002ebc4
- (void)_setInDock:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010002eaa8
- (double)_maxTitleWidthWithFocus:(_Bool)arg1;	// IMP=0x000000010002e9f4
- (void)_updateInDockBinding;	// IMP=0x000000010002e928
- (void)tvs_bindInDockBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x000000010002e834
- (id)InDockBinding;	// IMP=0x000000010002e7c0
- (void)badgeValueDidChange:(id)arg1;	// IMP=0x000000010002e7ac
- (void)displayNameDidChange:(id)arg1;	// IMP=0x000000010002e7a0
- (void)installStateDidChange:(id)arg1;	// IMP=0x000000010002e794
- (void)progressViewCanBeRemoved:(id)arg1;	// IMP=0x000000010002e784
- (_Bool)_applyKeyPathsAndRelativeValues:(id)arg1 forMotionEffect:(id)arg2;	// IMP=0x000000010002e5d0
- (long long)_focusedSound;	// IMP=0x000000010002e5c8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010002e4f8
- (void)setLayeredImageView:(id)arg1;	// IMP=0x000000010002e3e0
- (void)setImageStackView:(id)arg1;	// IMP=0x000000010002e3dc
- (id)imageStackView;	// IMP=0x000000010002e3d4
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x000000010002e324
- (void)prepareForReuse;	// IMP=0x000000010002e284
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x000000010002e1dc
- (void)_exitIdleMode;	// IMP=0x000000010002e0a0
- (void)_enterIdleMode;	// IMP=0x000000010002df58
@property(readonly, nonatomic, getter=_layerBelowFlash) CALayer *layerBelowFlash;
- (void)cancelConfirmFlash;	// IMP=0x000000010002de4c
- (void)beginConfirmFlash;	// IMP=0x000000010002d8b4
- (void)setDropState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x000000010002d808
- (void)dealloc;	// IMP=0x000000010002d3dc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010002d0d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

