//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSString, TVVibrantLabel;

@interface HBTopShelfSectionLabel : UICollectionReusableView
{
    TVVibrantLabel *_label;	// 8 = 0x8
}

+ (id)_font;	// IMP=0x000000010001a9c0
+ (struct CGSize)sizeForString:(id)arg1;	// IMP=0x000000010001a76c
@property(retain, nonatomic) TVVibrantLabel *label; // @synthesize label=_label;
- (void).cxx_destruct;	// IMP=0x000000010001aa84
@property(copy, nonatomic) NSString *title;
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x000000010001a4d8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010001a3c4

@end

