//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HBTopShelfBannerViewController.h"

#import "HBFolderObserver.h"
#import "HBTopShelfContentAvailableProtocol.h"

@class HBFolder, NSArray, NSString;

@interface HBTopShelfFolderBannerViewController : HBTopShelfBannerViewController <HBFolderObserver, HBTopShelfContentAvailableProtocol>
{
    CDStruct_55c0bed5 _flags;	// 8 = 0x8
    _Bool _contentAvailable;	// 12 = 0xc
    id <HBTopShelfContentAvailableProtocolDelegate> _delegate;	// 16 = 0x10
    HBFolder *_folder;	// 24 = 0x18
    NSArray *_appsInFolder;	// 32 = 0x20
}

@property(copy, nonatomic) NSArray *appsInFolder; // @synthesize appsInFolder=_appsInFolder;
@property(nonatomic, getter=isContentAvailable) _Bool contentAvailable; // @synthesize contentAvailable=_contentAvailable;
@property(retain, nonatomic) HBFolder *folder; // @synthesize folder=_folder;
@property(nonatomic) __weak id <HBTopShelfContentAvailableProtocolDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100022ec0
- (void)_updateContentAvailable;	// IMP=0x0000000100022dd0
- (void)_updateAppsInFolder;	// IMP=0x0000000100022bcc
- (void)itemsDidChange:(id)arg1;	// IMP=0x0000000100022b18
- (unsigned long long)numberOfItemsInCarouselView:(id)arg1;	// IMP=0x00000001000229b8
- (void)carouselView:(id)arg1 didPlayItemAtIndex:(unsigned long long)arg2;	// IMP=0x00000001000228cc
- (void)carouselView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;	// IMP=0x00000001000227e0
- (void)configureCell:(id)arg1 forItemAtIndex:(unsigned long long)arg2;	// IMP=0x00000001000226c0
- (Class)cellClass;	// IMP=0x00000001000226ac
- (void)dealloc;	// IMP=0x0000000100022638
- (id)initWithFolder:(id)arg1;	// IMP=0x0000000100022580
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000224d4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010002241c
- (id)init;	// IMP=0x0000000100022378

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

