//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSPreferences.h"

@class NSString;

@interface TVSPreferences (HeadBoardAdditions)
+ (id)sharedHeadBoardPreferences;	// IMP=0x0000000100012768
@property(readonly, nonatomic) NSString *alternativeApplicationOrder;
@property(readonly, nonatomic) _Bool shouldReloadOrderFromBundle;
@end

