//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ATVRadioSkipLimiter : NSObject
{
}

- (void)didSkipTrack:(id)arg1 withStation:(id)arg2 elapsedTime:(double)arg3 duration:(double)arg4;	// IMP=0x0000000100011190
- (unsigned long long)resultForAttemptToSkipTrack:(id)arg1 withStation:(id)arg2 elapsedTime:(double)arg3 duration:(double)arg4 skippedCount:(unsigned long long *)arg5 skipLimit:(unsigned long long *)arg6;	// IMP=0x0000000100010f68
- (_Bool)_skipFallsWithinThresholdWithElapsedTime:(double)arg1 duration:(double)arg2;	// IMP=0x0000000100010eb0
- (unsigned long long)_numberOfSkipsAvailableForStation:(id)arg1;	// IMP=0x0000000100010e3c
- (unsigned long long)_numberOfSkipsUsedForStation:(id)arg1;	// IMP=0x0000000100010d90
- (unsigned long long)_numberOfSkipsAllowedForStation:(id)arg1;	// IMP=0x0000000100010d30

@end

