//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSMetricsConfiguration, SSMetricsController;

@interface ATVRadioMetricsController : NSObject
{
    SSMetricsController *_metricsController;	// 8 = 0x8
    SSMetricsConfiguration *_globalConfiguration;	// 16 = 0x10
}

@property(retain, nonatomic) SSMetricsConfiguration *globalConfiguration; // @synthesize globalConfiguration=_globalConfiguration;
@property(retain, nonatomic) SSMetricsController *metricsController; // @synthesize metricsController=_metricsController;
- (void).cxx_destruct;	// IMP=0x0000000100006874
- (void)reportViewedHistoryWishListPage;	// IMP=0x00000001000067c8
- (void)reportViewedHistoryPlayedPage;	// IMP=0x00000001000067ac
- (void)reportViewedEditStationDetailPageForStation:(id)arg1;	// IMP=0x00000001000066ac
- (void)reportViewedEditStationsPage;	// IMP=0x0000000100006694
- (void)reportViewedGenrePageForGenre:(id)arg1;	// IMP=0x00000001000065e0
- (void)reportViewedAddStationPage;	// IMP=0x00000001000065c8
- (void)reportViewedStationsPage;	// IMP=0x00000001000065b0
- (void)reportViewedNowPlayingHistoryPageForStation:(id)arg1;	// IMP=0x00000001000064b0
- (void)reportViewedNowPlayingTrackPageForStation:(id)arg1;	// IMP=0x00000001000063b0
- (void)reportViewedTopShelfPostersPage;	// IMP=0x0000000100006394
- (void)reportViewedTopShelfWelcomePage;	// IMP=0x0000000100006378
- (id)_pageIdentifierForStation:(id)arg1;	// IMP=0x0000000100006204
- (void)_reportViewedPageWithType:(id)arg1 name:(id)arg2;	// IMP=0x00000001000061ac
- (void)_reportViewedPageWithType:(id)arg1 name:(id)arg2 pageIdentifier:(id)arg3 pageDetails:(id)arg4;	// IMP=0x0000000100006058
- (id)_clickEventForClearingSearchResults;	// IMP=0x0000000100005fb8
- (id)_clickEventForCancellingSearch;	// IMP=0x0000000100005f10
- (id)_clickEventForSelectingSearchResultsStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2 atIndex:(unsigned long long)arg3 withVisibleStations:(id)arg4;	// IMP=0x0000000100005dec
- (id)_clickEventForSelectingMoreResultsInSection:(id)arg1 atIndex:(unsigned long long)arg2 withVisibleStations:(id)arg3;	// IMP=0x0000000100005cd4
- (id)_clickEventWithVisibleStations:(id)arg1;	// IMP=0x0000000100005c24
- (id)_impressionEventForStations:(id)arg1;	// IMP=0x0000000100005b7c
- (id)_impressionIdentifiersForStations:(id)arg1;	// IMP=0x0000000100005970
- (id)_pageEventForSearchResultsWithSearchTerm:(id)arg1 startDate:(id)arg2 endDate:(id)arg3 cached:(_Bool)arg4;	// IMP=0x000000010000584c
- (id)_searchEventWithSearchTerm:(id)arg1 forBlankPage:(_Bool)arg2;	// IMP=0x00000001000057b0
- (id)_signOutEvent;	// IMP=0x0000000100005760
- (id)_signInEvent;	// IMP=0x0000000100005710
- (id)_blankPageEventWithDetails:(id)arg1;	// IMP=0x0000000100005654
- (void)reportSelectedSearchResultStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2 atIndex:(unsigned long long)arg3 withVisibleStations:(id)arg4;	// IMP=0x00000001000055c0
- (void)reportClearedSearch;	// IMP=0x0000000100005574
- (void)reportCancelledSearch;	// IMP=0x0000000100005528
- (void)reportSelectedShowMoreResultsForSearchResultSection:(id)arg1 atIndex:(unsigned long long)arg2 withVisibleStations:(id)arg3;	// IMP=0x00000001000054a4
- (void)reportVisibleSearchResultStations:(id)arg1;	// IMP=0x0000000100005424
- (void)reportReceivedResponse:(id)arg1 forSearchWithTerm:(id)arg2 withRequestStartDate:(id)arg3 responseEndDate:(id)arg4 cached:(_Bool)arg5;	// IMP=0x0000000100005330
- (void)reportStartedSearchWithTerm:(id)arg1 forBlankPage:(_Bool)arg2;	// IMP=0x00000001000052e4
- (void)reportSignedOut;	// IMP=0x0000000100005298
- (void)reportSignedIn;	// IMP=0x000000010000524c
- (void)reportViewedBlankNeverPlaySearchResultsPage;	// IMP=0x00000001000051f8
- (void)reportViewedBlankPlayMoreSearchResultsPage;	// IMP=0x00000001000051a4
- (void)reportViewedBlankCreateStationSearchResultsPage;	// IMP=0x0000000100005150
- (id)_locationsForStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2 atIndex:(unsigned long long)arg3;	// IMP=0x0000000100004ff0
- (id)_locationsForMoreResultsButtonInSection:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x0000000100004e98
- (id)_searchMoreResultsEventLocationForSection:(id)arg1;	// IMP=0x0000000100004df4
- (id)_searchResultStationDescriptionItemForStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2;	// IMP=0x0000000100004d70
- (id)_searchResultsSectionEventLocationForSection:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x0000000100004cf4
- (id)_searchResultsListEventLocation;	// IMP=0x0000000100004c94
- (id)_eventLocationWithType:(id)arg1 position:(unsigned long long)arg2 fieldData:(id)arg3;	// IMP=0x0000000100004bb0
- (id)_targetIdentifierForSection:(id)arg1;	// IMP=0x0000000100004b4c
- (id)_targetIdentifierForStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2;	// IMP=0x0000000100004ae0
- (id)_stationDictionaryForStationAtIndex:(unsigned long long)arg1 inSection:(id)arg2;	// IMP=0x0000000100004a00
- (id)_targetIdentifierForDictionary:(id)arg1;	// IMP=0x0000000100004820
- (id)_impressionsIdentifierForStationDictionary:(id)arg1;	// IMP=0x0000000100004618
- (id)_targetIdentifierKeys;	// IMP=0x00000001000045bc
- (id)_customValueFieldsMappingDictionary;	// IMP=0x0000000100004560
- (id)_singleValueFieldsMappingDictionary;	// IMP=0x0000000100004504
- (id)_fieldsMappingDictionary;	// IMP=0x00000001000044b0
- (id)_valueForBagKey:(id)arg1;	// IMP=0x0000000100004428
- (void)_setGlobalConfiguration:(id)arg1;	// IMP=0x0000000100004360
- (void)_setPageConfiguration:(id)arg1;	// IMP=0x00000001000042c0
- (void)_insertEvent:(id)arg1;	// IMP=0x0000000100003e64
- (void)_urlBagDidLoad:(id)arg1;	// IMP=0x0000000100003de8
- (void)_reloadValuesFromBag;	// IMP=0x0000000100003d90
- (void)dealloc;	// IMP=0x0000000100003d04
- (id)init;	// IMP=0x0000000100003c24

@end

