//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicPlaybackHelper : NSObject
{
}

+ (void)_addPAFFeatureNameToDictionary:(id)arg1;	// IMP=0x000000010008ca70
+ (id)_PAFFeatureName;	// IMP=0x000000010008ca14
+ (void)_addMediaItemMetadata:(id)arg1 toMediaItems:(id)arg2;	// IMP=0x000000010008c7a0
+ (void)_addToUpNextWithDataResults:(id)arg1 mediaItemMetadata:(id)arg2;	// IMP=0x000000010008c680
+ (void)_playNextWithDataResults:(id)arg1 mediaItemMetadata:(id)arg2;	// IMP=0x000000010008c560
+ (void)_playNowWithDataResults:(id)arg1 fromIndex:(long long)arg2 shuffle:(_Bool)arg3 mediaItemProperties:(id)arg4;	// IMP=0x000000010008c26c
+ (void)_playNowWithDataResults:(id)arg1;	// IMP=0x000000010008c254
+ (void)_playWithQueryResults:(id)arg1 playbackAction:(unsigned long long)arg2 mediaItemMetadata:(id)arg3;	// IMP=0x000000010008c0ac
+ (void)_playLibraryPlaylist:(id)arg1 optionalTracks:(id)arg2 playAction:(unsigned long long)arg3 fromIndex:(long long)arg4 shuffle:(_Bool)arg5;	// IMP=0x000000010008bc7c
+ (void)_playLibraryAlbum:(id)arg1 optionalTracks:(id)arg2 playAction:(unsigned long long)arg3 fromIndex:(long long)arg4 shuffle:(_Bool)arg5;	// IMP=0x000000010008ba20
+ (id)_PAFMediaItemMetadataForAlbum:(id)arg1;	// IMP=0x000000010008b8a4
+ (_Bool)isPlayingLibraryItemWithPersistentID:(long long)arg1 withPlayer:(id)arg2;	// IMP=0x000000010008b7c8
+ (void)playLibraryComposer:(id)arg1 shuffle:(_Bool)arg2;	// IMP=0x000000010008b62c
+ (void)playLibraryArtist:(id)arg1 shuffle:(_Bool)arg2;	// IMP=0x000000010008b2d4
+ (void)playLibraryPlaylist:(id)arg1 optionalTracks:(id)arg2 fromIndex:(long long)arg3 shuffle:(_Bool)arg4;	// IMP=0x000000010008b268
+ (void)playLibraryAlbum:(id)arg1 optionalTracks:(id)arg2 fromIndex:(long long)arg3 shuffle:(_Bool)arg4;	// IMP=0x000000010008b1fc
+ (void)playDataItems:(id)arg1 fromIndex:(long long)arg2 withAddedMediaItemMetadata:(id)arg3 shuffle:(_Bool)arg4;	// IMP=0x000000010008b194
+ (void)playDataItems:(id)arg1 fromIndex:(long long)arg2 shuffle:(_Bool)arg3;	// IMP=0x000000010008b064
+ (void)playItemType:(unsigned long long)arg1 withPersistentID:(id)arg2;	// IMP=0x000000010008b054
+ (void)playItemType:(unsigned long long)arg1 withPersistentID:(id)arg2 playbackAction:(unsigned long long)arg3 mediaItemMetadata:(id)arg4;	// IMP=0x000000010008a730
+ (void)playItemType:(unsigned long long)arg1 withPersistentID:(id)arg2 playbackAction:(unsigned long long)arg3;	// IMP=0x000000010008a720

@end

