//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicLibraryCollectionViewController.h"

@interface TVMusicLibraryArtistsViewController : TVMusicLibraryCollectionViewController
{
}

- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000945e4
- (id)placeholderImage;	// IMP=0x0000000100094574
- (void)_handlePlayPause:(id)arg1;	// IMP=0x0000000100094368
- (void)viewDidLoad;	// IMP=0x0000000100094214
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009419c
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100094194
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000940e8
- (id)init;	// IMP=0x000000010009404c

@end

