//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSString, TVAnimatedLabel, TVSImageProxy, UIImage, UIImageView, _UIFloatingContentView;

@interface TVMusicLibraryCollectionViewCell : UICollectionViewCell
{
    _UIFloatingContentView *_floatingView;	// 8 = 0x8
    UIImageView *_placeholderImageView;	// 16 = 0x10
    TVAnimatedLabel *_titleLabel;	// 24 = 0x18
    TVAnimatedLabel *_subTitleLabel;	// 32 = 0x20
    UIImageView *_explicitBadgeView;	// 40 = 0x28
    _Bool _circular;	// 48 = 0x30
    _Bool _isExplicit;	// 49 = 0x31
    TVSImageProxy *_imageProxy;	// 56 = 0x38
    UIImage *_image;	// 64 = 0x40
    NSString *_title;	// 72 = 0x48
    NSString *_subTitle;	// 80 = 0x50
    UIImageView *_imageView;	// 88 = 0x58
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool isExplicit; // @synthesize isExplicit=_isExplicit;
@property(nonatomic) _Bool circular; // @synthesize circular=_circular;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) TVSImageProxy *imageProxy; // @synthesize imageProxy=_imageProxy;
- (void).cxx_destruct;	// IMP=0x0000000100056c7c
- (void)_updateShadowForLabel:(id)arg1 inFocus:(_Bool)arg2;	// IMP=0x0000000100056ac4
- (void)_updateColorsForUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100056ab8
- (void)_setLabelTextColorsForUserInterfaceStyle:(long long)arg1;	// IMP=0x00000001000567c0
- (void)_setLabelTextColors;	// IMP=0x0000000100056768
- (void)_setWidthForLabel:(id)arg1;	// IMP=0x0000000100056678
- (void)_setLabelPositionsChangeY:(_Bool)arg1;	// IMP=0x00000001000562d4
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000561cc
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100055f74
- (id)_addSubheadLabelWithFont:(id)arg1 textColor:(id)arg2;	// IMP=0x0000000100055e1c
- (unsigned long long)controlState;	// IMP=0x0000000100055dd4
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x0000000100055d60
- (_Bool)canBecomeFocused;	// IMP=0x0000000100055d58
- (void)layoutSubviews;	// IMP=0x0000000100055d04
- (void)prepareForReuse;	// IMP=0x0000000100055bdc
- (void)_setShadows;	// IMP=0x000000010005599c
@property(retain, nonatomic) UIImage *placeholderImage;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100054b04

@end

