//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class JSValue, NSArray, NSDictionary, NSString;

@protocol TVMusicJSObject <JSExport>
@property(readonly) _Bool isMusicLibraryInitialized;
@property(readonly) unsigned long long tasteTypeHate;
@property(readonly) unsigned long long tasteTypeLove;
@property(readonly) unsigned long long tasteTypeNeutral;
@property(readonly) unsigned long long contentTypePlaylist;
@property(readonly) unsigned long long contentTypeAlbum;
@property(readonly) unsigned long long contentTypeMusicVideo;
@property(readonly) unsigned long long contentTypeSong;
- (void)presentContextMenuForItem:(NSDictionary *)arg1:(JSValue *)arg2;
- (void)presentDetailView:(NSString *)arg1:(NSString *)arg2:(JSValue *)arg3;
- (void)presentExplicitRestrictionAlertIfNeededOfType:(NSString *)arg1:(JSValue *)arg2;
- (_Bool)addSongToPlaylist:(NSDictionary *)arg1;
- (void)getCurrentIsPlayingState:(JSValue *)arg1;
- (void)getNowPlayingInfoWithOptions:(NSDictionary *)arg1:(JSValue *)arg2;
- (void)getNowPlayingInfo:(JSValue *)arg1;
- (JSValue *)queryMusicLibraryForCollection:(NSString *)arg1:(NSString *)arg2:(NSDictionary *)arg3:(JSValue *)arg4;
- (JSValue *)querySongsForAlbum:(NSString *)arg1:(NSDictionary *)arg2:(struct _NSRange)arg3:(JSValue *)arg4;
- (JSValue *)querySongsForArtist:(NSString *)arg1:(NSDictionary *)arg2:(struct _NSRange)arg3:(JSValue *)arg4;
- (JSValue *)querySongsForPlaylist:(NSString *)arg1:(NSDictionary *)arg2:(struct _NSRange)arg3:(JSValue *)arg4;
- (JSValue *)querySongsForPlaylistWithPersistentID:(NSString *)arg1:(struct _NSRange)arg2:(JSValue *)arg3;
- (JSValue *)queryMusicLibrary:(NSArray *)arg1:(struct _NSRange)arg2:(NSArray *)arg3:(JSValue *)arg4:(JSValue *)arg5;
- (void)removeItemsFromMusicLibraryWithSagaIDs:(NSArray *)arg1:(JSValue *)arg2;
- (void)removePlaylistFromMusicLibraryWithGlobalID:(NSString *)arg1:(JSValue *)arg2;
- (void)addPlaylistToMusicLibraryWithGlobalID:(NSString *)arg1:(JSValue *)arg2;
- (void)addToMusicLibraryWithAdamID:(long long)arg1:(JSValue *)arg2;
- (void)queryMusicLibraryForPlaylistWithCloudGlobalID:(NSString *)arg1:(JSValue *)arg2;
- (void)queryMusicLibraryForSongsWithAdamIDs:(NSArray *)arg1:(JSValue *)arg2;
- (unsigned long long)tasteTypeForPlaylistGlobalID:(NSString *)arg1;
- (unsigned long long)tasteTypeForAdamID:(NSString *)arg1;
- (void)setTasteType:(NSString *)arg1:(unsigned long long)arg2:(unsigned long long)arg3:(JSValue *)arg4;
- (void)getRecentRadioStations:(JSValue *)arg1;
- (void)playRadioStation:(NSDictionary *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
- (void)playItems:(NSArray *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
@end

