//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSMediaRemoteCommandHandler.h"

@interface TVMusicMediaRemoteCommandHandler : TVSMediaRemoteCommandHandler
{
}

- (void)_updateSupportedCommandsForPlayer:(id)arg1;	// IMP=0x000000010007615c

@end

