//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface TVMusicCloudProgressView : UIView
{
    UILabel *_messageLabel;	// 8 = 0x8
    UIView *_progressView;	// 16 = 0x10
    UIView *_progressCompleteView;	// 24 = 0x18
    float _progressPercent;	// 32 = 0x20
}

@property(nonatomic) float progressPercent; // @synthesize progressPercent=_progressPercent;
- (void).cxx_destruct;	// IMP=0x000000010008d2e8
- (void)_setColorsForUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010008d0f8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010008d02c
- (void)dealloc;	// IMP=0x000000010008cf44
- (id)initWithMessage:(id)arg1;	// IMP=0x000000010008cae8

@end

