//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CALayer, NSArray, NSString, TVImageView, UILabel, UIView, _UIFloatingContentView;

@interface TVMusicPlaylistLockupViewCell : UICollectionViewCell
{
    _Bool _createdImageViews;	// 8 = 0x8
    _UIFloatingContentView *_floatingView;	// 16 = 0x10
    NSArray *_imageViews;	// 24 = 0x18
    UIView *_titleBlockView;	// 32 = 0x20
    UILabel *_titleLabel;	// 40 = 0x28
    UILabel *_subtitleLabel;	// 48 = 0x30
    TVImageView *_titleBackgroundImageView;	// 56 = 0x38
    NSString *_playlistID;	// 64 = 0x40
    CALayer *_titleGradientLayer;	// 72 = 0x48
}

+ (id)playlistViewFromElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010008d33c
@property(retain, nonatomic) CALayer *titleGradientLayer; // @synthesize titleGradientLayer=_titleGradientLayer;
@property(retain, nonatomic) NSString *playlistID; // @synthesize playlistID=_playlistID;
@property(retain, nonatomic) TVImageView *titleBackgroundImageView; // @synthesize titleBackgroundImageView=_titleBackgroundImageView;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *titleBlockView; // @synthesize titleBlockView=_titleBlockView;
@property(nonatomic) _Bool createdImageViews; // @synthesize createdImageViews=_createdImageViews;
@property(retain, nonatomic) NSArray *imageViews; // @synthesize imageViews=_imageViews;
@property(retain, nonatomic) _UIFloatingContentView *floatingView; // @synthesize floatingView=_floatingView;
- (void).cxx_destruct;	// IMP=0x000000010008f6b4
- (id)_randomColor;	// IMP=0x000000010008f3f8
- (void)_configureLabel:(id)arg1 withTextElement:(id)arg2 maxWidth:(double)arg3;	// IMP=0x000000010008f264
- (struct CGRect)_scaleRect:(struct CGRect)arg1 withStyle:(id)arg2;	// IMP=0x000000010008f148
- (void)layoutSubviews;	// IMP=0x000000010008f064
- (void)layoutWithElement:(id)arg1;	// IMP=0x000000010008db34
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010008daa8
- (void)prepareForReuse;	// IMP=0x000000010008da54
- (_Bool)canBecomeFocused;	// IMP=0x000000010008da4c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010008d408

@end

