//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicRestrictionsUI : NSObject
{
}

+ (long long)explicitRestrictionAlertTypeForTypeString:(id)arg1;	// IMP=0x0000000100010c5c
+ (void)presentExplicitRestrictionAlertIfNeededOfType:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100010420

@end

