//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSBaseMediaItem.h"

@class MPNowPlayingContentItem, NSString;

@interface TVSBaseMediaItem (TVMusic)
- (void)_updateNowPlayingContentItem:(id)arg1;	// IMP=0x000000010000bcb4
- (void)_setCachedNowPlayingContentItem:(id)arg1;	// IMP=0x000000010000bca4
- (id)_cachedNowPlayingContentItem;	// IMP=0x000000010000bc98
- (void)refreshNowPlayingContentItem;	// IMP=0x000000010000bc48
@property(readonly, nonatomic) MPNowPlayingContentItem *nowPlayingContentItem;
@property(readonly, nonatomic) NSString *nowPlayingContentItemIdentifier;
@property(readonly, nonatomic) unsigned long long serviceType;
@end

