//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "_TVIVideoBackgroundVideoViewDelegate.h"

@class NSArray, NSObject<OS_dispatch_source>, NSString, TVIDaylightCalculator, _TVIVideoBackgroundVideoView;

@interface TVIBackgroundView : UIView <_TVIVideoBackgroundVideoViewDelegate>
{
    _TVIVideoBackgroundVideoView *_backgroundVideoView;	// 8 = 0x8
    TVIDaylightCalculator *_daylightCalculator;	// 16 = 0x10
    long long _mediaItemIndex;	// 24 = 0x18
    NSArray *_mediaItems;	// 32 = 0x20
    id _preferencesObserver;	// 40 = 0x28
    id _setupPreferencesObserver;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_sunriseSunsetTimer;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100008584
- (void)_updateBackgroundChannels;	// IMP=0x00000001000081c8
- (void)_transitionToMediaItemAtIndex:(long long)arg1 elapsedTime:(double)arg2;	// IMP=0x0000000100007c14
- (void)_scheduleSunriseSunsetTimer;	// IMP=0x0000000100007a0c
- (id)_mediaItemsForAssets:(id)arg1;	// IMP=0x00000001000075f8
- (_Bool)_canUseNetworkAssets;	// IMP=0x0000000100007590
- (void)_beginPlayback;	// IMP=0x000000010000725c
- (id)_backgroundVideoViewForMediaItem:(id)arg1 elapsedTime:(double)arg2;	// IMP=0x00000001000070f8
- (void)saveState;	// IMP=0x0000000100006f84
- (void)playPauseAction;	// IMP=0x0000000100006f0c
- (void)pause;	// IMP=0x0000000100006e74
- (void)play;	// IMP=0x0000000100006ddc
- (void)cycleAvailableBackgroundsInDirection:(long long)arg1;	// IMP=0x0000000100006d18
- (void)_locationDidChangeNotification:(id)arg1;	// IMP=0x0000000100006c94
- (void)_availableEntriesDidChangeNotification:(id)arg1;	// IMP=0x0000000100006c88
- (void)videoBackgroundVideoViewDidPlayToEnd:(id)arg1;	// IMP=0x0000000100006c78
- (void)dealloc;	// IMP=0x0000000100006b6c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000066a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

