//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TVSExternalControlSystemDelegate.h"

@class NSString, TVSExternalControlSystem, TVSettings3rdPartyRemotesFacade, TVSettingsBluetoothFacade, TVSettingsSelectIRConfigurationViewController;

@interface TVSettingsRemotesViewController : TSKViewController <TVSExternalControlSystemDelegate>
{
    _Bool _updatingPairedAppleRemoteState;	// 8 = 0x8
    _Bool _pairedWithAppleRemote;	// 9 = 0x9
    TVSettingsSelectIRConfigurationViewController *_selectIRConfigurationViewController;	// 16 = 0x10
    TVSExternalControlSystem *_externalControlSystem;	// 24 = 0x18
    TVSettingsBluetoothFacade *_bluetoothFacade;	// 32 = 0x20
    TVSettings3rdPartyRemotesFacade *_remoteFacade;	// 40 = 0x28
}

+ (id)stringForCurrentVolumePolicyWithExternalControlSystem:(id)arg1;	// IMP=0x000000010007e2f4
@property(retain, nonatomic) TVSettings3rdPartyRemotesFacade *remoteFacade; // @synthesize remoteFacade=_remoteFacade;
@property(retain, nonatomic) TVSettingsBluetoothFacade *bluetoothFacade; // @synthesize bluetoothFacade=_bluetoothFacade;
@property(retain, nonatomic) TVSExternalControlSystem *externalControlSystem; // @synthesize externalControlSystem=_externalControlSystem;
@property(nonatomic, getter=isPairedWithAppleRemote) _Bool pairedWithAppleRemote; // @synthesize pairedWithAppleRemote=_pairedWithAppleRemote;
@property(nonatomic, getter=isUpdatingPairedAppleRemoteState) _Bool updatingPairedAppleRemoteState; // @synthesize updatingPairedAppleRemoteState=_updatingPairedAppleRemoteState;
@property(nonatomic) __weak TVSettingsSelectIRConfigurationViewController *selectIRConfigurationViewController; // @synthesize selectIRConfigurationViewController=_selectIRConfigurationViewController;
- (void).cxx_destruct;	// IMP=0x0000000100084de8
- (void)_remoteFacadeConfigurationChanged;	// IMP=0x0000000100084c90
- (void)_externalControlSystemConfigurationChanged;	// IMP=0x0000000100084c84
- (void)_updateAppleRemotePairedStateWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100084af4
- (void)_fetchAppleRemotePairedState;	// IMP=0x0000000100084a70
- (void)_showLearnedRemoteFinishedAlertWithName:(id)arg1;	// IMP=0x0000000100084764
- (void)_setUpPlaybackButtonsForRemoteWithUUID:(id)arg1;	// IMP=0x00000001000843e0
- (void)_showLearnedRemoteOptionsAlertForDevice:(id)arg1 withName:(id)arg2;	// IMP=0x0000000100083f50
- (void)_learnNewRemote;	// IMP=0x0000000100083c84
- (void)_showSystemControlUnavailableDialog;	// IMP=0x0000000100083a88
- (id)_valueStringForTogglePower;	// IMP=0x0000000100083978
- (id)_valueStringForOneTouchPlay;	// IMP=0x0000000100083868
- (_Bool)_canProgramBluetoothRemote;	// IMP=0x0000000100083854
- (_Bool)_showLearnedRemotes;	// IMP=0x00000001000837a8
- (id)_systemControlSettingsGroups;	// IMP=0x0000000100082a24
- (id)_remoteSettingsGroups;	// IMP=0x0000000100081b74
- (id)_appleRemoteSettingGroups;	// IMP=0x0000000100080dd4
- (void)externalControlSystemDidUpdatePolicy:(id)arg1;	// IMP=0x0000000100080d28
- (void)externalControlSystem:(id)arg1 didReceiveDeviceEvent:(long long)arg2;	// IMP=0x0000000100080c7c
- (void)externalControlSystem:(id)arg1 didChangeReadyStatus:(_Bool)arg2;	// IMP=0x0000000100080bd0
- (void)_activateKonamiCodeForUnpair:(id)arg1;	// IMP=0x0000000100080b7c
- (void)_activateKonamiCodeForFirmwareUpdate:(id)arg1;	// IMP=0x0000000100080af4
- (void)_showSelectedLearnedRemoteOptionsAlertForDevice:(id)arg1 withName:(id)arg2;	// IMP=0x000000010007f684
- (void)_didSelectLearnedRemoteItem:(id)arg1;	// IMP=0x000000010007f478
- (void)_didSelectLearnNewRemoteItem:(id)arg1;	// IMP=0x000000010007f0e8
- (void)_didSelectPairAppleRemoteItem:(id)arg1;	// IMP=0x000000010007efe4
- (void)_didSelectVolumeControlItem:(id)arg1;	// IMP=0x000000010007ef14
- (void)_togglePowerItem:(id)arg1;	// IMP=0x000000010007ee74
- (void)_toggleOneTouchPlayItem:(id)arg1;	// IMP=0x000000010007edf8
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010007ebf4
- (id)loadSettingGroups;	// IMP=0x000000010007eb08
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010007eab8
- (void)viewDidLoad;	// IMP=0x000000010007e9f4
- (void)dealloc;	// IMP=0x000000010007e978
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010007e6e4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

