//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSFormatter, NSMutableDictionary, TVSettingsLocationItem;

@interface TVSettingsLocationServicesFacade : NSObject
{
    NSArray *_applicationItems;	// 8 = 0x8
    NSArray *_systemServiceItems;	// 16 = 0x10
    TVSettingsLocationItem *_timeZoneItem;	// 24 = 0x18
    NSMutableDictionary *_items;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x000000010007a550
@property(copy, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
@property(readonly, nonatomic) TVSettingsLocationItem *timeZoneItem; // @synthesize timeZoneItem=_timeZoneItem;
@property(copy, nonatomic) NSArray *systemServiceItems; // @synthesize systemServiceItems=_systemServiceItems;
@property(copy, nonatomic) NSArray *applicationItems; // @synthesize applicationItems=_applicationItems;
- (void).cxx_destruct;	// IMP=0x000000010007b7b8
- (void)_updateItems:(_Bool)arg1;	// IMP=0x000000010007ad48
- (id)_whitelistedSystemServices;	// IMP=0x000000010007ac50
@property(readonly, nonatomic) NSFormatter *accessTypeFormatter;
- (id)itemForBundleID:(id)arg1;	// IMP=0x000000010007a7a8
@property(nonatomic) _Bool locationServicesEnabled;
- (id)init;	// IMP=0x000000010007a5d0

@end

