//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKPreviewViewController.h"

@class TVConferenceRoomDisplaySmallView;

@interface TVSettingsCRDPreviewViewController : TSKPreviewViewController
{
    TVConferenceRoomDisplaySmallView *_crdView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010009aa3c
- (id)_crdView;	// IMP=0x000000010009a8cc
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010009a744
- (void)viewDidLoad;	// IMP=0x000000010009a650
- (void)dealloc;	// IMP=0x000000010009a574
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010009a464

@end

