//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_TVInterfaceCreatingPrivate.h"

@class NSString;

@interface TVSettingsInterfaceFactory : NSObject <_TVInterfaceCreatingPrivate>
{
}

+ (id)sharedInterfaceFactory;	// IMP=0x000000010009193c
+ (void)initialize;	// IMP=0x00000001000918cc
- (id)_styleSheetURLForTemplate:(id)arg1;	// IMP=0x0000000100091a0c
- (void)setup;	// IMP=0x00000001000919bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

