//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class TSKPreviewViewController, TSKSettingItem, TVSettingsAppsFacade;

@interface TVSettingsAppsViewController : TSKViewController
{
    _Bool _nowPlayingEnabled;	// 8 = 0x8
    TVSettingsAppsFacade *_appsFacade;	// 16 = 0x10
    TSKSettingItem *_lastFocusedItem;	// 24 = 0x18
    TSKPreviewViewController *_appIconPreviewViewController;	// 32 = 0x20
}

@property(retain, nonatomic) TSKPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(nonatomic) _Bool nowPlayingEnabled; // @synthesize nowPlayingEnabled=_nowPlayingEnabled;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
@property(retain, nonatomic) TVSettingsAppsFacade *appsFacade; // @synthesize appsFacade=_appsFacade;
- (void).cxx_destruct;	// IMP=0x0000000100064d88
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000648b4
- (void)tableView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000647f4
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000644fc
- (id)loadSettingGroups;	// IMP=0x0000000100063750
- (void)dealloc;	// IMP=0x00000001000636e0
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000634e0

@end

