//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class TSKBundleLoader;

@interface TVSettingsMainViewController : TSKViewController
{
    TSKBundleLoader *_developerBundleLoader;	// 8 = 0x8
}

@property(retain, nonatomic) TSKBundleLoader *developerBundleLoader; // @synthesize developerBundleLoader=_developerBundleLoader;
- (void).cxx_destruct;	// IMP=0x000000010001e5d8
- (void)_updateDeveloperBundleLoader;	// IMP=0x000000010001e460
- (id)_airPlayViewController;	// IMP=0x000000010001e2e8
- (void)_sleepNow:(id)arg1;	// IMP=0x000000010001e29c
- (id)loadSettingGroups;	// IMP=0x000000010001d5bc
- (id)title;	// IMP=0x000000010001d54c
- (void)dealloc;	// IMP=0x000000010001d4f0
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010001d460

@end

