//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TSKSettingItemEditingController.h"

@class NSString, TSKSettingItem;

@interface TVSettingsProfileInfoViewController : TSKViewController <TSKSettingItemEditingController>
{
    TSKSettingItem *_profileInfoItem;	// 8 = 0x8
    TSKSettingItem *_editingItem;	// 16 = 0x10
    id <TSKSettingItemEditingControllerDelegate> _editingDelegate;	// 24 = 0x18
}

@property(nonatomic) __weak id <TSKSettingItemEditingControllerDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
@property(retain, nonatomic) TSKSettingItem *editingItem; // @synthesize editingItem=_editingItem;
- (void).cxx_destruct;	// IMP=0x000000010007df80
- (void)_getProfileTitles:(id *)arg1 values:(id *)arg2;	// IMP=0x000000010007d984
- (void)removeProfile:(id)arg1;	// IMP=0x000000010007d89c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010007d69c
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010007d630
- (void)loadView;	// IMP=0x000000010007d56c
- (id)loadSettingGroups;	// IMP=0x000000010007d2d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

