//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TVSettingsBluetoothFacade : NSObject
{
    NSArray *_sortDescriptors;	// 8 = 0x8
    int _derpDidStartNotificationToken;	// 16 = 0x10
    _Bool _derpDidStartNotificationTokenIsValid;	// 20 = 0x14
    int _derpDidStopNotificationToken;	// 24 = 0x18
    _Bool _derpDidStopNotificationTokenIsValid;	// 28 = 0x1c
    NSArray *_remotes;	// 32 = 0x20
    NSArray *_myDevices;	// 40 = 0x28
    NSArray *_otherDevices;	// 48 = 0x30
    NSArray *_connectedDevices;	// 56 = 0x38
}

+ (long long)numberOfConnectedDevices;	// IMP=0x00000001000089e4
+ (long long)numberOfConnectedRemotes;	// IMP=0x0000000100008860
+ (void)updateDevice:(id)arg1;	// IMP=0x0000000100008774
+ (void)unpairDevice:(id)arg1;	// IMP=0x0000000100008704
+ (void)disconnectDevice:(id)arg1;	// IMP=0x0000000100008694
+ (void)connectDevice:(id)arg1;	// IMP=0x0000000100008624
+ (id)deviceStatusFormatterForDeviceType:(long long)arg1 showConnectedState:(_Bool)arg2;	// IMP=0x00000001000070d8
@property(copy, nonatomic) NSArray *connectedDevices; // @synthesize connectedDevices=_connectedDevices;
@property(copy, nonatomic) NSArray *otherDevices; // @synthesize otherDevices=_otherDevices;
@property(copy, nonatomic) NSArray *myDevices; // @synthesize myDevices=_myDevices;
@property(copy, nonatomic) NSArray *remotes; // @synthesize remotes=_remotes;
- (void).cxx_destruct;	// IMP=0x0000000100008ba4
- (id)_deviceSortDescriptors;	// IMP=0x0000000100008a60
@property(nonatomic) _Bool filterDeviceScan;
- (void)stopScanning;	// IMP=0x00000001000085d4
- (void)startScanning;	// IMP=0x0000000100008584
- (void)_managerDidUpdate:(id)arg1;	// IMP=0x0000000100008400
- (void)_updateConnectedDevicesWithSet:(id)arg1;	// IMP=0x0000000100008320
- (void)_updateOtherDevicesWithSet:(id)arg1;	// IMP=0x0000000100008240
- (void)_updateMyDevicesWithSet:(id)arg1;	// IMP=0x000000010000811c
- (void)_updateRemotesWithSet:(id)arg1;	// IMP=0x0000000100007f2c
- (void)_willEnterForeground:(id)arg1;	// IMP=0x0000000100007f20
- (void)_didEnterBackground:(id)arg1;	// IMP=0x0000000100007f14
- (void)dealloc;	// IMP=0x0000000100007e40
- (id)init;	// IMP=0x0000000100007a38

@end

