//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsSetupViewController : TSKViewController
{
}

- (void)_launchTVWhatsNew;	// IMP=0x0000000100051fc8
- (void)_handleResetAllSettingsResultWithError:(id)arg1;	// IMP=0x0000000100051d7c
- (void)_showFailureWithText:(id)arg1;	// IMP=0x0000000100051c24
- (void)_showConfirmRestore;	// IMP=0x00000001000518e0
- (void)_showConfirmReset;	// IMP=0x0000000100051438
- (id)_resetViewController;	// IMP=0x0000000100051054
- (id)loadSettingGroups;	// IMP=0x0000000100050794

@end

