//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "AKAppleIDAuthenticationInAppContextDelegate.h"

@class NSString;

@interface TVSettingsHomeSharingAccountViewController : TSKViewController <AKAppleIDAuthenticationInAppContextDelegate>
{
    _Bool _authenticationInProgress;	// 8 = 0x8
}

- (void)contextDidDismissLoginAlertController:(id)arg1;	// IMP=0x0000000100039504
- (void)contextWillDismissLoginAlertController:(id)arg1;	// IMP=0x0000000100039500
- (void)contextDidPresentLoginAlertController:(id)arg1;	// IMP=0x00000001000394c8
- (void)_showErrorDialog;	// IMP=0x0000000100039230
- (void)_showConfirmDisableDialog;	// IMP=0x0000000100038f50
- (void)_showSuccessDialog:(id)arg1;	// IMP=0x0000000100038c64
- (void)_showLoginWithAccount:(id)arg1;	// IMP=0x0000000100038570
- (void)_showShouldUseAccountDialog:(id)arg1;	// IMP=0x0000000100037f80
- (void)_updateDisableItem:(id)arg1;	// IMP=0x0000000100037e00
- (void)_updateEnableItem:(id)arg1;	// IMP=0x0000000100037c70
- (void)_disableHomeSharing;	// IMP=0x0000000100037c64
- (void)_enableHomeSharing;	// IMP=0x0000000100037bc0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100037b04
@property(getter=isAuthenticationInProgress) _Bool authenticationInProgress;
- (id)loadSettingGroups;	// IMP=0x0000000100037624
- (void)dealloc;	// IMP=0x0000000100037598
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100037504

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

