//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBSOSUpdateServiceDelegate.h"

@class NSString, TVOSUpdateView, UITapGestureRecognizer;

@interface TVSettingsOSRestoreViewController : UIViewController <PBSOSUpdateServiceDelegate>
{
    _Bool _cancelOnExit;	// 8 = 0x8
    TVOSUpdateView *_progressView;	// 16 = 0x10
    UITapGestureRecognizer *_menuRecognizer;	// 24 = 0x18
}

@property(retain, nonatomic) UITapGestureRecognizer *menuRecognizer; // @synthesize menuRecognizer=_menuRecognizer;
@property(nonatomic) _Bool cancelOnExit; // @synthesize cancelOnExit=_cancelOnExit;
@property(retain, nonatomic) TVOSUpdateView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;	// IMP=0x0000000100021c98
- (void)_menuButtonAction:(id)arg1;	// IMP=0x000000010002184c
- (void)osUpdateServiceDidFinishApplyWithData:(id)arg1;	// IMP=0x00000001000216e0
- (void)osUpdateServiceDidEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x00000001000216dc
- (void)osUpdateServiceDidUpdateApplyProgressWithData:(id)arg1;	// IMP=0x00000001000216d8
- (void)osUpdateServiceDidStartApplyWithData:(id)arg1;	// IMP=0x000000010002160c
- (void)osUpdateServiceDidStartRedownloadWithData:(id)arg1;	// IMP=0x0000000100021608
- (void)osUpdateServiceDidFinishDownloadWithData:(id)arg1;	// IMP=0x0000000100021470
- (void)osUpdateServiceDidUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x0000000100021058
- (void)osUpdateServiceDidStartDownloadWithData:(id)arg1;	// IMP=0x0000000100021054
- (void)osUpdateServiceDidFinishCheckWithData:(id)arg1;	// IMP=0x0000000100020ec4
- (void)osUpdateServiceDidStartCheckWithData:(id)arg1;	// IMP=0x0000000100020e10
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100020d30
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100020c00
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000209c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

