//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BBObserverDelegate.h"
#import "FBUIApplicationServiceDelegate.h"
#import "PBSAppDepotProxyProtocol.h"

@class BBObserver, NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface PBAppDepot : NSObject <FBUIApplicationServiceDelegate, BBObserverDelegate, PBSAppDepotProxyProtocol>
{
    // Error parsing type: AB, name: _needsReload
    // Error parsing type: AB, name: _needsNotifyAppStateDidChange
    _Bool _enforceProvisioningOnSystemAppsEnabled;	// 10 = 0xa
    NSMutableDictionary *_internalAppState;	// 16 = 0x10
    NSArray *_internalProvisionedAppIdentifiers;	// 24 = 0x18
    BBObserver *_bbObserver;	// 32 = 0x20
}

+ (_Bool)_checkApplicationIsSystemAppRequiringProvisioning:(id)arg1;	// IMP=0x0000000100054ab8
+ (id)_appStateURL;	// IMP=0x000000010005442c
+ (id)sharedInstance;	// IMP=0x0000000100050e40
+ (void)setupAppDepot;	// IMP=0x0000000100050c40
+ (void)initialize;	// IMP=0x0000000100050bd4
@property(retain, nonatomic) BBObserver *bbObserver; // @synthesize bbObserver=_bbObserver;
@property(nonatomic) _Bool enforceProvisioningOnSystemAppsEnabled; // @synthesize enforceProvisioningOnSystemAppsEnabled=_enforceProvisioningOnSystemAppsEnabled;
@property(copy, nonatomic) NSArray *internalProvisionedAppIdentifiers; // @synthesize internalProvisionedAppIdentifiers=_internalProvisionedAppIdentifiers;
@property(retain, nonatomic) NSMutableDictionary *internalAppState; // @synthesize internalAppState=_internalAppState;
- (void).cxx_destruct;	// IMP=0x0000000100054c7c
- (id)_reversedDictionaryWithDictionary:(id)arg1;	// IMP=0x0000000100054904
- (id)_systemAppBundleIdentifiers;	// IMP=0x0000000100054694
- (void)observer:(id)arg1 noteServerConnectionStateChanged:(_Bool)arg2;	// IMP=0x00000001000542d4
- (void)observer:(id)arg1 updateSectionInfo:(id)arg2;	// IMP=0x0000000100054218
- (void)_updateBadgeEnabledWithInfos:(id)arg1;	// IMP=0x0000000100053e90
- (void)_save;	// IMP=0x0000000100053d60
- (void)_notifyAppStateDidChange;	// IMP=0x0000000100053c48
- (void)_setNeedsNotifyAppStateDidChange;	// IMP=0x0000000100053b74
- (void)_updateAppInfo;	// IMP=0x000000010005327c
- (void)setNeedsReload;	// IMP=0x00000001000531a8
- (void)_appStateDidChange:(id)arg1;	// IMP=0x000000010005319c
- (void)_loadInitialAppState;	// IMP=0x0000000100052e0c
- (void)_removeAppStateForIdentifier:(id)arg1;	// IMP=0x0000000100052d78
- (id)_addAppStateForIdentifier:(id)arg1;	// IMP=0x0000000100052c90
- (id)_appStateForIdentifier:(id)arg1;	// IMP=0x0000000100052c08
- (void)clearUserNotificationsForBundleIdentifier:(id)arg1;	// IMP=0x0000000100052a98
- (void)enqueueUserNotification:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x00000001000528e8
- (void)decrementCacheDeletingForBundleIdentifier:(id)arg1;	// IMP=0x0000000100052788
- (void)incrementCacheDeletingForBundleIdentifier:(id)arg1;	// IMP=0x0000000100052628
- (void)setRecentlyUpdated:(_Bool)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x00000001000524bc
- (void)applicationService:(id)arg1 suspendApplicationWithBundleIdentifier:(id)arg2;	// IMP=0x0000000100052444
- (void)applicationService:(id)arg1 getBadgeValueForBundleIdentifier:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005210c
- (void)applicationService:(id)arg1 setBadgeValue:(id)arg2 forBundleIdentifier:(id)arg3;	// IMP=0x0000000100051f38
- (void)removeAppStateForApplicationProxies:(id)arg1;	// IMP=0x0000000100051cb8
- (void)addAppStateForApplicationProxies:(id)arg1;	// IMP=0x00000001000518a0
@property(readonly, copy) NSArray *provisionedAppIdentifiers;
@property(readonly, copy) NSDictionary *appState;
- (id)_appDepotQueue;	// IMP=0x0000000100051440
- (void)dealloc;	// IMP=0x0000000100051374
- (id)init;	// IMP=0x0000000100050e94

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

