//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, PBAppSwitcherItem, PBAppSwitcherTitleView, PBSnapshotView, UIView;

@interface PBAppSwitcherFocusCollectionViewCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    PBSnapshotView *_snapshotImageView;	// 8 = 0x8
    PBAppSwitcherItem *_appSwitcherItem;	// 16 = 0x10
    PBAppSwitcherTitleView *_titleView;	// 24 = 0x18
    UIView *_itemContentView;	// 32 = 0x20
    UIView *_containerView;	// 40 = 0x28
    double _blurRadius;	// 48 = 0x30
    UIView *_snapshotView;	// 56 = 0x38
    double _hasBlurFilter;	// 64 = 0x40
    struct CGRect _blurRect;	// 72 = 0x48
}

@property(nonatomic) double hasBlurFilter; // @synthesize hasBlurFilter=_hasBlurFilter;
@property(retain, nonatomic) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(readonly, nonatomic) struct CGRect blurRect; // @synthesize blurRect=_blurRect;
@property(readonly, nonatomic) double blurRadius; // @synthesize blurRadius=_blurRadius;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) UIView *itemContentView; // @synthesize itemContentView=_itemContentView;
@property(readonly, nonatomic) PBAppSwitcherTitleView *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) PBAppSwitcherItem *appSwitcherItem; // @synthesize appSwitcherItem=_appSwitcherItem;
@property(readonly, nonatomic) PBSnapshotView *snapshotImageView; // @synthesize snapshotImageView=_snapshotImageView;
- (void).cxx_destruct;	// IMP=0x0000000100061ccc
- (void)setBlurRadius:(double)arg1 rect:(struct CGRect)arg2;	// IMP=0x0000000100061884
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100061708
- (void)setAppSwitcherItem:(id)arg1;	// IMP=0x0000000100061258
- (void)layoutSubviews;	// IMP=0x000000010006116c
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x0000000100060e64
- (void)dealloc;	// IMP=0x0000000100060e10
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100060a68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

