//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, NSLock, NSMutableArray;

@interface PBAppSoftwareUpdateOperation : NSOperation
{
    int __state;	// 24 = 0x18
    int __ordinal;	// 28 = 0x1c
    NSLock *__lock;	// 32 = 0x20
    NSMutableArray *__unfinishedOperations;	// 40 = 0x28
    unsigned int __powerAssertion;	// 48 = 0x30
    id __self;	// 56 = 0x38
    NSArray *_operations;	// 64 = 0x40
}

+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;	// IMP=0x000000010009d110
@property(readonly) NSArray *operations; // @synthesize operations=_operations;
- (void).cxx_destruct;	// IMP=0x000000010009ff40
- (void)__processAppSoftwareUpdateResponse:(id)arg1;	// IMP=0x000000010009f39c
- (void)__computeInstalledSoftwareWithAskToBuyEnabled:(_Bool)arg1;	// IMP=0x000000010009e47c
- (void)__computeFamilyAccountInfo;	// IMP=0x000000010009e268
@property(readonly) double percentComplete;
@property(readonly) _Bool hadFailures;
- (void)resume;	// IMP=0x000000010009db30
- (void)pause;	// IMP=0x000000010009da18
- (void)cancel;	// IMP=0x000000010009d8e0
- (void)__finish;	// IMP=0x000000010009d6c4
- (void)start;	// IMP=0x000000010009d388
- (_Bool)isFinished;	// IMP=0x000000010009d370
- (_Bool)isExecuting;	// IMP=0x000000010009d358
- (_Bool)isAsynchronous;	// IMP=0x000000010009d350
- (id)init;	// IMP=0x000000010009d1e8

@end

