//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LSApplicationProxy, NSString, PBAppSwitcherManager, PBSAppState, UIImage;

@interface PBAppSwitcherItem : NSObject
{
    _Bool _live;	// 8 = 0x8
    _Bool _pendingInsertion;	// 9 = 0x9
    _Bool _pendingDeletion;	// 10 = 0xa
    long long _itemType;	// 16 = 0x10
    LSApplicationProxy *_applicationProxy;	// 24 = 0x18
    NSString *_identifier;	// 32 = 0x20
    NSString *_displayName;	// 40 = 0x28
    UIImage *_iconImage;	// 48 = 0x30
    PBAppSwitcherManager *_manager;	// 56 = 0x38
    PBSAppState *_appState;	// 64 = 0x40
}

@property(nonatomic, getter=isPendingDeletion) _Bool pendingDeletion; // @synthesize pendingDeletion=_pendingDeletion;
@property(nonatomic, getter=isPendingInsertion) _Bool pendingInsertion; // @synthesize pendingInsertion=_pendingInsertion;
@property(copy, nonatomic) PBSAppState *appState; // @synthesize appState=_appState;
@property(readonly, nonatomic) __weak PBAppSwitcherManager *manager; // @synthesize manager=_manager;
@property(readonly, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) LSApplicationProxy *applicationProxy; // @synthesize applicationProxy=_applicationProxy;
@property(readonly, nonatomic, getter=isLive) _Bool live; // @synthesize live=_live;
@property(readonly, nonatomic) long long itemType; // @synthesize itemType=_itemType;
- (void).cxx_destruct;	// IMP=0x00000001000ac3e4
- (id)_localizedAppName;	// IMP=0x00000001000ac148
- (void)_updateIconImage;	// IMP=0x00000001000ac030
- (void)_updateDisplayName;	// IMP=0x00000001000abebc
- (void)_updateForProgressChange;	// IMP=0x00000001000abeb0
- (id)description;	// IMP=0x00000001000abe6c
- (id)initWithType:(long long)arg1 proxy:(id)arg2 appState:(id)arg3 manager:(id)arg4 live:(_Bool)arg5;	// IMP=0x00000001000abb20

@end

