//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PBBundleLoader : NSObject
{
    NSMutableDictionary *_loadedPluginsByBundleID;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010002435c
- (void).cxx_destruct;	// IMP=0x0000000100024ab0
- (id)pluginControllerForBundleIdentifier:(id)arg1;	// IMP=0x0000000100024a98
- (void)_loadBundlesFromDirectory:(id)arg1;	// IMP=0x0000000100024470
- (id)init;	// IMP=0x00000001000243f0
- (void)loadPlugins;	// IMP=0x00000001000243dc

@end

