//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIViewControllerTransitioningDelegate.h"

@class NSString, PBFeatureInfoViewController, TVTextAlertController, UIView;

@interface PBSiriOptInOfferViewController : UIViewController <UIViewControllerTransitioningDelegate>
{
    _Bool _configuredForDictationOnly;	// 8 = 0x8
    _Bool _termsVisible;	// 9 = 0x9
    CDUnknownBlockType _dismissalCompletion;	// 16 = 0x10
    UIView *_dialogContainerView;	// 24 = 0x18
    PBFeatureInfoViewController *_featureInfoViewController;	// 32 = 0x20
    TVTextAlertController *_termsViewController;	// 40 = 0x28
}

@property(readonly, nonatomic) TVTextAlertController *termsViewController; // @synthesize termsViewController=_termsViewController;
@property(readonly, nonatomic) PBFeatureInfoViewController *featureInfoViewController; // @synthesize featureInfoViewController=_featureInfoViewController;
@property(readonly, nonatomic) UIView *dialogContainerView; // @synthesize dialogContainerView=_dialogContainerView;
@property(nonatomic) _Bool termsVisible; // @synthesize termsVisible=_termsVisible;
@property(copy, nonatomic) CDUnknownBlockType dismissalCompletion; // @synthesize dismissalCompletion=_dismissalCompletion;
@property(nonatomic, getter=isConfiguredForDictationOnly) _Bool configuredForDictationOnly; // @synthesize configuredForDictationOnly=_configuredForDictationOnly;
- (void).cxx_destruct;	// IMP=0x000000010007293c
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;	// IMP=0x00000001000725bc
- (id)animationControllerForDismissedController:(id)arg1;	// IMP=0x0000000100072588
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;	// IMP=0x0000000100072554
- (void)_readAboutText:(id)arg1;	// IMP=0x0000000100072544
- (void)_dismissViewControllerWithValue:(_Bool)arg1;	// IMP=0x0000000100072428
- (void)_optOut:(id)arg1;	// IMP=0x0000000100072418
- (void)_optIn:(id)arg1;	// IMP=0x0000000100072358
- (void)_handleHomeButton:(id)arg1;	// IMP=0x0000000100072348
- (void)_handleMenuButton:(id)arg1;	// IMP=0x0000000100072300
- (id)preferredFocusEnvironments;	// IMP=0x0000000100072294
- (void)viewDidLoad;	// IMP=0x0000000100071b54
- (void)dealloc;	// IMP=0x0000000100071ac8
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100071a28

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

