//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSystemServiceInterface.h"

@class NSString, NSXPCConnection, PBAirPlayService, PBBulletinService, PBDiagnosticLogsService, PBOSUpdateService, PBRestrictionService, PBUserPresentationService;

@interface PBSystemServiceConnection : NSObject <PBSystemServiceInterface>
{
    PBAirPlayService *_airPlayService;	// 8 = 0x8
    PBBulletinService *_bulletinService;	// 16 = 0x10
    PBDiagnosticLogsService *_diagnosticLogsService;	// 24 = 0x18
    PBOSUpdateService *_osUpdateService;	// 32 = 0x20
    PBRestrictionService *_restrictionService;	// 40 = 0x28
    PBUserPresentationService *_userPresentationService;	// 48 = 0x30
    NSXPCConnection *_remoteConnection;	// 56 = 0x38
    NSString *_clientBundleIdentifier;	// 64 = 0x40
    id <PBSystemServiceNowPlayingDelegate> _nowPlayingPresentationDelegate;	// 72 = 0x48
}

+ (id)systemServiceConnectionForProcessIdentifier:(int)arg1;	// IMP=0x000000010008824c
+ (void)_registerConnection:(id)arg1;	// IMP=0x00000001000880b4
+ (id)_activeConnectionsByProcessIdentifier;	// IMP=0x0000000100088034
@property(retain, nonatomic) id <PBSystemServiceNowPlayingDelegate> nowPlayingPresentationDelegate; // @synthesize nowPlayingPresentationDelegate=_nowPlayingPresentationDelegate;
@property(readonly, copy, nonatomic) NSString *clientBundleIdentifier; // @synthesize clientBundleIdentifier=_clientBundleIdentifier;
@property(readonly, nonatomic) NSXPCConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x000000010008eebc
- (id)_clientBundleIdentifierFromConnection;	// IMP=0x000000010008ede0
- (_Bool)sendMessagePresentNowPlayingUI;	// IMP=0x000000010008ed84
- (void)prepareForKioskAppTransitionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010008ecf4
- (void)sharedAppStateDidChange;	// IMP=0x000000010008ec90
- (void)startIdleScreenAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 delay:(double)arg4;	// IMP=0x000000010008ebe0
- (void)startKioskAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 delay:(double)arg4;	// IMP=0x000000010008eb30
- (void)kioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x000000010008eaa0
- (void)kioskAppHandleHomeButtonWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010008ea10
- (void)listen;	// IMP=0x000000010008ea0c
- (void)getUserPresentationServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e7d4
- (void)getMediaRemoteServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e60c
- (void)getRestrictionServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e534
- (void)getAirPlayServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e2fc
- (void)getOSUpdateServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e0c4
- (void)getDiagnosticLogsServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008de8c
- (void)getBulletinServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008dc54
- (void)endpointForProviderType:(id)arg1 withIdentifier:(id)arg2 responseBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010008dba4
- (void)registerServiceProviderEndpoint:(id)arg1 forProviderType:(id)arg2;	// IMP=0x000000010008dae0
- (void)getStoreFrontCountryCodeWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008da0c
- (void)cancelScheduledAppActivation;	// IMP=0x000000010008d928
- (void)activateAppIfPlayingMusicAfterIdleTime:(double)arg1 openURL:(id)arg2;	// IMP=0x000000010008d7a0
- (void)performBluetoothRemoteFirmwareCheck;	// IMP=0x000000010008d614
- (void)pairAppleRemote:(_Bool)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010008d3b8
- (void)fetchPairedAppleRemoteStateWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008d198
- (void)fetchEnforceProvisioningOnSystemAppsEnabledWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008cfd8
- (void)fetchApplicationIdentifiersByBundleIdentifierMappingWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008ce04
- (void)fetchDisabledAdamIDsWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008cbe8
- (void)fetchProvisionAppIdentifiersWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008ca14
- (void)fetchSharedAppStateWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008c840
- (void)launchKioskApp;	// IMP=0x000000010008c690
- (void)stopSiriListening;	// IMP=0x000000010008c41c
- (void)startSiriListening;	// IMP=0x000000010008c1a8
- (void)activateSiri;	// IMP=0x000000010008bf34
- (void)setEffectiveUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010008bcf4
- (void)effectiveUserInterfaceStyleWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008ba14
- (void)sendEventData:(id)arg1;	// IMP=0x000000010008b768
- (void)sendMenuButtonEvent;	// IMP=0x000000010008b53c
- (void)performScreenActionWithName:(id)arg1 forItemIdentifier:(id)arg2 parameters:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x000000010008afd0
- (void)setNextAssistantRecognitionStrings:(id)arg1;	// IMP=0x000000010008ada4
- (void)setNextVoiceRecognitionAudioInputPaths:(id)arg1;	// IMP=0x000000010008ab78
- (void)topActiveOrActivatingApplicationIdentifierWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008a94c
- (void)recentApplicationBundleIdentifiersWithReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010008a77c
- (void)purgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x000000010008a5e8
- (void)dismissCRDInstructionWindow;	// IMP=0x000000010008a27c
- (void)presentCRDInstructionWindow;	// IMP=0x0000000100089f10
- (void)launchCRDApp;	// IMP=0x0000000100089d5c
- (void)setAirPlayActive:(_Bool)arg1;	// IMP=0x0000000100089b70
- (void)deactivateScreenSaver;	// IMP=0x0000000100089944
- (void)activateScreenSaverWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100089674
- (void)activateScreenSaver;	// IMP=0x0000000100089664
- (void)sleepTimeoutWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100089408
- (void)setSleepTimeout:(double)arg1;	// IMP=0x00000001000891c0
- (void)reboot;	// IMP=0x0000000100088f94
- (void)relaunch;	// IMP=0x0000000100088d68
- (void)relaunchBackboardd;	// IMP=0x0000000100088bb0
- (void)fetchDeviceIsAsleepWithResult:(CDUnknownBlockType)arg1;	// IMP=0x0000000100088a10
- (void)wakeSystemForReason:(unsigned long long)arg1;	// IMP=0x00000001000887d4
- (void)sleepSystemForReason:(unsigned long long)arg1;	// IMP=0x0000000100088598
- (void)deactivateApplication;	// IMP=0x0000000100088544
- (void)registerNowPlayingDelegate:(id)arg1;	// IMP=0x0000000100088538
- (id)osUpdateService;	// IMP=0x0000000100088528
- (void)invalidate;	// IMP=0x0000000100088354
- (void)resume;	// IMP=0x000000010008833c
- (void)dealloc;	// IMP=0x0000000100087f88
- (id)init;	// IMP=0x0000000100087f70
- (id)initWithConnection:(id)arg1;	// IMP=0x000000010008775c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool hiliteModeActive;
@property(readonly, nonatomic) _Bool screenSaverActive;
@property(readonly) Class superclass;

@end

