//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBNavigationControllerDelegate.h"

@class FBDisplayLayoutElement, FBUIApplicationSceneDeactivationAssertion, NSMutableArray, NSMutableSet, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_source>, NSString, PBOSUpdateWindow, PBRemoteBulletinViewController, PBScreenSaverTransitionViewController, PBWindow, UIView, UIViewController, _PBWindowManagerAppTransitionHelper;

@interface PBWindowManager : NSObject <PBNavigationControllerDelegate>
{
    _Bool _hasScheduledPresentDialog;	// 8 = 0x8
    _Bool _hasScheduledPresentBulletin;	// 9 = 0x9
    _Bool _siriIsFullscreen;	// 10 = 0xa
    _Bool _shouldAnimateCRDInstructionsHUD;	// 11 = 0xb
    _Bool _useSnapshotForSiri;	// 12 = 0xc
    PBRemoteBulletinViewController *_presentedBulletinViewController;	// 16 = 0x10
    PBOSUpdateWindow *_softwareUpdateWindow;	// 24 = 0x18
    PBWindow *_criticalAlertWindow;	// 32 = 0x20
    PBWindow *_airPlayWindow;	// 40 = 0x28
    PBWindow *_bulletinWindow;	// 48 = 0x30
    PBWindow *_playbackLaunchShroudWindow;	// 56 = 0x38
    PBWindow *_dialogWindow;	// 64 = 0x40
    PBWindow *_siriWindow;	// 72 = 0x48
    PBWindow *_nowPlayingWindow;	// 80 = 0x50
    PBWindow *_restrictionPINWindow;	// 88 = 0x58
    PBWindow *_screenSaverWindow;	// 96 = 0x60
    PBWindow *_appSwitcherWindow;	// 104 = 0x68
    PBWindow *_appTransitionWindow;	// 112 = 0x70
    PBWindow *_wallpaperWindow;	// 120 = 0x78
    PBWindow *_radioAdWindow;	// 128 = 0x80
    PBWindow *_blackScreenRecoveryWindow;	// 136 = 0x88
    PBWindow *_crdLoadingWindow;	// 144 = 0x90
    PBWindow *_crdInstructionsWindow;	// 152 = 0x98
    NSMutableSet *_dialogHiddenClients;	// 160 = 0xa0
    PBScreenSaverTransitionViewController *_screenSaverTransitionViewController;	// 168 = 0xa8
    NSObject<OS_dispatch_source> *_bulletinDismissalTimer;	// 176 = 0xb0
    NSMutableArray *_pendingDialogRequests;	// 184 = 0xb8
    NSMutableArray *_pendingBulletinRequests;	// 192 = 0xc0
    NSMutableArray *_pendingTransitionTransactions;	// 200 = 0xc8
    FBUIApplicationSceneDeactivationAssertion *_airPlayAssertion;	// 208 = 0xd0
    FBUIApplicationSceneDeactivationAssertion *_appSwitcherAssertion;	// 216 = 0xd8
    FBUIApplicationSceneDeactivationAssertion *_dialogAssertion;	// 224 = 0xe0
    FBUIApplicationSceneDeactivationAssertion *_screenSaverAssertion;	// 232 = 0xe8
    FBUIApplicationSceneDeactivationAssertion *_siriAssertion;	// 240 = 0xf0
    FBUIApplicationSceneDeactivationAssertion *_siriFullscreenAssertion;	// 248 = 0xf8
    FBDisplayLayoutElement *_focusedAppDisplayLayoutElement;	// 256 = 0x100
    _PBWindowManagerAppTransitionHelper *_appTransitionHelper;	// 264 = 0x108
    unsigned long long _crdInstructionWindowIdentifier;	// 272 = 0x110
    NSObject<OS_dispatch_group> *_crdInstructionWindowGroup;	// 280 = 0x118
    UIViewController *_siriViewController;	// 288 = 0x120
    UIView *_siriSnapshotView;	// 296 = 0x128
}

+ (void)_registerWindowNotificationHandlers;	// IMP=0x00000001000351dc
+ (id)_rootNavigationViewControllerForWindow:(id)arg1;	// IMP=0x000000010003515c
+ (id)sharedInstance;	// IMP=0x000000010002ab24
+ (void)initialize;	// IMP=0x000000010002aab8
@property(readonly, nonatomic) UIView *siriSnapshotView; // @synthesize siriSnapshotView=_siriSnapshotView;
@property(readonly, nonatomic) UIViewController *siriViewController; // @synthesize siriViewController=_siriViewController;
@property(readonly, nonatomic) _Bool useSnapshotForSiri; // @synthesize useSnapshotForSiri=_useSnapshotForSiri;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *crdInstructionWindowGroup; // @synthesize crdInstructionWindowGroup=_crdInstructionWindowGroup;
@property(nonatomic) unsigned long long crdInstructionWindowIdentifier; // @synthesize crdInstructionWindowIdentifier=_crdInstructionWindowIdentifier;
@property(retain, nonatomic) _PBWindowManagerAppTransitionHelper *appTransitionHelper; // @synthesize appTransitionHelper=_appTransitionHelper;
@property(retain, nonatomic) FBDisplayLayoutElement *focusedAppDisplayLayoutElement; // @synthesize focusedAppDisplayLayoutElement=_focusedAppDisplayLayoutElement;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *siriFullscreenAssertion; // @synthesize siriFullscreenAssertion=_siriFullscreenAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *siriAssertion; // @synthesize siriAssertion=_siriAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *screenSaverAssertion; // @synthesize screenSaverAssertion=_screenSaverAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *dialogAssertion; // @synthesize dialogAssertion=_dialogAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *appSwitcherAssertion; // @synthesize appSwitcherAssertion=_appSwitcherAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *airPlayAssertion; // @synthesize airPlayAssertion=_airPlayAssertion;
@property(readonly, nonatomic) NSMutableArray *pendingTransitionTransactions; // @synthesize pendingTransitionTransactions=_pendingTransitionTransactions;
@property(readonly, nonatomic) NSMutableArray *pendingBulletinRequests; // @synthesize pendingBulletinRequests=_pendingBulletinRequests;
@property(readonly, nonatomic) NSMutableArray *pendingDialogRequests; // @synthesize pendingDialogRequests=_pendingDialogRequests;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *bulletinDismissalTimer; // @synthesize bulletinDismissalTimer=_bulletinDismissalTimer;
@property(readonly, nonatomic) __weak PBScreenSaverTransitionViewController *screenSaverTransitionViewController; // @synthesize screenSaverTransitionViewController=_screenSaverTransitionViewController;
@property(readonly, copy, nonatomic) NSMutableSet *dialogHiddenClients; // @synthesize dialogHiddenClients=_dialogHiddenClients;
@property(retain, nonatomic) PBWindow *crdInstructionsWindow; // @synthesize crdInstructionsWindow=_crdInstructionsWindow;
@property(retain, nonatomic) PBWindow *crdLoadingWindow; // @synthesize crdLoadingWindow=_crdLoadingWindow;
@property(retain, nonatomic) PBWindow *blackScreenRecoveryWindow; // @synthesize blackScreenRecoveryWindow=_blackScreenRecoveryWindow;
@property(retain, nonatomic) PBWindow *radioAdWindow; // @synthesize radioAdWindow=_radioAdWindow;
@property(retain, nonatomic) PBWindow *wallpaperWindow; // @synthesize wallpaperWindow=_wallpaperWindow;
@property(retain, nonatomic) PBWindow *appTransitionWindow; // @synthesize appTransitionWindow=_appTransitionWindow;
@property(retain, nonatomic) PBWindow *appSwitcherWindow; // @synthesize appSwitcherWindow=_appSwitcherWindow;
@property(retain, nonatomic) PBWindow *screenSaverWindow; // @synthesize screenSaverWindow=_screenSaverWindow;
@property(retain, nonatomic) PBWindow *restrictionPINWindow; // @synthesize restrictionPINWindow=_restrictionPINWindow;
@property(retain, nonatomic) PBWindow *nowPlayingWindow; // @synthesize nowPlayingWindow=_nowPlayingWindow;
@property(retain, nonatomic) PBWindow *siriWindow; // @synthesize siriWindow=_siriWindow;
@property(retain, nonatomic) PBWindow *dialogWindow; // @synthesize dialogWindow=_dialogWindow;
@property(retain, nonatomic) PBWindow *playbackLaunchShroudWindow; // @synthesize playbackLaunchShroudWindow=_playbackLaunchShroudWindow;
@property(retain, nonatomic) PBWindow *bulletinWindow; // @synthesize bulletinWindow=_bulletinWindow;
@property(retain, nonatomic) PBWindow *airPlayWindow; // @synthesize airPlayWindow=_airPlayWindow;
@property(retain, nonatomic) PBWindow *criticalAlertWindow; // @synthesize criticalAlertWindow=_criticalAlertWindow;
@property(retain, nonatomic) PBOSUpdateWindow *softwareUpdateWindow; // @synthesize softwareUpdateWindow=_softwareUpdateWindow;
@property(nonatomic) _Bool shouldAnimateCRDInstructionsHUD; // @synthesize shouldAnimateCRDInstructionsHUD=_shouldAnimateCRDInstructionsHUD;
@property(nonatomic) _Bool siriIsFullscreen; // @synthesize siriIsFullscreen=_siriIsFullscreen;
@property(retain, nonatomic) PBRemoteBulletinViewController *presentedBulletinViewController; // @synthesize presentedBulletinViewController=_presentedBulletinViewController;
- (void).cxx_destruct;	// IMP=0x0000000100035d80
- (void)_updateLayoutElementsWithFocusedProcess:(id)arg1;	// IMP=0x0000000100034fac
- (void)_updateKeyWindow;	// IMP=0x0000000100034e80
- (id)_highestPriorityWindowBelow:(id)arg1 eventsOnly:(_Bool)arg2;	// IMP=0x0000000100034604
- (id)_highestPriorityWindow;	// IMP=0x0000000100033e48
- (id)_lazyCRDInstructionsWindow;	// IMP=0x0000000100033c24
- (id)_lazyCRDLoadingWindow;	// IMP=0x0000000100033a00
- (id)_lazyWallpaperWindow;	// IMP=0x0000000100033904
- (id)_lazyAppTransitionWindow;	// IMP=0x00000001000337ec
- (id)_lazyAppSwitcherWindow;	// IMP=0x0000000100033644
- (id)_lazyBulletinWindow;	// IMP=0x0000000100033548
- (id)_lazyDialogWindowForRequest:(id)arg1;	// IMP=0x0000000100033384
- (id)_lazySiriWindow;	// IMP=0x00000001000331c0
- (id)_lazyBlackScreenRecoveryWindow;	// IMP=0x0000000100032f4c
- (id)_lazyRadioAdWindow;	// IMP=0x0000000100032ce0
- (id)_lazyRestrictionPINWindow;	// IMP=0x0000000100032a44
- (id)_lazyNowPlayingWindow;	// IMP=0x00000001000327c4
- (id)_lazyAirPlayWindow;	// IMP=0x000000010003259c
- (id)_lazyScreenSaverWindow;	// IMP=0x00000001000323b0
- (id)_lazyPlaybackLaunchShroudWindow;	// IMP=0x00000001000321f4
- (void)_dismissCRDInstructionsWindow:(id)arg1;	// IMP=0x000000010003215c
- (void)dismissCRDInstructionsWindow;	// IMP=0x0000000100032054
- (void)presentCRDInstructionsWindow;	// IMP=0x0000000100031b24
@property(readonly, nonatomic) _Bool presentingCRDInstructionsWindow;
- (void)_incrementCRDInstructionWindowIdentifier;	// IMP=0x0000000100031a84
- (void)_dismissCRDLoadingWindow:(id)arg1;	// IMP=0x00000001000319ec
- (_Bool)dismissCRDLoadingWindow;	// IMP=0x0000000100031934
- (void)presentCRDLoadingWindow;	// IMP=0x0000000100031664
@property(readonly, nonatomic) _Bool presentingCRDLoadingWindow;
- (void)_dismissAppTransitionWindow:(id)arg1;	// IMP=0x0000000100031538
- (void)_dismissWindowsForAppLaunch:(id)arg1;	// IMP=0x00000001000313ac
- (_Bool)cancelCurrentAppTransition;	// IMP=0x0000000100031314
- (void)_cancelPendingTransitionTransactions;	// IMP=0x00000001000311ac
- (void)_beginPendingTransitionTransaction;	// IMP=0x0000000100030d84
- (void)_beginAppTransitionTransaction:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100030678
- (void)beginAppTransitionWithTransaction:(id)arg1;	// IMP=0x0000000100030300
@property(readonly, nonatomic) _Bool presentingAppTransition;
- (void)_dismissAppSwitcherWindow;	// IMP=0x00000001000301e4
- (_Bool)_shouldActivateAppSwitcher;	// IMP=0x0000000100030010
- (_Bool)dismissAppSwitcher;	// IMP=0x000000010002ff58
- (_Bool)presentAppSwitcher;	// IMP=0x000000010002fe84
@property(readonly, nonatomic) _Bool presentingAppSwitcher;
- (void)_dismissAirPlayWindow;	// IMP=0x000000010002fd6c
- (_Bool)dismissAirPlayWindow;	// IMP=0x000000010002fcb8
- (void)presentAirPlayViewController:(id)arg1;	// IMP=0x000000010002fb14
- (_Bool)presentingAirPlay;	// IMP=0x000000010002faac
- (void)dismissThermalWarningWindow;	// IMP=0x000000010002fa38
- (void)presentThermalWarningWindow;	// IMP=0x000000010002f964
- (void)dismissSoftwareUpdateWindow;	// IMP=0x000000010002f8f0
- (void)presentSoftwareUpdateWindow;	// IMP=0x000000010002f7ec
- (void)_cancelBulletinTimer;	// IMP=0x000000010002f7a8
- (void)_presentNextBulletin;	// IMP=0x000000010002f2d8
- (void)_schedulePresentBulletin;	// IMP=0x000000010002f1c0
- (void)_enqueueBulletinPresentationRequest:(id)arg1;	// IMP=0x000000010002f114
- (_Bool)dismissBulletinWindow;	// IMP=0x000000010002f02c
- (_Bool)dismissBulletinViewController:(id)arg1;	// IMP=0x000000010002ee7c
- (void)updateBulletinViewControllerTimeout:(id)arg1 timeoutInSeconds:(double)arg2;	// IMP=0x000000010002ed98
- (void)presentBulletinViewController:(id)arg1 withTimeoutInSeconds:(double)arg2;	// IMP=0x000000010002ed28
- (void)navigationController:(id)arg1 didDismissViewController:(id)arg2;	// IMP=0x000000010002ed18
- (void)_executePresentationRequest:(id)arg1;	// IMP=0x000000010002e93c
- (void)_presentNextDialog;	// IMP=0x000000010002e4c0
- (void)_schedulePresentDialog;	// IMP=0x000000010002e3ec
- (void)_enqueueDialogPresentationRequest:(id)arg1;	// IMP=0x000000010002e350
- (_Bool)_dismissDialogWindow;	// IMP=0x000000010002e26c
- (void)_suspendDialogWindow;	// IMP=0x000000010002e12c
- (_Bool)_retirePresentationRequestForViewController:(id)arg1;	// IMP=0x000000010002df7c
- (void)dismissDialogViewController:(id)arg1;	// IMP=0x000000010002dec4
- (_Bool)hideDialogWindowForClient:(id)arg1;	// IMP=0x000000010002dc48
- (_Bool)_unhideDialogWindowForClients:(id)arg1;	// IMP=0x000000010002d86c
- (_Bool)unhideDialogWindowForClient:(id)arg1;	// IMP=0x000000010002d800
- (void)presentDialogViewController:(id)arg1 options:(id)arg2;	// IMP=0x000000010002d684
- (void)presentDialogViewController:(id)arg1;	// IMP=0x000000010002d674
@property(readonly, nonatomic) _Bool presentingDialogWindow;
- (void)setUseSnapshotForSiri:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010002d024
- (_Bool)dismissSiriWindow;	// IMP=0x000000010002ce68
- (_Bool)hideSiriWindow;	// IMP=0x000000010002cd1c
- (void)_unhideSiriWindow;	// IMP=0x000000010002cc14
- (_Bool)_willHideSiriWindow;	// IMP=0x000000010002cb4c
- (void)presentSiriViewController:(id)arg1;	// IMP=0x000000010002c978
@property(readonly, nonatomic) _Bool presentingSiriSession;
- (void)_dismissBlackScreenRecoveryWindow:(id)arg1;	// IMP=0x000000010002c878
- (_Bool)dismissBlackScreenRecoveryWindow;	// IMP=0x000000010002c7c0
- (_Bool)presentBlackScreenRecoveryViewController;	// IMP=0x000000010002c61c
- (void)_dismissRadioAdWindow:(id)arg1;	// IMP=0x000000010002c584
- (_Bool)dismissRadioAdWindow;	// IMP=0x000000010002c4cc
- (_Bool)presentRadioAdViewController:(id)arg1;	// IMP=0x000000010002c418
- (void)_dismissRestrictionPINWindow:(id)arg1;	// IMP=0x000000010002c34c
- (_Bool)dismissRestrictionPINWindow;	// IMP=0x000000010002c294
- (void)presentRestrictionPINWindow:(CDUnknownBlockType)arg1;	// IMP=0x000000010002be7c
@property(readonly, nonatomic) _Bool presentingPINRequest;
- (void)_dismissNowPlayingWindow:(id)arg1;	// IMP=0x000000010002bc88
- (_Bool)dismissNowPlayingWindow;	// IMP=0x000000010002bbd0
- (_Bool)presentNowPlayingViewController:(id)arg1;	// IMP=0x000000010002bae0
@property(readonly, nonatomic) _Bool presentingNowPlaying;
- (_Bool)isScreenSaverWindowKey;	// IMP=0x000000010002ba2c
- (void)_destroyScreenSaverWindow:(id)arg1;	// IMP=0x000000010002b968
- (void)dismissScreenSaverWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002b5e8
- (void)presentScreenSaverWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002b220
- (_Bool)_dialogRequestIsRemote:(id)arg1;	// IMP=0x000000010002b1b4
- (_Bool)_presentedDialogIsRemote;	// IMP=0x000000010002b134
- (_Bool)shouldForwardSystemAppEvent;	// IMP=0x000000010002adac
- (id)init;	// IMP=0x000000010002abf8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

