//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (SetupUtilities)
- (id)_buddy_stringForKey:(id)arg1;	// IMP=0x000000010000492c
- (id)_buddy_arrayForKey:(id)arg1;	// IMP=0x00000001000048b0
- (id)_buddy_dictionaryForKey:(id)arg1;	// IMP=0x0000000100004834
@end

