//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface SVSError : NSError
{
}

+ (id)errorWithCode:(long long)arg1;	// IMP=0x00000001000519c0
+ (id)errorWithCode:(long long)arg1 localizedFailureReason:(id)arg2;	// IMP=0x0000000100051954
+ (id)errorWithCode:(long long)arg1 userInfo:(id)arg2;	// IMP=0x00000001000518e8
- (id)initWithCode:(long long)arg1;	// IMP=0x0000000100051acc
- (id)initWithCode:(long long)arg1 localizedFailureReason:(id)arg2;	// IMP=0x00000001000519f4
- (id)initWithCode:(long long)arg1 userInfo:(id)arg2;	// IMP=0x00000001000519d0

@end

