//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface SVSPagingScrollView : UIScrollView
{
}

- (void)scrollToSubview:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100029280
- (void)layoutSubviews;	// IMP=0x0000000100029078
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100028ff4

@end

