//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface SVSStarkConfirmationSnippetView : UIView
{
    id <SVSStarkConfirmationSnippetViewDelegate> _delegate;	// 8 = 0x8
    NSArray *_confirmationButtons;	// 16 = 0x10
    double _confirmationButtonYOrigin;	// 24 = 0x18
}

@property(nonatomic, getter=_confirmationButtonYOrigin) double confirmationButtonYOrigin; // @synthesize confirmationButtonYOrigin=_confirmationButtonYOrigin;
@property(readonly, nonatomic) NSArray *confirmationButtons; // @synthesize confirmationButtons=_confirmationButtons;
@property(nonatomic) __weak id <SVSStarkConfirmationSnippetViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100052bdc
- (id)preferredFocusEnvironments;	// IMP=0x0000000100052ab0
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000100052918
- (void)confirmationButton:(id)arg1 tappedWithHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010005284c
- (void)layoutSubviews;	// IMP=0x0000000100052684
- (double)_confirmationButtonYOriginInBounds:(struct CGRect)arg1;	// IMP=0x000000010005258c
- (void)enableReadAgainButton;	// IMP=0x000000010005244c
- (id)initWithFrame:(struct CGRect)arg1 confirmationButtons:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000100052018

@end

