//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFQueueDelegate.h"
#import "NSFastEnumeration.h"
#import "SVSTranscriptItemGroupDelegate.h"

@class AFQueue, NSMutableArray, NSMutableDictionary, NSString;

@interface SVSTranscript : NSObject <AFQueueDelegate, SVSTranscriptItemGroupDelegate, NSFastEnumeration>
{
    id <SVSTranscriptDataSource> _dataSource;	// 8 = 0x8
    id <SVSTranscriptDelegate> _delegate;	// 16 = 0x10
    NSMutableArray *_allTranscriptItems;	// 24 = 0x18
    NSMutableArray *_exposedTranscriptItems;	// 32 = 0x20
    NSMutableArray *_waitingTranscriptItems;	// 40 = 0x28
    NSMutableDictionary *_exposedIdToWaitingIdMap;	// 48 = 0x30
    NSMutableDictionary *_waitingIdToExposedIdMap;	// 56 = 0x38
    AFQueue *_loadingTranscriptItemGroupQueue;	// 64 = 0x40
    long long _discardedItemCount;	// 72 = 0x48
}

@property(readonly, nonatomic) long long discardedItemCount; // @synthesize discardedItemCount=_discardedItemCount;
@property(readonly, nonatomic, getter=_loadingTranscriptItemGroupQueue) AFQueue *loadingTranscriptItemGroupQueue; // @synthesize loadingTranscriptItemGroupQueue=_loadingTranscriptItemGroupQueue;
@property(retain, nonatomic) NSMutableDictionary *waitingIdToExposedIdMap; // @synthesize waitingIdToExposedIdMap=_waitingIdToExposedIdMap;
@property(retain, nonatomic) NSMutableDictionary *exposedIdToWaitingIdMap; // @synthesize exposedIdToWaitingIdMap=_exposedIdToWaitingIdMap;
@property(retain, nonatomic) NSMutableArray *waitingTranscriptItems; // @synthesize waitingTranscriptItems=_waitingTranscriptItems;
@property(readonly, nonatomic, getter=_exposedTranscriptItems) NSMutableArray *exposedTranscriptItems; // @synthesize exposedTranscriptItems=_exposedTranscriptItems;
@property(readonly, nonatomic, getter=_allTranscriptItems) NSMutableArray *allTranscriptItems; // @synthesize allTranscriptItems=_allTranscriptItems;
@property(nonatomic) __weak id <SVSTranscriptDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SVSTranscriptDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x000000010001bfcc
- (_Bool)_transcriptHasProvisionalItems;	// IMP=0x000000010001bc8c
- (id)_aceObjectForItemAtIndex:(long long)arg1;	// IMP=0x000000010001bc20
- (id)_transcriptItemsForDataSourceItemsAtIndexes:(id)arg1;	// IMP=0x000000010001bb9c
- (id)_transcriptItemForDataSourceItemAtIndex:(long long)arg1;	// IMP=0x000000010001bb40
- (long long)conversationIndexForTranscriptLevelModelItemAtIndex:(long long)arg1;	// IMP=0x000000010001ba08
- (unsigned long long)_waitingIndexOfTranscriptItemWithAceObjectAceId:(id)arg1;	// IMP=0x000000010001b830
- (unsigned long long)_conversationIndexOfTranscriptItemWithAceObjectAceId:(id)arg1;	// IMP=0x000000010001b638
- (unsigned long long)_conversationIndexForTranscriptItem:(id)arg1;	// IMP=0x000000010001b5bc
- (id)conversationIndexesForTranscriptLevelModelItemsAtIndexes:(id)arg1;	// IMP=0x000000010001b304
- (long long)_conversationIndexForWaitingTranscriptItem:(id)arg1;	// IMP=0x000000010001b230
- (void)_clearViewControllerDelegateForTranscriptItem:(id)arg1;	// IMP=0x000000010001b184
- (void)_notifyThatViewControllerWillBeRemoved:(id)arg1;	// IMP=0x000000010001b0d0
- (void)clearTranscriptItemViewControllerDelegates;	// IMP=0x000000010001afac
- (id)transcriptItemForViewController:(id)arg1;	// IMP=0x000000010001ada8
- (id)_createTranscriptItemForAceObject:(id)arg1 itemIndex:(long long)arg2;	// IMP=0x000000010001ac74
- (id)_createErrorSnippetViewControllerWithAceObject:(id)arg1 itemIndex:(long long)arg2;	// IMP=0x000000010001aba0
- (void)_configureViewController:(id)arg1 withAceObject:(id)arg2 itemIndex:(long long)arg3;	// IMP=0x000000010001a8f8
- (void)enumerateTranscriptItemsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010001a8e0
- (void)enumerateTranscriptItemsWithOptions:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a86c
- (unsigned long long)_indexOfTranscriptItemWithAceObjectAceId:(id)arg1;	// IMP=0x000000010001a674
- (unsigned long long)indexOfTranscriptItem:(id)arg1;	// IMP=0x000000010001a5f8
- (id)lastItem;	// IMP=0x000000010001a5a4
- (id)transcriptItemForConversationItemWithIdentifier:(id)arg1;	// IMP=0x000000010001a370
- (id)transcriptItemsAtIndexes:(id)arg1;	// IMP=0x000000010001a2ec
- (id)transcriptItemAtIndex:(long long)arg1;	// IMP=0x000000010001a228
@property(readonly, nonatomic) long long transcriptItemCount;
- (id)conversationItemIdentifierForViewController:(id)arg1;	// IMP=0x0000000100019f90
- (void)transcriptItemDidBecomeReadyToAppear:(id)arg1;	// IMP=0x0000000100019f84
- (void)_processLoadingTranscriptItemGroupQueue;	// IMP=0x0000000100019024
- (void)setErrorViewControllerForTranscriptItem:(id)arg1;	// IMP=0x0000000100018f70
- (void)presentationStateDidChangeForItemsAtIndexes:(id)arg1;	// IMP=0x0000000100018d80
- (void)removeItemsWithIdentifiers:(id)arg1 atIndexes:(id)arg2;	// IMP=0x00000001000184f0
- (void)reloadItemsAtIndexes:(id)arg1;	// IMP=0x0000000100017b80
- (void)reloadViewControllerAtIndex:(long long)arg1;	// IMP=0x0000000100017974
- (void)unloadViewControllerAtIndex:(long long)arg1;	// IMP=0x0000000100017904
- (void)insertItemsAtIndexes:(id)arg1;	// IMP=0x00000001000171a0
- (void)reloadData;	// IMP=0x0000000100016f48
- (void)transcriptItemGroupPresentationEligibilityDidChange:(id)arg1;	// IMP=0x0000000100016f00
- (void)queue:(id)arg1 didEnqueueObjects:(id)arg2;	// IMP=0x0000000100016ef4
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;	// IMP=0x0000000100016e88
- (id)init;	// IMP=0x0000000100016cec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

