//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SVSTranscriptStackView : UIView
{
    UIView *_contentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003c070
- (void)layoutSubviews;	// IMP=0x000000010003c004
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003bff4
- (id)initWithFrame:(struct CGRect)arg1 contentView:(id)arg2;	// IMP=0x000000010003bf24

@end

