//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SVSTranscriptContentView, UICollectionView;

@interface SVSTranscriptView : UIView
{
    SVSTranscriptContentView *_contentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003cd84
- (void)setKeylineHidden:(_Bool)arg1;	// IMP=0x000000010003cd68
@property(nonatomic) double topMargin;
@property(retain, nonatomic) UIView *suggestionsView;
@property(readonly, nonatomic) UICollectionView *collectionView;
- (void)layoutSubviews;	// IMP=0x000000010003cc84
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003cc74
- (id)initWithFrame:(struct CGRect)arg1 collectionView:(id)arg2;	// IMP=0x000000010003cb6c

@end

