//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBSViewServicePresenter.h"

@class NSString;

@interface TVCRDServiceLoadingViewController : UIViewController <PBSViewServicePresenter>
{
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0000000100006328
+ (id)_exportedInterface;	// IMP=0x000000010000620c
- (void)_menuPressed:(id)arg1;	// IMP=0x00000001000063e0
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000060a0
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x0000000100005fb8
- (void)viewDidLoad;	// IMP=0x00000001000052d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

