//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVPAOSynchronizer : NSObject
{
    id _accessObject;	// 8 = 0x8
}

+ (id)syncAccessObjectWithFactory:(CDUnknownBlockType)arg1;	// IMP=0x0000000100041cb8
+ (void)flushWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100041c14
+ (void)initialize;	// IMP=0x0000000100041bb4
@property(retain, nonatomic) id accessObject; // @synthesize accessObject=_accessObject;
- (void).cxx_destruct;	// IMP=0x0000000100042160
- (void)queuePostOperation:(CDUnknownBlockType)arg1;	// IMP=0x0000000100042134
- (void)queueOperation:(CDUnknownBlockType)arg1;	// IMP=0x0000000100041fe0
- (void)tearDownWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100041e60
- (id)initWithFactory:(CDUnknownBlockType)arg1;	// IMP=0x0000000100041d34
- (id)init;	// IMP=0x0000000100041d1c

@end

