//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, TVSDataQuery;

@interface TVPDataQueryContext : NSObject
{
    TVSDataQuery *_query;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    CDUnknownBlockType _completionHandler;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, retain, nonatomic) TVSDataQuery *query; // @synthesize query=_query;
- (void).cxx_destruct;	// IMP=0x0000000100039d14
- (id)subcontextWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100039c20
- (void)performCompletion;	// IMP=0x0000000100039bb8
- (_Bool)isQueryStillValid;	// IMP=0x0000000100039b68
- (id)initWithQuery:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100039a5c

@end

