//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPSharedPSAlbumDescriptionView.h"

@class TVPFolderView;

@interface TVPFolderCell : TVPSharedPSAlbumDescriptionView
{
    TVPFolderView *_folderView;	// 8 = 0x8
}

@property(retain, nonatomic) TVPFolderView *folderView; // @synthesize folderView=_folderView;
- (void).cxx_destruct;	// IMP=0x000000010003a078
- (void)updateFolderImage;	// IMP=0x0000000100039f0c
- (void)layoutSubviews;	// IMP=0x0000000100039e88
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100039dd8

@end

