//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, UIApplication;

@interface TVPhotosAppDelegateTesting : NSObject
{
    id <TVPhotosAppDelegateTestingDelegate> _delegate;	// 8 = 0x8
    UIApplication *__application;	// 16 = 0x10
    NSString *__testName;	// 24 = 0x18
    NSDictionary *__testOptions;	// 32 = 0x20
}

@property(retain, nonatomic, setter=_setTestOptions:) NSDictionary *_testOptions; // @synthesize _testOptions=__testOptions;
@property(retain, nonatomic, setter=_setTestName:) NSString *_testName; // @synthesize _testName=__testName;
@property(retain, nonatomic, setter=_setApplication:) UIApplication *_application; // @synthesize _application=__application;
@property(nonatomic) __weak id <TVPhotosAppDelegateTestingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100005c28
- (id)_tabViewController;	// IMP=0x0000000100005a58
- (id)_rootNavigationController;	// IMP=0x00000001000059dc
- (_Bool)_navigateToRootOfCurrentTabAnimated:(_Bool)arg1;	// IMP=0x00000001000057ac
- (id)_tabRootViewControllerInNavigationController:(id)arg1;	// IMP=0x00000001000055f4
- (void)runScrollMemoriesFeedTest:(id)arg1;	// IMP=0x000000010000552c
- (void)_navigateToMemoriesFeedForCurrentTest:(CDUnknownBlockType)arg1;	// IMP=0x00000001000051e4
- (void)runFocusMoveAlbumsTest:(id)arg1;	// IMP=0x000000010000506c
- (void)runSwipeAlbumsTest:(id)arg1;	// IMP=0x0000000100004ef4
- (void)runScrollAlbumsTest:(id)arg1;	// IMP=0x0000000100004d64
- (void)runFocusMoveMomentsTest:(id)arg1;	// IMP=0x0000000100004c70
- (void)runSwipeMomentsTest:(id)arg1;	// IMP=0x0000000100004b7c
- (void)runScrollMomentsTest:(id)arg1;	// IMP=0x0000000100004a48
- (void)_performFocusMoveTest;	// IMP=0x0000000100004220
- (void)_performSwipeTest;	// IMP=0x0000000100004110
- (void)_performScrollTestOnScrollView:(id)arg1;	// IMP=0x0000000100003fc0
- (int)_scrollAxisForTestWithOptions:(id)arg1;	// IMP=0x0000000100003f54
- (int)_scrollTestDelta:(id)arg1 options:(id)arg2;	// IMP=0x0000000100003e2c
- (int)_scrollTestLength:(id)arg1 options:(id)arg2;	// IMP=0x0000000100003dac
- (void)_failedCurrentTest;	// IMP=0x0000000100003d0c
- (void)_finishedCurrentTest;	// IMP=0x0000000100003c6c
- (void)_startedCurrentTest;	// IMP=0x0000000100003bfc
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;	// IMP=0x0000000100003aac

@end

