//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "TVPhotosAppDelegateTestingDelegate.h"
#import "UIApplicationDelegate.h"
#import "UIApplicationTestingDelegate.h"

@class NSString, TVPhotosAppDelegateTesting, TVPiCloudPhotoSettings, UIViewController, UIWindow;

@interface TVPhotosAppDelegate : UIResponder <TVPhotosAppDelegateTestingDelegate, UIApplicationTestingDelegate, UIApplicationDelegate>
{
    _Bool _photoPickerModeEnabled;	// 8 = 0x8
    _Bool _didFinishAppLaunch;	// 9 = 0x9
    UIWindow *_window;	// 16 = 0x10
    TVPiCloudPhotoSettings *_iCloudSettings;	// 24 = 0x18
    UIViewController *_photoPickerViewController;	// 32 = 0x20
    TVPhotosAppDelegateTesting *_applicationTesting;	// 40 = 0x28
}

@property(readonly, nonatomic) TVPhotosAppDelegateTesting *applicationTesting; // @synthesize applicationTesting=_applicationTesting;
@property(retain, nonatomic) UIViewController *photoPickerViewController; // @synthesize photoPickerViewController=_photoPickerViewController;
@property(nonatomic) _Bool didFinishAppLaunch; // @synthesize didFinishAppLaunch=_didFinishAppLaunch;
@property(retain, nonatomic) TVPiCloudPhotoSettings *iCloudSettings; // @synthesize iCloudSettings=_iCloudSettings;
@property(nonatomic, getter=isPhotoPickerModeEnabled) _Bool photoPickerModeEnabled; // @synthesize photoPickerModeEnabled=_photoPickerModeEnabled;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;	// IMP=0x000000010001be30
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;	// IMP=0x000000010001bc50
- (void)_tvs_enableSharedPhotoStreamPostUpdateForAccount:(id)arg1;	// IMP=0x000000010001baf0
- (void)_tvs_enableMyPhotoStreamPostUpdateForAccount:(id)arg1;	// IMP=0x000000010001b990
- (void)_setUpScreensaverPickerUI;	// IMP=0x000000010001b918
- (_Bool)_isDisplayingPhotoStreamContent;	// IMP=0x000000010001b8b0
- (void)_performAppLaunchForScheme:(id)arg1;	// IMP=0x000000010001b1a4
- (void)_updateApplicationUIWithRootController:(id)arg1 forceRefresh:(_Bool)arg2;	// IMP=0x000000010001b190
- (void)_deactivateApplication;	// IMP=0x000000010001b124
- (void)_displayActivityIndicator;	// IMP=0x000000010001af90
- (void)_updateCRDPreferencesWithImage:(id)arg1;	// IMP=0x000000010001ae90
- (void)photoPickerViewController:(id)arg1 selectedPhotoAsset:(id)arg2;	// IMP=0x000000010001ac7c
- (void)internetAvailabilityChanged:(id)arg1;	// IMP=0x000000010001ab40
- (void)iCloudAccountStatusChanged:(id)arg1;	// IMP=0x000000010001a798
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x000000010001a748
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x000000010001a700
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x000000010001a6f0
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010001a008
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x0000000100019f8c
- (id)init;	// IMP=0x0000000100019ef8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

