//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPAccessObject.h"

#import "MSDeleterPlugin.h"
#import "MSSubscriberPlugin.h"
#import "TVSPushNotificationListener.h"

@class NSArray, NSString, TVPMyPSImageLoadTask, TVSAssetLibrary;

@interface TVPMyPSAccessObject : TVPAccessObject <MSSubscriberPlugin, MSDeleterPlugin, TVSPushNotificationListener>
{
    struct sqlite3 *_db;	// 8 = 0x8
    NSArray *_assets;	// 16 = 0x10
    id <TVPMyPSAccessObjectDelegate> _delegate;	// 24 = 0x18
    TVSAssetLibrary *_imageManager;	// 32 = 0x20
    id <MSSubscriber> _subscriber;	// 40 = 0x28
    TVPMyPSImageLoadTask *_imageLoadTask;	// 48 = 0x30
}

+ (id)deleterPluginForPersonID:(id)arg1;	// IMP=0x00000001000519ac
+ (id)personIDsForPollingTriggeredByPushNotification;	// IMP=0x00000001000512b4
+ (id)subscriberPluginForPersonID:(id)arg1;	// IMP=0x00000001000511fc
+ (id)dbCachePathForPersonID:(id)arg1;	// IMP=0x0000000100051040
+ (id)accessObjectWithAppleAccount:(id)arg1;	// IMP=0x0000000100050b3c
@property(retain, nonatomic) TVPMyPSImageLoadTask *imageLoadTask; // @synthesize imageLoadTask=_imageLoadTask;
@property(nonatomic) __weak id <MSSubscriber> subscriber; // @synthesize subscriber=_subscriber;
@property(retain, nonatomic) TVSAssetLibrary *imageManager; // @synthesize imageManager=_imageManager;
@property(nonatomic) __weak id <TVPMyPSAccessObjectDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;	// IMP=0x0000000100054280
- (void)_removeAssets:(id)arg1;	// IMP=0x0000000100053e54
- (void)_addNewAssetsFromServerAssets:(id)arg1;	// IMP=0x0000000100053a2c
- (id)_assetForAssetID:(id)arg1;	// IMP=0x000000010005387c
- (void)_didFinishDeletingAssetCollection:(id)arg1 error:(id)arg2;	// IMP=0x0000000100053658
- (void)_didReceiveDeleteForAssetCollections:(id)arg1;	// IMP=0x0000000100053424
- (void)_didCompleteCheckForNewAssetCollections;	// IMP=0x0000000100053328
- (void)_didFinishRetrievingAsset:(id)arg1 imageData:(id)arg2 error:(id)arg3;	// IMP=0x0000000100052bf4
- (void)_didRequestAssetRetrievalForAssetCollections:(id)arg1;	// IMP=0x0000000100052110
- (void)_loadImageForImageTokens:(id)arg1;	// IMP=0x0000000100052028
- (id)_imageTokenForAssetID:(id)arg1;	// IMP=0x000000010005201c
- (id)_imageForAssetID:(id)arg1 canLoad:(_Bool *)arg2;	// IMP=0x0000000100051f4c
- (void)_tearDown;	// IMP=0x0000000100051e18
- (void)_runSetup;	// IMP=0x0000000100051ce4
- (void)pushNotificationServerTokenDidChange:(id)arg1;	// IMP=0x0000000100051ce0
- (void)pushNotificationServer:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000100051bbc
- (void)deleter:(id)arg1 didFinishDeletingAssetCollection:(id)arg2 error:(id)arg3;	// IMP=0x0000000100051a64
- (void)subscriberDidCompleteCheckForNewAssetCollections:(id)arg1;	// IMP=0x0000000100051928
- (void)subscriber:(id)arg1 didReceiveDeleteForAssetCollections:(id)arg2 streamID:(id)arg3;	// IMP=0x0000000100051814
- (void)subscriber:(id)arg1 didFailToRetriveSubscriptionUpdateWithError:(id)arg2;	// IMP=0x0000000100051810
- (void)subscriber:(id)arg1 didFinishRetrievingAsset:(id)arg2 error:(id)arg3;	// IMP=0x0000000100051604
- (void)subscriber:(id)arg1 didFinishRequestingAssetRetrievalForStreamID:(id)arg2;	// IMP=0x0000000100051600
- (void)subscriber:(id)arg1 didRequestAssetRetrievalForAssetCollections:(id)arg2 streamID:(id)arg3;	// IMP=0x00000001000514ec
- (void)subscriberWillAssignPluginAsDelegateOfSubscriber:(id)arg1;	// IMP=0x00000001000513d8
- (void)removeAssetForAssetID:(id)arg1;	// IMP=0x0000000100050ce4
- (void)tearDown;	// IMP=0x0000000100050c70
- (void)_insertDBAsset:(id)arg1;	// IMP=0x0000000100055018
- (id)_dateFormatter;	// IMP=0x0000000100054f34
- (void)_removeDBAsset:(id)arg1;	// IMP=0x0000000100054e60
- (void)_removeDBAssets:(id)arg1;	// IMP=0x0000000100054cd4
- (void)_insertDBAssets:(id)arg1;	// IMP=0x0000000100054b58
- (void)_updateDBAsset:(id)arg1 newState:(int)arg2;	// IMP=0x0000000100054a58
- (void)_removeDB;	// IMP=0x0000000100054910
- (id)_loadAssetsFromDB;	// IMP=0x0000000100054404
- (void)_createOrOpenDB;	// IMP=0x00000001000542f4
- (void)_writeImageFromImageData:(id)arg1 assetID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000554c4
- (void)_purgeImages;	// IMP=0x0000000100055478
- (void)_purgeImageForAssetID:(id)arg1;	// IMP=0x000000010005540c
- (id)_imageForAssetID:(id)arg1;	// IMP=0x000000010005537c
- (id)_imagePathForAssetID:(id)arg1;	// IMP=0x00000001000552ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

