//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSBackgroundTask.h"

@interface TVPMyPSImageLoadTask : TVSBackgroundTask
{
    _Bool _shouldPerformLoad;	// 8 = 0x8
    _Bool _isLoading;	// 9 = 0x9
    id <TVPMyPSImageLoadTaskDelegate> _delegate;	// 16 = 0x10
    unsigned long long _loadID;	// 24 = 0x18
}

@property(nonatomic) unsigned long long loadID; // @synthesize loadID=_loadID;
@property(nonatomic) __weak id <TVPMyPSImageLoadTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool shouldPerformLoad; // @synthesize shouldPerformLoad=_shouldPerformLoad;
- (void).cxx_destruct;	// IMP=0x000000010000a94c
- (void)stop;	// IMP=0x000000010000a85c
- (_Bool)perform;	// IMP=0x000000010000a7f8
- (id)init;	// IMP=0x000000010000a7b4

@end

