//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@interface TVPPhotoLibraryTabViewController : UITabBarController
{
}

- (void)ppt_navigateToTabMode:(long long)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010003d28c
- (void)navigateToTabMode:(long long)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010003d1e8
- (id)_viewControllerForMode:(long long)arg1;	// IMP=0x000000010003d040

@end

