//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPPhotoLibraryCollectionViewController.h"

#import "PHPhotoLibraryChangeObserver.h"
#import "TVPCollectionViewCachingManagerDataSource.h"
#import "TVPPhotoLibraryOneUpViewControllerDelegate.h"

@class NSIndexPath, NSString, NSTimer, PHAssetCollection, PLCloudSharedAlbum, TVModalPresenter, TVPCollectionViewCachingManager, TVPFetchManager, TVPSharedPSSubscriberListViewController;

@interface TVPPhotoLibraryAlbumViewController : TVPPhotoLibraryCollectionViewController <PHPhotoLibraryChangeObserver, TVPPhotoLibraryOneUpViewControllerDelegate, TVPCollectionViewCachingManagerDataSource>
{
    PHAssetCollection *_album;	// 8 = 0x8
    NSIndexPath *_preferredFocusIndexPath;	// 16 = 0x10
    TVModalPresenter *_presenter;	// 24 = 0x18
    TVPFetchManager *_fetchManager;	// 32 = 0x20
    TVPCollectionViewCachingManager *_cachingManager;	// 40 = 0x28
    TVPSharedPSSubscriberListViewController *_subscribersListController;	// 48 = 0x30
    PLCloudSharedAlbum *_pl_sharedAlbum;	// 56 = 0x38
    NSTimer *_updateAssetsAndReloadTimer;	// 64 = 0x40
}

@property(retain, nonatomic) NSTimer *updateAssetsAndReloadTimer; // @synthesize updateAssetsAndReloadTimer=_updateAssetsAndReloadTimer;
@property(retain, nonatomic) PLCloudSharedAlbum *pl_sharedAlbum; // @synthesize pl_sharedAlbum=_pl_sharedAlbum;
@property(retain, nonatomic) TVPSharedPSSubscriberListViewController *subscribersListController; // @synthesize subscribersListController=_subscribersListController;
@property(retain, nonatomic) TVPCollectionViewCachingManager *cachingManager; // @synthesize cachingManager=_cachingManager;
@property(retain, nonatomic) TVPFetchManager *fetchManager; // @synthesize fetchManager=_fetchManager;
@property(retain, nonatomic) TVModalPresenter *presenter; // @synthesize presenter=_presenter;
@property(retain, nonatomic) NSIndexPath *preferredFocusIndexPath; // @synthesize preferredFocusIndexPath=_preferredFocusIndexPath;
@property(retain, nonatomic) PHAssetCollection *album; // @synthesize album=_album;
- (void).cxx_destruct;	// IMP=0x000000010005f318
- (id)_indexPathsFromIndexes:(id)arg1;	// IMP=0x000000010005efd0
- (void)_onSelectSubscribersButton:(id)arg1;	// IMP=0x000000010005ee3c
- (void)_sharedAlbumStreamDeletedOrUnsubscribedNotification:(id)arg1;	// IMP=0x000000010005edb8
- (void)_menuAction:(id)arg1;	// IMP=0x000000010005ed80
- (void)_onSelectSlideshowButton:(id)arg1;	// IMP=0x000000010005eccc
- (void)_onSelectScreenSaverButton:(id)arg1;	// IMP=0x000000010005eb9c
- (id)_allPhotoAssets;	// IMP=0x000000010005ea94
- (id)_assetAtIndexPath:(id)arg1;	// IMP=0x000000010005e98c
- (void)_cancelExistingTimer;	// IMP=0x000000010005e940
- (void)_didFinishTimedInterval:(id)arg1;	// IMP=0x000000010005e828
- (id)collectionViewCachingManager:(id)arg1 assetsForIndexPaths:(id)arg2;	// IMP=0x000000010005e648
- (Class)_collectionViewCellClass;	// IMP=0x000000010005e634
- (Class)_sectionHeaderViewClass;	// IMP=0x000000010005e620
- (void)photoLibraryDidChange:(id)arg1;	// IMP=0x000000010005e418
- (void)photoLibraryOneUpControllerWillPop:(id)arg1;	// IMP=0x000000010005e2c8
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x000000010005e21c
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010005e190
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010005deb4
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010005d69c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010005d31c
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010005d2c4
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x000000010005d280
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x000000010005d23c
- (void)dealloc;	// IMP=0x000000010005d060
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010005cfb8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010005ceec
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010005cdc8
- (void)viewDidLoad;	// IMP=0x000000010005cd2c
- (id)init;	// IMP=0x000000010005cc60

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

