//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVOneupView.h"

@class UIView;

@interface TVPSharedPSOneupView : TVOneupView
{
    UIView *_commentsBubbleView;	// 8 = 0x8
    UIView *_itemContainerView;	// 16 = 0x10
}

@property(retain, nonatomic) UIView *itemContainerView; // @synthesize itemContainerView=_itemContainerView;
@property(retain, nonatomic) UIView *commentsBubbleView; // @synthesize commentsBubbleView=_commentsBubbleView;
- (void).cxx_destruct;	// IMP=0x0000000100027a88
- (id)_getSecondaryCommentsViewFromParentView;	// IMP=0x0000000100027880
- (void)_setFrameForSecondaryView:(id)arg1 itemViewFrame:(struct CGRect)arg2;	// IMP=0x0000000100027800
- (void)_performPushTransitionToView:(id)arg1 atNewIndex:(long long)arg2;	// IMP=0x0000000100027300
- (void)_addAllSubviews;	// IMP=0x00000001000271a8
- (void)_menuAction:(id)arg1;	// IMP=0x0000000100027130
- (void)_transitionToItemAtIndex:(long long)arg1;	// IMP=0x0000000100026ebc
- (void)_configureSupplementaryView;	// IMP=0x0000000100026d64
- (void)_configureItemView:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x0000000100026c14
- (void)_transitionToFullScreenMode;	// IMP=0x0000000100026948
- (void)_transitionToCaptionMode;	// IMP=0x0000000100026418
- (void)_longPressAction:(id)arg1;	// IMP=0x00000001000261d8
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x00000001000261d0
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x0000000100026060
- (id)preferredFocusEnvironments;	// IMP=0x0000000100025e74
- (_Bool)canBecomeFocused;	// IMP=0x0000000100025e6c
- (void)switchToOneupCaptionView;	// IMP=0x0000000100025e60

@end

