//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AEHelper.h"

@class AEAnnotationProvider, NSArray, NSDictionary, NSString, NSURL;

@interface AEAggregationhelper : NSObject <AEHelper>
{
    NSArray *_plugins;	// 8 = 0x8
    NSURL *_url;	// 16 = 0x10
    NSDictionary *_options;	// 24 = 0x18
}

- (void)helperViewControllerWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001eda50
- (void)viewControllerFromPluginIndex:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001ed6c8
- (_Bool)acknowledgeAnnotationProvider:(id)arg1 willMergeAnnotationsWithAssertVersionMismatch:(id)arg2 assetID:(id)arg3 assetURL:(id)arg4;	// IMP=0x00000001001ed4ec
@property(readonly, nonatomic) AEAnnotationProvider *annotationProvider;
- (void)helperDeletePersistentCache;	// IMP=0x00000001001ed198
- (void)setMetadata:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001001ed028
- (id)helperMetadataForKey:(id)arg1;	// IMP=0x00000001001ece68
- (id)helperCoverImage;	// IMP=0x00000001001eccb0
- (void)dealloc;	// IMP=0x00000001001ecc14
- (id)initWithPlugins:(id)arg1 forUrl:(id)arg2 withOptions:(id)arg3;	// IMP=0x00000001001ecb78

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

