//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEMarginNotesControllerAccessibility_super.h"

@interface AEMarginNotesControllerAccessibility : AEMarginNotesControllerAccessibility_super
{
}

+ (void)_initializeSafeCategory;	// IMP=0x00000001001f440c
- (void)addMarginNote:(id)arg1;	// IMP=0x00000001001f4420

@end

