//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMBookshelfImageConfiguration, IMTopShelf, NSOperationQueue, NSString;

@interface IMBookshelfImageGenerator : NSObject
{
    IMTopShelf *_portraitTopShelf;	// 8 = 0x8
    IMTopShelf *_alternatePortraitTopShelf;	// 16 = 0x10
    IMTopShelf *_landscapeTopShelf;	// 24 = 0x18
    IMTopShelf *_alternateLandscapeTopShelf;	// 32 = 0x20
    NSString *_outputDirectory;	// 40 = 0x28
    long long _numberOfShelves;	// 48 = 0x30
    NSOperationQueue *_writeQueue;	// 56 = 0x38
    _Bool _useSynchronousWrites;	// 64 = 0x40
    double _shelfHeight;	// 72 = 0x48
    IMBookshelfImageConfiguration *_configuration;	// 80 = 0x50
}

+ (_Bool)writeCgImageRef:(struct CGImage *)arg1 toPath:(id)arg2 type:(struct __CFString *)arg3;	// IMP=0x00000001001753e8
@property(retain, nonatomic) IMBookshelfImageConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) double shelfHeight; // @synthesize shelfHeight=_shelfHeight;
@property(nonatomic) _Bool useSynchronousWrites; // @synthesize useSynchronousWrites=_useSynchronousWrites;
@property(nonatomic) long long numberOfShelves; // @synthesize numberOfShelves=_numberOfShelves;
@property(retain, nonatomic) NSString *outputDirectory; // @synthesize outputDirectory=_outputDirectory;
- (id)alternateLandscapeTopShelfImage;	// IMP=0x0000000100175a4c
- (id)landscapeTopShelfImage;	// IMP=0x0000000100175a34
- (id)alternatePortraitTopShelfImage;	// IMP=0x00000001001759dc
- (id)portraitTopShelfImage;	// IMP=0x00000001001759c4
- (id)alternateLandscapeImageArray;	// IMP=0x0000000100175974
- (id)alternatePortraitImageArray;	// IMP=0x0000000100175924
- (id)landscapeImageArray;	// IMP=0x000000010017590c
- (id)portraitImageArray;	// IMP=0x00000001001758f4
- (void)createWithSize:(struct CGSize)arg1 isPad:(_Bool)arg2 isPortrait:(_Bool)arg3 scale:(double)arg4 alternate:(_Bool)arg5;	// IMP=0x00000001001755c0
- (void)createWithSize:(struct CGSize)arg1 isPad:(_Bool)arg2 isPortrait:(_Bool)arg3 scale:(double)arg4;	// IMP=0x00000001001755b0
- (void)memoryWarning:(id)arg1;	// IMP=0x0000000100175384
- (void)dealloc;	// IMP=0x0000000100175280
- (void)_releaseImages;	// IMP=0x0000000100175210
- (id)init;	// IMP=0x0000000100175150

@end

