//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIImage;

@interface IMBookshelfImageConfiguration : NSObject
{
    UIImage *_shelfBackgroundImage;	// 8 = 0x8
    UIImage *_topShelfShadingImage;	// 16 = 0x10
    UIImage *_appleLogoImage;	// 24 = 0x18
    UIImage *_shelfImage;	// 32 = 0x20
    UIImage *_landscapeShelfImage;	// 40 = 0x28
    UIImage *_shelfShadingImage;	// 48 = 0x30
    UIImage *_alternateLandscapeShelfImage;	// 56 = 0x38
    _Bool _usesModernUI;	// 64 = 0x40
    UIColor *_shelfGradientTopColor;	// 72 = 0x48
    UIColor *_shelfGradientMidColor;	// 80 = 0x50
    double _shelfGradientMidY;	// 88 = 0x58
    UIColor *_shelfGradientBottomColor;	// 96 = 0x60
    long long _numberOfShelves;	// 104 = 0x68
    double _topShelfHeight;	// 112 = 0x70
    double _shelfHeight;	// 120 = 0x78
}

@property(nonatomic) double shelfHeight; // @synthesize shelfHeight=_shelfHeight;
@property(nonatomic) double topShelfHeight; // @synthesize topShelfHeight=_topShelfHeight;
@property(nonatomic) long long numberOfShelves; // @synthesize numberOfShelves=_numberOfShelves;
@property(retain, nonatomic) UIColor *shelfGradientBottomColor; // @synthesize shelfGradientBottomColor=_shelfGradientBottomColor;
@property(nonatomic) double shelfGradientMidY; // @synthesize shelfGradientMidY=_shelfGradientMidY;
@property(retain, nonatomic) UIColor *shelfGradientMidColor; // @synthesize shelfGradientMidColor=_shelfGradientMidColor;
@property(retain, nonatomic) UIColor *shelfGradientTopColor; // @synthesize shelfGradientTopColor=_shelfGradientTopColor;
@property(nonatomic) _Bool usesModernUI; // @synthesize usesModernUI=_usesModernUI;
@property(retain, nonatomic) UIImage *alternateLandscapeShelfImage; // @synthesize alternateLandscapeShelfImage=_alternateLandscapeShelfImage;
@property(retain, nonatomic) UIImage *shelfShadingImage; // @synthesize shelfShadingImage=_shelfShadingImage;
@property(retain, nonatomic) UIImage *landscapeShelfImage; // @synthesize landscapeShelfImage=_landscapeShelfImage;
@property(retain, nonatomic) UIImage *shelfImage; // @synthesize shelfImage=_shelfImage;
@property(retain, nonatomic) UIImage *appleLogoImage; // @synthesize appleLogoImage=_appleLogoImage;
@property(retain, nonatomic) UIImage *topShelfShadingImage; // @synthesize topShelfShadingImage=_topShelfShadingImage;
@property(retain, nonatomic) UIImage *shelfBackgroundImage; // @synthesize shelfBackgroundImage=_shelfBackgroundImage;
- (void)dealloc;	// IMP=0x00000001001ede04

@end

