//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSMutableArray;

@interface IMCalendarMiniMonthView : UIControl
{
    id _delegate;	// 8 = 0x8
    CDStruct_b0fa4487 _displayedDate;	// 16 = 0x10
    CDStruct_b0fa4487 _displayedMonth;	// 32 = 0x20
    NSMutableArray *_calendarDayItems;	// 48 = 0x30
    int _frameCount;	// 56 = 0x38
    int _currentStartIndex;	// 60 = 0x3c
    int _touchDate;	// 64 = 0x40
    int _rowsNeededForCurrentMonth;	// 68 = 0x44
    _Bool _maskTouches;	// 72 = 0x48
}

+ (id)defaultParagraphStyle;	// IMP=0x00000001001aa668
@property(readonly, nonatomic) int rowsNeededForCurrentMonth; // @synthesize rowsNeededForCurrentMonth=_rowsNeededForCurrentMonth;
@property(nonatomic) _Bool maskTouches; // @synthesize maskTouches=_maskTouches;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) int touchDate; // @synthesize touchDate=_touchDate;
- (void)cancelTrackingWithEvent:(id)arg1;	// IMP=0x00000001001aaaec
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001aaac0
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001aaa7c
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001aaa38
- (void)updateTrackWithPoint:(struct CGPoint)arg1;	// IMP=0x00000001001aa914
- (void)hideTouchFeedback;	// IMP=0x00000001001aa8f8
- (void)setDisplayedDate:(CDStruct_b0fa4487)arg1;	// IMP=0x00000001001aa884
- (CDStruct_b0fa4487)displayedDate;	// IMP=0x00000001001aa870
- (void)setDisplayedMonth:(CDStruct_b0fa4487)arg1;	// IMP=0x00000001001aa7c4
- (CDStruct_b0fa4487)displayedMonth;	// IMP=0x00000001001aa7b0
- (void)dealloc;	// IMP=0x00000001001aa720
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00000001001aa22c
- (void)_drawBox:(struct CGRect)arg1;	// IMP=0x00000001001aa21c
- (void)_drawBox:(struct CGRect)arg1 fill:(_Bool)arg2;	// IMP=0x00000001001aa1a4
- (int)dayForPoint:(struct CGPoint)arg1;	// IMP=0x00000001001aa0d0
- (struct CGRect)rectForDay:(int)arg1;	// IMP=0x00000001001aa05c
- (struct CGRect)highlightRectForDayRect:(struct CGRect)arg1;	// IMP=0x00000001001aa040
- (void)_localeChanged;	// IMP=0x00000001001aa034
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001001a9f88
- (int)RowsNeededForMiniMonth:(CDStruct_b0fa4487)arg1;	// IMP=0x00000001001a9f0c
- (id)MiniDayFont;	// IMP=0x00000001001a9ef4
- (id)MiniDayNumberFont;	// IMP=0x00000001001a9edc
- (id)boxColor;	// IMP=0x00000001001a9ebc
- (id)todayTextColor;	// IMP=0x00000001001a9e8c
- (id)defaultNumberColor;	// IMP=0x00000001001a9e70
- (id)darkTextColor;	// IMP=0x00000001001a9e54
- (id)defaultTextColor;	// IMP=0x00000001001a9e34

@end

