//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISlider.h"

@class UIImage;

@interface IMCustomSlider : UISlider
{
    struct CGPoint _offset;	// 8 = 0x8
    _Bool _fineScrubbing;	// 24 = 0x18
    struct CGPoint _previousLocation;	// 32 = 0x20
    struct CGPoint _beginLocation;	// 48 = 0x30
    double _factor;	// 64 = 0x40
    int _speed;	// 72 = 0x48
    int _type;	// 76 = 0x4c
    UIImage *_thumb;	// 80 = 0x50
    UIImage *_highlightedThumb;	// 88 = 0x58
    id <IMCustomSliderDelegate> _delegate;	// 96 = 0x60
}

@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) UIImage *thumb; // @synthesize thumb=_thumb;
@property(retain, nonatomic) UIImage *highlightedThumb; // @synthesize highlightedThumb=_highlightedThumb;
@property(nonatomic) int speed; // @synthesize speed=_speed;
@property(nonatomic) id <IMCustomSliderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool fineScrubbing; // @synthesize fineScrubbing=_fineScrubbing;
@property(nonatomic) struct CGPoint offset; // @synthesize offset=_offset;
- (id)accessibilityValue;	// IMP=0x00000001001ab770
- (void)cancelTrackingWithEvent:(id)arg1;	// IMP=0x00000001001ab64c
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001ab518
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001ab1f0
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001001ab01c
- (void)updateFactor:(double)arg1;	// IMP=0x00000001001aaf30
- (float)_scaleForVerticalPosition:(double)arg1;	// IMP=0x00000001001aae74
- (float)_scaleForIdealValueForVerticalPosition:(double)arg1;	// IMP=0x00000001001aadd8
- (struct CGRect)thumbRectForBounds:(struct CGRect)arg1 trackRect:(struct CGRect)arg2 value:(float)arg3;	// IMP=0x00000001001aacd4
- (void)layoutSubviews;	// IMP=0x00000001001aac08
- (void)dealloc;	// IMP=0x00000001001aab8c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001aab58

@end

