//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IMFlipViewTransition;

@protocol IMFlipViewTransitionDelegate
- (void)flipViewClosedTransitionMidpoint:(IMFlipViewTransition *)arg1;
- (void)flipViewClosedTransitionFinished:(IMFlipViewTransition *)arg1;
- (void)flipViewOpenTransitionMidpoint:(IMFlipViewTransition *)arg1;
- (void)flipViewOpenTransitionFinished:(IMFlipViewTransition *)arg1;
@end

