//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView;

@interface IMForegroundTouchHighlightedButton : UIButton
{
    UIImageView *_foregroundTouch;	// 8 = 0x8
}

- (void)setHighlighted:(_Bool)arg1;	// IMP=0x000000010022fe40
- (void)setShowsTouchWhenHighlighted:(_Bool)arg1;	// IMP=0x000000010022fe3c
- (void)layoutSubviews;	// IMP=0x000000010022fcfc
- (void)dealloc;	// IMP=0x000000010022fc9c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010022fc44
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010022fbec
- (void)commonInit;	// IMP=0x000000010022fb34

@end

