//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSString, UIActivityIndicatorView, UIButton, UIColor, UIImageView, UILabel, UIView;

@interface IMGridCollectionViewCell : UICollectionViewCell
{
    UIImageView *_imageView;	// 8 = 0x8
    UILabel *_textLabel;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
    UIView *_highlightView;	// 32 = 0x20
    UIActivityIndicatorView *_workingView;	// 40 = 0x28
    UIButton *_closeBox;	// 48 = 0x30
    UIImageView *_badgeView;	// 56 = 0x38
    UILabel *_badgeLabel;	// 64 = 0x40
    UIView *_selectedWhitewashView;	// 72 = 0x48
    UIImageView *_selectedBadgeView;	// 80 = 0x50
    _Bool _useMaskForHighlightView;	// 88 = 0x58
    _Bool _highlighted;	// 89 = 0x59
    _Bool _working;	// 90 = 0x5a
    _Bool _showSelectionView;	// 91 = 0x5b
    UIColor *_borderColor;	// 96 = 0x60
    struct CGPoint _unjitterPoint;	// 104 = 0x68
    int _imageGravity;	// 120 = 0x78
    unsigned int _isGrabbed:1;	// 124 = 0x7c
    unsigned int _isEditing:1;	// 124 = 0x7c
    unsigned int _canDelete:1;	// 124 = 0x7c
    unsigned int _jiggleWhenEditing:1;	// 124 = 0x7c
    unsigned int _isSelected:1;	// 124 = 0x7c
    unsigned int _hidesWhitewash:1;	// 124 = 0x7c
    unsigned int _openSelected:1;	// 124 = 0x7c
    id <IMGridCollectionViewCellDelegate> _gridCellDelegate;	// 128 = 0x80
}

+ (id)_jitterTransformAnimation;	// IMP=0x00000001001e6140
+ (id)_jitterPositionAnimation;	// IMP=0x00000001001e5cf8
@property(nonatomic) id <IMGridCollectionViewCellDelegate> gridCellDelegate; // @synthesize gridCellDelegate=_gridCellDelegate;
@property(retain, nonatomic) UIImageView *selectedBadgeView; // @synthesize selectedBadgeView=_selectedBadgeView;
@property(retain, nonatomic) UIView *selectedWhitewashView; // @synthesize selectedWhitewashView=_selectedWhitewashView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) _Bool showSelectionView; // @synthesize showSelectionView=_showSelectionView;
@property(retain, nonatomic) UILabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
@property(retain, nonatomic) UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) int imageGravity; // @synthesize imageGravity=_imageGravity;
- (_Bool)isAccessibilityElement;	// IMP=0x00000001001e6a34
@property(readonly, nonatomic) struct UIEdgeInsets snapshotEdgeInsets;
- (void)setShowCloseBox:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001e66b0
- (void)setShowCloseBox:(_Bool)arg1;	// IMP=0x00000001001e66a0
- (void)_removeCloseBox;	// IMP=0x00000001001e6658
- (void)_removeWorkingView;	// IMP=0x00000001001e660c
- (void)_removeHighlightView;	// IMP=0x00000001001e65c4
- (void)_removeSelectedBadgeView;	// IMP=0x00000001001e6548
- (id)closeBox;	// IMP=0x00000001001e6450
- (void)deleteConfirmationControlWasClicked:(id)arg1;	// IMP=0x00000001001e63cc
- (void)setJiggling:(_Bool)arg1;	// IMP=0x00000001001e5b50
@property(nonatomic) _Bool jiggleWhenEditing;
- (void)setSelected:(_Bool)arg1;	// IMP=0x00000001001e589c
- (_Bool)isSelected;	// IMP=0x00000001001e5888
- (void)setHidesWhitewash:(_Bool)arg1;	// IMP=0x00000001001e5868
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x00000001001e572c
@property(nonatomic) _Bool canDelete;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001e55ec
@property(nonatomic, getter=isEditing) _Bool editing; // @dynamic editing;
- (void)setEnlargedSelectedState:(_Bool)arg1;	// IMP=0x00000001001e53ec
- (void)setGrabbed:(_Bool)arg1;	// IMP=0x00000001001e52f4
- (id)_gridView;	// IMP=0x00000001001e529c
@property(readonly, nonatomic) struct CGRect selectionFrame;
- (void)layoutSelectedBadgeViewWithContentFrame:(struct CGRect)arg1;	// IMP=0x00000001001e51c0
- (void)layoutSelectedWhitewashView;	// IMP=0x00000001001e514c
- (void)layoutSubviews;	// IMP=0x00000001001e4c58
- (void)layoutBadgeLabelForBadgeViewBounds:(struct CGRect)arg1;	// IMP=0x00000001001e4bc8
- (void)layoutBadgeViewForImageFrame:(struct CGRect)arg1;	// IMP=0x00000001001e4b00
- (struct CGRect)contentRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001001e4af4
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001001e4a4c
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001001e48cc
- (struct CGSize)scaledImageSizeForBounds:(struct CGRect)arg1;	// IMP=0x00000001001e4818
- (void)prepareForReuse;	// IMP=0x00000001001e46c8
- (id)workingView;	// IMP=0x00000001001e4508
- (id)highlightView;	// IMP=0x00000001001e430c
- (void)loadImageView;	// IMP=0x00000001001e41fc
@property(nonatomic, getter=isWorking) _Bool working;
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x00000001001e4010
- (_Bool)highlighted;	// IMP=0x00000001001e4000
@property(nonatomic) _Bool useMaskForHighlightView;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x00000001001e3ef0
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x00000001001e3e44
- (void)setBadgeText:(id)arg1;	// IMP=0x00000001001e3d90
- (void)setBadgeLabelNumber:(id)arg1;	// IMP=0x00000001001e3cc0
- (void)setNewBadge:(_Bool)arg1;	// IMP=0x00000001001e3c54
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001e399c
- (id)description;	// IMP=0x00000001001e3918
- (void)dealloc;	// IMP=0x00000001001e37c4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001001e376c

@end

