//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray;

@interface IMLibraryTiledBackgroundView : UIView
{
    struct CGPoint _offset;	// 8 = 0x8
    double _height;	// 24 = 0x18
    NSArray *_images;	// 32 = 0x20
    NSMutableArray *_tiles;	// 40 = 0x28
    struct CGSize _tileSize;	// 48 = 0x30
}

@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) struct CGSize tileSize; // @synthesize tileSize=_tileSize;
@property(nonatomic) struct CGPoint offset; // @synthesize offset=_offset;
- (void)setTileCount:(long long)arg1 viewProvider:(CDUnknownBlockType)arg2;	// IMP=0x000000010017e2e8
- (void)_adjustRowLayout;	// IMP=0x000000010017de88
- (void)dealloc;	// IMP=0x000000010017de1c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010017ddac

@end

