//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAttachmentInfoAEAnnotation.h"

@class NSManagedObjectID, NSString;

@protocol IMMutableAttachmentInfoAEAnnotation <IMAttachmentInfoAEAnnotation>
- (void)setAEAnnotationManagedObjectID:(NSManagedObjectID *)arg1;
- (void)setAEAnnotationUuid:(NSString *)arg1;
- (void)setAEAnnotationAssetID:(NSString *)arg1;
@end

