//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXMLParserDelegate.h"

@class IMPodcastFeed, NSDateFormatter, NSError, NSMutableString, NSString;

@interface IMPodcastParser : NSObject <NSXMLParserDelegate>
{
    long long _feedType;	// 8 = 0x8
    IMPodcastFeed *_parsedFeed;	// 16 = 0x10
    NSDateFormatter *_rssDateFormatter;	// 24 = 0x18
    _Bool _shouldBufferElementChars;	// 32 = 0x20
    NSMutableString *_elementCharBuffer;	// 40 = 0x28
    unsigned long long _itemElementNestCount;	// 48 = 0x30
    _Bool _inAuthorElement;	// 56 = 0x38
    NSString *_feedDescriptionSourceElement;	// 64 = 0x40
    _Bool _preferredFeedCategoryFound;	// 72 = 0x48
    _Bool _preferredItemCategoryFound;	// 73 = 0x49
    NSError *_parseError;	// 80 = 0x50
    _Bool _inGlobalImageElement;	// 88 = 0x58
}

+ (id)UTIFromMIMEType:(id)arg1;	// IMP=0x00000001001946ec
+ (id)UTIByExtension:(id)arg1;	// IMP=0x0000000100194580
+ (_Bool)isContentNamespace:(id)arg1;	// IMP=0x0000000100194564
+ (_Bool)isITunesNamespace:(id)arg1;	// IMP=0x00000001001944f4
@property(nonatomic) _Bool inGlobalImageElement; // @synthesize inGlobalImageElement=_inGlobalImageElement;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
@property(nonatomic) _Bool preferredItemCategoryFound; // @synthesize preferredItemCategoryFound=_preferredItemCategoryFound;
@property(nonatomic) _Bool preferredFeedCategoryFound; // @synthesize preferredFeedCategoryFound=_preferredFeedCategoryFound;
@property(retain, nonatomic) NSString *feedDescriptionSourceElement; // @synthesize feedDescriptionSourceElement=_feedDescriptionSourceElement;
@property(nonatomic) _Bool inAuthorElement; // @synthesize inAuthorElement=_inAuthorElement;
@property(nonatomic) unsigned long long itemElementNestCount; // @synthesize itemElementNestCount=_itemElementNestCount;
@property(retain, nonatomic) NSMutableString *elementCharBuffer; // @synthesize elementCharBuffer=_elementCharBuffer;
@property(nonatomic) _Bool shouldBufferElementChars; // @synthesize shouldBufferElementChars=_shouldBufferElementChars;
@property(retain, nonatomic) NSDateFormatter *rssDateFormatter; // @synthesize rssDateFormatter=_rssDateFormatter;
@property(retain, nonatomic) IMPodcastFeed *parsedFeed; // @synthesize parsedFeed=_parsedFeed;
@property(retain, nonatomic) NSError *parseError; // @synthesize parseError=_parseError;
- (id)elementCharBufferTrimmed;	// IMP=0x0000000100194828
- (void)endBufferingElementChars;	// IMP=0x0000000100194818
- (void)startBufferingElementChars;	// IMP=0x00000001001947a4
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;	// IMP=0x00000001001944e4
- (void)parser:(id)arg1 foundCharacters:(id)arg2;	// IMP=0x000000010019448c
- (void)postProcessItemElement:(id)arg1;	// IMP=0x000000010019432c
- (void)atomParser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;	// IMP=0x0000000100193d6c
- (void)rssParser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;	// IMP=0x0000000100193294
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;	// IMP=0x00000001001931f4
- (void)atomParser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;	// IMP=0x0000000100192c2c
- (void)_parseEnclosureElement:(id)arg1 forFeedItem:(id)arg2;	// IMP=0x00000001001929a4
- (void)rssParser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;	// IMP=0x00000001001922f0
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;	// IMP=0x00000001001921b8
- (id)dateFromAtomDateString:(id)arg1;	// IMP=0x0000000100192134
- (id)removeLastColonOfString:(id)arg1;	// IMP=0x0000000100192080
- (id)dateFromRSSDateString:(id)arg1;	// IMP=0x000000010019200c
- (void)parseStreamFromURL:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100191e68
- (id)parseWithData:(id)arg1;	// IMP=0x0000000100191cdc
- (void)dealloc;	// IMP=0x0000000100191c38
- (id)init;	// IMP=0x0000000100191b58

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

