//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISearchBarDelegate.h"

@class NSString, UIScrollView, UISearchBar, UIView, UIViewController<IMSearchContentController>;

@interface IMSearchContainerViewController : UIViewController <UISearchBarDelegate>
{
    UIView *_containerView;	// 8 = 0x8
    UISearchBar *_searchBar;	// 16 = 0x10
    UIScrollView *_contentScrollView;	// 24 = 0x18
    _Bool _usesLayoutGuide;	// 32 = 0x20
    _Bool _insetsAdjusted;	// 33 = 0x21
    _Bool _observesContentOffset;	// 34 = 0x22
    UIViewController<IMSearchContentController> *_contentViewController;	// 40 = 0x28
}

@property(nonatomic) _Bool observesContentOffset; // @synthesize observesContentOffset=_observesContentOffset;
@property(nonatomic) _Bool insetsAdjusted; // @synthesize insetsAdjusted=_insetsAdjusted;
@property(readonly, retain, nonatomic) UIViewController<IMSearchContentController> *contentViewController; // @synthesize contentViewController=_contentViewController;
- (_Bool)searchBarShouldEndEditing:(id)arg1;	// IMP=0x00000001001c2730
- (void)searchBarCancelButtonClicked:(id)arg1;	// IMP=0x00000001001c2720
- (_Bool)searchBarShouldBeginEditing:(id)arg1;	// IMP=0x00000001001c26c8
- (void)viewDidLoad;	// IMP=0x00000001001c2648
- (void)contentScrollViewDidChange;	// IMP=0x00000001001c2538
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001c24e0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001c2434
- (void)viewDidLayoutSubviews;	// IMP=0x00000001001c23d4
- (void)setInsetsAdjusted:(_Bool)arg1 force:(_Bool)arg2;	// IMP=0x00000001001c2268
- (void)loadView;	// IMP=0x00000001001c2020
- (void)dealloc;	// IMP=0x00000001001c1f24
- (void)_contentScrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;	// IMP=0x00000001001c1d48
- (id)initWithContentViewController:(id)arg1;	// IMP=0x00000001001c1b08

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

