//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMSplitViewController.h"

#import "UIPopoverControllerDelegate.h"

@class NSString, UIBarButtonItem, UIPopoverController;

@interface IMSplitPopViewController : IMSplitViewController <UIPopoverControllerDelegate>
{
    id _delegate;	// 128 = 0x80
    UIBarButtonItem *_barButtonPopSource;	// 136 = 0x88
    UIPopoverController *_popover;	// 144 = 0x90
    struct CGSize _popoverContentSize;	// 152 = 0x98
    _Bool _popoverMode;	// 168 = 0xa8
    int _style;	// 172 = 0xac
    Class _popoverBackgroundViewClass;	// 176 = 0xb0
    _Bool _forceSplit;	// 184 = 0xb8
}

@property(nonatomic) _Bool forceSplit; // @synthesize forceSplit=_forceSplit;
@property(retain, nonatomic) Class popoverBackgroundViewClass; // @synthesize popoverBackgroundViewClass=_popoverBackgroundViewClass;
@property(nonatomic) int style; // @synthesize style=_style;
@property(readonly, nonatomic) UIBarButtonItem *barButtonPopSource; // @synthesize barButtonPopSource=_barButtonPopSource;
@property(readonly, nonatomic) UIPopoverController *popover; // @synthesize popover=_popover;
@property(nonatomic) _Bool popoverMode; // @synthesize popoverMode=_popoverMode;
@property(nonatomic) struct CGSize popoverContentSize; // @synthesize popoverContentSize=_popoverContentSize;
@property(nonatomic) id <IMSplitPopViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)popoverControllerDidDismissPopover:(id)arg1;	// IMP=0x00000001001a522c
- (void)onPopoverButtonClick:(id)arg1;	// IMP=0x00000001001a5144
- (void)dismissPopoverAnimated:(_Bool)arg1;	// IMP=0x00000001001a512c
- (void)setupPopoverMode;	// IMP=0x00000001001a4e90
- (void)setupSplitMode;	// IMP=0x00000001001a4d3c
- (void)setupModeForOrientation:(long long)arg1;	// IMP=0x00000001001a4ce8
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001a4c5c
- (void)viewDidLayoutSubviews;	// IMP=0x00000001001a4bf8
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;	// IMP=0x00000001001a4ba0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001a4a90
- (void)dealloc;	// IMP=0x00000001001a4a20
- (void)releaseViews;	// IMP=0x00000001001a49c0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001001a4964

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

