//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToolbar.h"

#import "IMTopBar.h"

@class NSArray, NSString, UIBarButtonItem, UIImage, UIImageView, UIView;

@interface IMToolbar : UIToolbar <IMTopBar>
{
    _Bool _bottom;	// 8 = 0x8
    NSArray *_leftItems;	// 16 = 0x10
    UIView *_titleView;	// 24 = 0x18
    NSArray *_rightItems;	// 32 = 0x20
    UIBarButtonItem *_titleViewBarButtonItem;	// 40 = 0x28
    UIImage *_backgroundImage;	// 48 = 0x30
    UIImage *_miniBackgroundImage;	// 56 = 0x38
    UIImage *_backgroundImageBottom;	// 64 = 0x40
    UIImage *_miniBackgroundImageBottom;	// 72 = 0x48
    UIImage *_shadowImage;	// 80 = 0x50
    UIImageView *_shadow;	// 88 = 0x58
}

@property(retain, nonatomic) UIImage *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(retain, nonatomic) UIImage *miniBackgroundImageBottom; // @synthesize miniBackgroundImageBottom=_miniBackgroundImageBottom;
@property(retain, nonatomic) UIImage *backgroundImageBottom; // @synthesize backgroundImageBottom=_backgroundImageBottom;
@property(retain, nonatomic) UIImage *miniBackgroundImage; // @synthesize miniBackgroundImage=_miniBackgroundImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) NSArray *rightItems; // @synthesize rightItems=_rightItems;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSArray *leftItems; // @synthesize leftItems=_leftItems;
@property(nonatomic) _Bool bottom; // @synthesize bottom=_bottom;
- (id)backgroundImageForToolbarPosition:(long long)arg1 barMetrics:(long long)arg2;	// IMP=0x00000001001c19b4
- (void)setBackgroundImage:(id)arg1 forToolbarPosition:(long long)arg2 barMetrics:(long long)arg3;	// IMP=0x00000001001c1974
- (void)_updateControlMiniState;	// IMP=0x00000001001c16bc
- (struct CGRect)_centerFrame;	// IMP=0x00000001001c1344
- (id)_toolbarItemSubviews;	// IMP=0x00000001001c12bc
- (void)_updateItems;	// IMP=0x00000001001c1144
- (void)setLeftItems:(id)arg1 rightItems:(id)arg2;	// IMP=0x00000001001c1058
@property(readonly, nonatomic) _Bool mini;
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00000001001c0c30
- (void)layoutSubviews;	// IMP=0x00000001001c0934
- (void)layoutShadow;	// IMP=0x00000001001c082c
- (void)dealloc;	// IMP=0x00000001001c0718

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

