//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface IMTransitionAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _appearing;	// 8 = 0x8
    double _duration;	// 16 = 0x10
    id <IMTransitionAnimatorDelegate> _delegate;	// 24 = 0x18
}

@property(nonatomic) __weak id <IMTransitionAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool appearing; // @synthesize appearing=_appearing;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void).cxx_destruct;	// IMP=0x00000001001c7d70
- (void)animationEnded:(_Bool)arg1;	// IMP=0x00000001001c7cb4
- (void)willStartAnimation;	// IMP=0x00000001001c7c6c
- (void)animateTransition:(id)arg1;	// IMP=0x00000001001c7454
- (double)transitionDuration:(id)arg1;	// IMP=0x00000001001c7428

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

