//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSString;

@interface IMUbiquitousFileCache : NSObject
{
    NSString *_cachePrefix;	// 8 = 0x8
    NSMutableSet *_cacheProtectedUUID;	// 16 = 0x10
}

- (_Bool)isProtectedUUID:(id)arg1;	// IMP=0x000000010022dca8
- (void)protectCacheForUUID:(id)arg1;	// IMP=0x000000010022dc44
- (void)emptyCache;	// IMP=0x000000010022d968
- (id)cacheUbiquitousURL:(id)arg1 withUUID:(id)arg2 error:(id *)arg3;	// IMP=0x000000010022d594
- (id)cachePath;	// IMP=0x000000010022d564
- (_Bool)makeCacheDirectory;	// IMP=0x000000010022d48c
- (void)dealloc;	// IMP=0x000000010022d408
- (id)initWithCacheName:(id)arg1;	// IMP=0x000000010022d350
- (id)init;	// IMP=0x000000010022d26c
- (void)emptyCacheExceptForUUID:(id)arg1;	// IMP=0x000000010022dd00

@end

