//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MZKeyValueStoreControllerDelegate.h"
#import "MZKeyValueStoreTransactionProcessing.h"

@class IMKeyValueStoreController, IMKeyValueStoreTransaction, IMUPPBagContext, NSError, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface IMUniversalPlaybackPositionSyncHandler : NSObject <MZKeyValueStoreControllerDelegate, MZKeyValueStoreTransactionProcessing>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_syncOperationQueue;	// 16 = 0x10
    _Bool _canRequestStoreSignIn;	// 24 = 0x18
    _Bool _syncInProgress;	// 25 = 0x19
    _Bool _canceled;	// 26 = 0x1a
    IMKeyValueStoreController *_kvsController;	// 32 = 0x20
    id <MZUniversalPlaybackPositionDataSource> _dataSource;	// 40 = 0x28
    id <MZUniversalPlaybackPositionTransactionContext> _dataSourceTransactionContext;	// 48 = 0x30
    IMUPPBagContext *_bagContext;	// 56 = 0x38
    NSString *_responseDomainVersion;	// 64 = 0x40
    NSMutableDictionary *m_etadataItemsFromDataSource;	// 72 = 0x48
    NSMutableDictionary *_metadataItemsFromKVSStorage;	// 80 = 0x50
    NSMutableDictionary *_metadataItemsToCommitToDataSource;	// 88 = 0x58
    NSMutableDictionary *_metadataItemsToCommitToKVSStorage;	// 96 = 0x60
    NSMutableDictionary *_reportedItemVersionForIdentifier;	// 104 = 0x68
    IMKeyValueStoreTransaction *currentKVSTransaction;	// 112 = 0x70
    NSError *_fatalSyncError;	// 120 = 0x78
}

@property(retain) NSError *fatalSyncError; // @synthesize fatalSyncError=_fatalSyncError;
@property _Bool canceled; // @synthesize canceled=_canceled;
@property _Bool syncInProgress; // @synthesize syncInProgress=_syncInProgress;
@property(retain) IMKeyValueStoreTransaction *currentKVSTransaction; // @synthesize currentKVSTransaction;
@property(retain) NSMutableDictionary *reportedItemVersionForIdentifier; // @synthesize reportedItemVersionForIdentifier=_reportedItemVersionForIdentifier;
@property(retain) NSMutableDictionary *metadataItemsToCommitToKVSStorage; // @synthesize metadataItemsToCommitToKVSStorage=_metadataItemsToCommitToKVSStorage;
@property(retain) NSMutableDictionary *metadataItemsToCommitToDataSource; // @synthesize metadataItemsToCommitToDataSource=_metadataItemsToCommitToDataSource;
@property(retain) NSMutableDictionary *metadataItemsFromKVSStorage; // @synthesize metadataItemsFromKVSStorage=_metadataItemsFromKVSStorage;
@property(retain) NSMutableDictionary *metadataItemsFromDataSource; // @synthesize metadataItemsFromDataSource=m_etadataItemsFromDataSource;
@property(nonatomic) _Bool canRequestStoreSignIn; // @synthesize canRequestStoreSignIn=_canRequestStoreSignIn;
@property(retain) NSString *responseDomainVersion; // @synthesize responseDomainVersion=_responseDomainVersion;
@property(retain) IMUPPBagContext *bagContext; // @synthesize bagContext=_bagContext;
@property(retain) id <MZUniversalPlaybackPositionTransactionContext> dataSourceTransactionContext; // @synthesize dataSourceTransactionContext=_dataSourceTransactionContext;
@property(retain) id <MZUniversalPlaybackPositionDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain) IMKeyValueStoreController *kvsController; // @synthesize kvsController=_kvsController;
- (id)sinceDomainVersionForTransaction:(id)arg1;	// IMP=0x000000010004d748
- (id)keysForTransaction:(id)arg1;	// IMP=0x000000010004d724
- (void)transaction:(id)arg1 mergeData:(id)arg2 forKey:(id)arg3 domainVersion:(id)arg4 version:(id)arg5 mismatch:(_Bool)arg6 finishedBlock:(CDUnknownBlockType)arg7;	// IMP=0x000000010004d548
- (void)transaction:(id)arg1 didProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x000000010004d544
- (void)transaction:(id)arg1 willProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x000000010004d500
- (id)dataForSetTransaction:(id)arg1 key:(id)arg2 version:(id *)arg3;	// IMP=0x000000010004d48c
- (id)versionForGetTransaction:(id)arg1 key:(id)arg2;	// IMP=0x000000010004d484
- (void)keyValueStoreController:(id)arg1 transactionDidFinish:(id)arg2;	// IMP=0x000000010004d474
- (void)keyValueStoreController:(id)arg1 transaction:(id)arg2 didCancelWithError:(id)arg3;	// IMP=0x000000010004d460
- (_Bool)keyValueStoreController:(id)arg1 transaction:(id)arg2 didFailWithError:(id)arg3;	// IMP=0x000000010004d388
- (_Bool)keyValueStoreController:(id)arg1 shouldScheduleTransaction:(id)arg2;	// IMP=0x000000010004d380
- (void)_signalKVSTransactionCompletion:(id)arg1 withError:(id)arg2;	// IMP=0x000000010004d2ec
- (void)_signalKVSTransactionCompletion:(id)arg1;	// IMP=0x000000010004d298
- (id)_synchronouslyRunKVSTransaction:(id)arg1;	// IMP=0x000000010004d1a8
- (id)newKVSGetAllTransactionSinceDomainVersion:(id)arg1;	// IMP=0x000000010004d150
- (id)newKVSGetAllTransactionWithMetadataItems:(id)arg1;	// IMP=0x000000010004d104
- (id)newKVSPutAllTransactionWithMetadataItems:(id)arg1;	// IMP=0x000000010004cf4c
- (id)newKVSTransactionWithType:(int)arg1 keys:(id)arg2;	// IMP=0x000000010004ce40
- (void)_mergeMetadataItemsFromGetResponse;	// IMP=0x000000010004ca84
- (int)_mergeMetadataItemFromSetResponse:(id)arg1;	// IMP=0x000000010004c8f4
- (void)synchronizeWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010004c6bc
- (void)cancel;	// IMP=0x000000010004c6ac
- (void)timeout;	// IMP=0x000000010004c654
- (void)cancelWithError:(id)arg1;	// IMP=0x000000010004c538
- (_Bool)_shouldStop;	// IMP=0x000000010004c394
- (_Bool)_synchronize:(id *)arg1;	// IMP=0x000000010004bb8c
- (void)_dataSourceCancelTransaction;	// IMP=0x000000010004bb00
- (void)_resetState;	// IMP=0x000000010004ba30
- (void)dealloc;	// IMP=0x000000010004b8d8
- (id)initWithDataSource:(id)arg1 bagContext:(id)arg2;	// IMP=0x000000010004b694

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

