//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ITMReachability : NSObject
{
    _Bool _alwaysReturnLocalWiFiStatus;	// 8 = 0x8
    struct __SCNetworkReachability *_reachabilityRef;	// 16 = 0x10
}

+ (id)reachabilityForLocalWiFi;	// IMP=0x00000001001886e0
+ (id)reachabilityForInternetConnection;	// IMP=0x0000000100188684
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)arg1;	// IMP=0x000000010018860c
+ (id)reachabilityWithHostName:(id)arg1;	// IMP=0x0000000100188568
- (long long)currentReachabilityStatus;	// IMP=0x0000000100188c5c
- (_Bool)connectionRequired;	// IMP=0x0000000100188b58
- (long long)networkStatusForFlags:(unsigned int)arg1;	// IMP=0x0000000100188b20
- (long long)localWiFiStatusForFlags:(unsigned int)arg1;	// IMP=0x0000000100188b0c
- (void)dealloc;	// IMP=0x0000000100188aa8
- (void)stopNotifier;	// IMP=0x0000000100188a5c
- (_Bool)startNotifier;	// IMP=0x0000000100188760

@end

