//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIBarButtonItem;

@interface MTAddPodcastOrStationController : NSObject
{
    UIBarButtonItem *_plusButtonItem;	// 8 = 0x8
}

+ (id)createAndSaveStationWithTitle:(id)arg1;	// IMP=0x0000000100075aa8
- (void).cxx_destruct;	// IMP=0x000000010007601c
- (_Bool)userHasSomePodcasts;	// IMP=0x0000000100075f00
- (id)presentingViewController;	// IMP=0x0000000100075ea4
- (void)presentStationWithTitle:(id)arg1;	// IMP=0x00000001000759f4
- (void)presentAddStationUI;	// IMP=0x0000000100075438
- (void)performSubscribe:(id)arg1;	// IMP=0x0000000100075384
- (void)presentAddPodcastUIWithUrl:(id)arg1;	// IMP=0x0000000100074be0
- (void)presentAddPodcastUI;	// IMP=0x0000000100074bd0
- (void)plusButtonPressed:(id)arg1;	// IMP=0x0000000100074714
- (id)plusButtonItem;	// IMP=0x00000001000746a4

@end

