//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBaseQueryObserver.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSString;

@interface MTAllPropertyChangesQueryObserver : MTBaseQueryObserver <NSFetchedResultsControllerDelegate>
{
    _Bool _inCallback;	// 8 = 0x8
}

- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x0000000100014708
- (void)notifyObservers;	// IMP=0x00000001000145f8
- (void)startObserving;	// IMP=0x00000001000145a8
- (id)addResultsChangedHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001453c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

