//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTCountUtil : NSObject
{
}

+ (id)stringForStationCount:(long long)arg1;	// IMP=0x000000010011e710
+ (id)stringForPodcastCount:(long long)arg1;	// IMP=0x000000010011e564
+ (id)stringForEpisodeCount:(long long)arg1;	// IMP=0x000000010011e3b8

@end

