//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MTEpisodeListViewControllerDelegate.h"
#import "MTPodcastHeaderDelegate.h"
#import "UIPopoverControllerDelegate.h"

@class MTButtonBar, MTEpisodeListViewController, MTPodcastHeaderView, NSString, UIImage, UIPopoverController, UIView;

@interface MTDetailViewController : UIViewController <MTPodcastHeaderDelegate, MTEpisodeListViewControllerDelegate, UIPopoverControllerDelegate>
{
    UIImage *_image;	// 8 = 0x8
    MTButtonBar *_buttonBar;	// 16 = 0x10
    UIView *_behindNavView;	// 24 = 0x18
    _Bool _headerHidden;	// 32 = 0x20
    _Bool _forcePhoneStyle;	// 33 = 0x21
    float _topLayoutGuideLength;	// 36 = 0x24
    NSString *_podcastUuid;	// 40 = 0x28
    id <MTDetailViewControllerDelegate> _delegate;	// 48 = 0x30
    MTPodcastHeaderView *_headerView;	// 56 = 0x38
    MTEpisodeListViewController *_detailListViewController;	// 64 = 0x40
    UIImage *_podcastImage;	// 72 = 0x48
    UIView *_headerSeparatorView;	// 80 = 0x50
    UIPopoverController *_detailsPopover;	// 88 = 0x58
}

@property(nonatomic) float topLayoutGuideLength; // @synthesize topLayoutGuideLength=_topLayoutGuideLength;
@property(retain, nonatomic) UIPopoverController *detailsPopover; // @synthesize detailsPopover=_detailsPopover;
@property(retain, nonatomic) UIView *headerSeparatorView; // @synthesize headerSeparatorView=_headerSeparatorView;
@property(retain, nonatomic) UIImage *podcastImage; // @synthesize podcastImage=_podcastImage;
@property(retain, nonatomic) MTEpisodeListViewController *detailListViewController; // @synthesize detailListViewController=_detailListViewController;
@property(retain, nonatomic) MTPodcastHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <MTDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool forcePhoneStyle; // @synthesize forcePhoneStyle=_forcePhoneStyle;
@property(nonatomic) _Bool headerHidden; // @synthesize headerHidden=_headerHidden;
@property(retain, nonatomic) NSString *podcastUuid; // @synthesize podcastUuid=_podcastUuid;
- (void).cxx_destruct;	// IMP=0x000000010001077c
- (void)decodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100010514
- (void)encodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100010350
- (_Bool)popoverControllerShouldDismissPopover:(id)arg1;	// IMP=0x0000000100010348
- (_Bool)detailHeaderHasDisclosureButton:(id)arg1;	// IMP=0x0000000100010328
- (void)detailHeaderDisclosureButtonTapped:(id)arg1;	// IMP=0x0000000100010324
- (struct CGSize)imageSize;	// IMP=0x00000001000102ec
- (void)detailListController:(id)arg1 didTransitionToState:(long long)arg2;	// IMP=0x00000001000102e8
- (void)detailListController:(id)arg1 didChangeEditing:(_Bool)arg2 animated:(_Bool)arg3;	// IMP=0x000000010000fec4
- (void)detailListController:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010000fec0
- (void)layoutTopAndBottomButtonBars;	// IMP=0x000000010000fdc8
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010000fce8
- (id)newListController;	// IMP=0x000000010000fca8
- (void)updateHeaderView;	// IMP=0x000000010000fc10
- (_Bool)showBottomToolbarInsteadOfDetailHeader;	// IMP=0x000000010000fbc0
- (int)detailHeaderMode;	// IMP=0x000000010000fbb8
- (void)adjustScrollViewOffset;	// IMP=0x000000010000fa18
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010000f8f0
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;	// IMP=0x000000010000f888
- (void)viewDidLayoutSubviews;	// IMP=0x000000010000f060
- (void)viewDidLoad;	// IMP=0x000000010000eb50
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010000eaf4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000eaa4
- (void)dealloc;	// IMP=0x000000010000ea28
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010000e974
- (_Bool)usePad;	// IMP=0x000000010000e93c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

