//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableSet;

@interface MTEpisodeUpdaterCache : NSObject
{
    NSMutableSet *_unvisitedUuids;	// 8 = 0x8
    NSDictionary *_dictCache;	// 16 = 0x10
}

+ (id)episodeCacheWithPredicate:(id)arg1 inCtx:(id)arg2 extraProperties:(id)arg3;	// IMP=0x00000001001665f4
+ (id)episodeCacheWithPredicate:(id)arg1 inCtx:(id)arg2;	// IMP=0x0000000100166590
@property(retain, nonatomic) NSDictionary *dictCache; // @synthesize dictCache=_dictCache;
- (void).cxx_destruct;	// IMP=0x0000000100167a2c
- (id)itemUuidsToDelete;	// IMP=0x00000001001679cc
- (id)searchCacheForFeedItem:(id)arg1 enclosureUrl:(id)arg2;	// IMP=0x00000001001677e0
- (id)searchCacheForMediaItem:(id)arg1;	// IMP=0x00000001001675b0
- (id)episodeCacheItemForMediaLibraryId:(id)arg1;	// IMP=0x00000001001674e8
- (id)episodeCacheItemForAssetUrl:(id)arg1;	// IMP=0x0000000100167420
- (id)episodeCacheItemForEnclosure:(id)arg1;	// IMP=0x0000000100167358
- (id)episodeCacheItemForGuid:(id)arg1;	// IMP=0x0000000100167290
- (id)episodeCacheItemForTitle:(id)arg1 pubDate:(double)arg2;	// IMP=0x0000000100166f94
- (id)initWithPredicate:(id)arg1 inCtx:(id)arg2 extraProperties:(id)arg3;	// IMP=0x0000000100166698

@end

