//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTListViewController.h"

#import "IMActionControllerDelegate.h"
#import "MTEpisodeCellDelegate.h"

@class NSString, UIRefreshControl, UISearchController;

@interface MTEpisodeListViewController : MTListViewController <MTEpisodeCellDelegate, IMActionControllerDelegate>
{
    _Bool _needsScrollAdjust;	// 8 = 0x8
    double _lastDownloadUpdate;	// 16 = 0x10
    _Bool _cellularReachable;	// 24 = 0x18
    UISearchController *_searchController;	// 32 = 0x20
    _Bool _viewSizeChangedWhileNotVisible;	// 40 = 0x28
    _Bool _needsToFixUpHeaderInsets;	// 41 = 0x29
    double _cachedFixedRowHeight;	// 48 = 0x30
    struct CGSize _cachedExpandedRowSize;	// 56 = 0x38
    _Bool _showsArtworkInCells;	// 72 = 0x48
    _Bool _showFooterView;	// 73 = 0x49
    _Bool _disablesEditWhileRefreshing;	// 74 = 0x4a
    _Bool _disablesPullToRefreshWhileEditing;	// 75 = 0x4b
    int _refreshControlState;	// 76 = 0x4c
    id <MTEpisodeListViewControllerDelegate> _delegate;	// 80 = 0x50
    unsigned long long _cellStyle;	// 88 = 0x58
    NSString *_playingUuid;	// 96 = 0x60
    UIRefreshControl *_mt_refreshControl;	// 104 = 0x68
    NSString *_expandedEpisodeUuid;	// 112 = 0x70
    struct UIEdgeInsets __layoutMargins;	// 120 = 0x78
}

@property(nonatomic) struct UIEdgeInsets _layoutMargins; // @synthesize _layoutMargins=__layoutMargins;
@property(retain, nonatomic) NSString *expandedEpisodeUuid; // @synthesize expandedEpisodeUuid=_expandedEpisodeUuid;
@property(nonatomic) int refreshControlState; // @synthesize refreshControlState=_refreshControlState;
@property(retain, nonatomic, setter=mt_setRefreshControl:) UIRefreshControl *mt_refreshControl; // @synthesize mt_refreshControl=_mt_refreshControl;
@property(nonatomic) _Bool disablesPullToRefreshWhileEditing; // @synthesize disablesPullToRefreshWhileEditing=_disablesPullToRefreshWhileEditing;
@property(nonatomic) _Bool disablesEditWhileRefreshing; // @synthesize disablesEditWhileRefreshing=_disablesEditWhileRefreshing;
@property(readonly, copy, nonatomic) NSString *playingUuid; // @synthesize playingUuid=_playingUuid;
@property(nonatomic) _Bool showFooterView; // @synthesize showFooterView=_showFooterView;
@property(nonatomic) unsigned long long cellStyle; // @synthesize cellStyle=_cellStyle;
@property(nonatomic) __weak id <MTEpisodeListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool showsArtworkInCells; // @synthesize showsArtworkInCells=_showsArtworkInCells;
- (void).cxx_destruct;	// IMP=0x000000010002ad90
- (struct UIEdgeInsets)_layoutMarginsForViewWidth:(double)arg1;	// IMP=0x000000010002ab5c
- (id)editingToolbarItems;	// IMP=0x000000010002a91c
- (void)markSelectedItemsAsSaved:(_Bool)arg1;	// IMP=0x000000010002a694
- (void)markSelectedItems:(_Bool)arg1;	// IMP=0x000000010002a2ec
- (void)scrollToLatestIfNeeded:(_Bool)arg1;	// IMP=0x0000000100029e88
- (void)refetchWithSortDescriptors:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100029e20
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x0000000100029d5c
- (void)selectedItemAtIndexPath:(id)arg1;	// IMP=0x0000000100029b5c
- (void)scrollToExpandedEpisodeAnimated:(_Bool)arg1;	// IMP=0x0000000100029890
- (void)_updateRowHeightsForExpansionChange;	// IMP=0x0000000100029794
- (void)toggleExpansionForEpisodeUuid:(id)arg1;	// IMP=0x00000001000294d8
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x000000010002945c
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010002927c
- (double)tableView:(id)arg1 headerSizeForIndexPath:(id)arg2;	// IMP=0x00000001000291c0
- (void)didPerformActionInSheet:(id)arg1;	// IMP=0x00000001000291b4
- (void)dismissSwipeToDeleteMode;	// IMP=0x000000010002914c
- (_Bool)hasRemoveActionInsteadOfDeleteActionForRowAtIndexPath:(id)arg1;	// IMP=0x0000000100029144
- (_Bool)primaryActionIsMarkForSwipeGestureAtIndexPath:(id)arg1;	// IMP=0x000000010002913c
- (_Bool)hasMoreActionsForRowAtIndexPath:(id)arg1;	// IMP=0x0000000100029134
- (void)showMoreActionSheetFromButton:(id)arg1 forRowAtIndexPath:(id)arg2;	// IMP=0x0000000100029014
- (void)updateMarkRowAction:(id)arg1 forEpisode:(id)arg2;	// IMP=0x0000000100028db4
- (id)markRowActionForIndexPath:(id)arg1;	// IMP=0x0000000100028b08
- (id)removeRowActionForIndexPath:(id)arg1;	// IMP=0x0000000100028878
- (id)deleteRowActionForIndexPath:(id)arg1;	// IMP=0x0000000100028634
- (id)_moreRowAction;	// IMP=0x00000001000283f8
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000283f0
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100028274
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100028270
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100028160
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100028028
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x0000000100027fbc
- (id)reuseIdentifierForRow:(id)arg1;	// IMP=0x0000000100027f90
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;	// IMP=0x0000000100027f88
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100027e6c
- (void)removeEpisodeAtIndexPath:(id)arg1 fromButton:(id)arg2;	// IMP=0x0000000100027d20
- (void)pauseEpisodeAtIndexPath:(id)arg1;	// IMP=0x0000000100027cd8
- (void)playEpisodeAtIndexPath:(id)arg1;	// IMP=0x0000000100027cac
- (void)cellDidChangeSize:(id)arg1;	// IMP=0x0000000100027c30
- (void)cell:(id)arg1 moreButtonTapped:(id)arg2;	// IMP=0x0000000100027b9c
- (void)transitionToState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100027ad0
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x0000000100027a80
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x0000000100027940
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x000000010002790c
- (void)didEndRefreshing;	// IMP=0x00000001000278fc
- (void)endRefreshing;	// IMP=0x00000001000276a0
- (void)beginRefreshing;	// IMP=0x0000000100027624
- (void)refreshControlStateMovedToEnding;	// IMP=0x0000000100027620
- (void)refreshControlStateMovedToIdle;	// IMP=0x000000010002761c
- (void)refreshControlStateMovedToRefreshing;	// IMP=0x0000000100027618
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000274fc
- (_Bool)isSwipingExpandedCell;	// IMP=0x0000000100027434
- (void)_updateRowHeightsForEditingStateChange;	// IMP=0x000000010002736c
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100027240
- (id)footerView;	// IMP=0x0000000100027094
- (void)updateCellStyle;	// IMP=0x0000000100026f88
- (unsigned long long)sectionTypeForIndexPath:(id)arg1;	// IMP=0x0000000100026bd8
- (id)indexPathForEpisodeUuid:(id)arg1;	// IMP=0x0000000100026adc
- (void)updateEstimatedRowHeight;	// IMP=0x0000000100026970
- (void)nowPlayingStateChanged:(id)arg1;	// IMP=0x000000010002692c
- (void)nowPlayingItemChanged:(id)arg1;	// IMP=0x0000000100026920
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x0000000100026824
- (void)_updateNowPlayingGlyph;	// IMP=0x0000000100026570
- (_Bool)shouldShowNowPlayingGlyphWhenPaused;	// IMP=0x0000000100026568
- (void)fixSectionHeaderInsetsIfNeeded;	// IMP=0x00000001000263c4
- (void)fixEmptyTextContainers;	// IMP=0x0000000100026240
- (void)updateActionSheetsAndPopovers;	// IMP=0x00000001000260bc
- (void)dismissActionSheetsAndPopovers;	// IMP=0x0000000100025f38
- (void)playEpisodeWithUUID:(id)arg1;	// IMP=0x0000000100025eec
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0000000100025cbc
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100025c1c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100025b98
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100025a78
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100025a28
- (void)viewDidLoad;	// IMP=0x00000001000259c8
- (void)dealloc;	// IMP=0x000000010002593c
- (id)initWithCompositeFetchedResultsController:(id)arg1;	// IMP=0x00000001000257dc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

