//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBaseFeedManager.h"

@interface MTFeedUpdateManager : MTBaseFeedManager
{
}

- (_Bool)_updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 forced:(_Bool)arg3 useBackgroundFetch:(_Bool)arg4 tryRedirectURL:(_Bool)arg5;	// IMP=0x0000000100146b80
- (_Bool)_updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 forced:(_Bool)arg3 useBackgroundFetch:(_Bool)arg4;	// IMP=0x0000000100146b70
- (long long)_updatePodcastsWithUUIDs:(id)arg1 userInitiated:(_Bool)arg2 useBackgroundFetch:(_Bool)arg3;	// IMP=0x00000001001469a8
- (long long)_updateAllPodcastsUserInitiated:(_Bool)arg1 useBackgroundFetch:(_Bool)arg2;	// IMP=0x00000001001464f8
- (_Bool)isPodcastUpdatable:(id)arg1 userInitiated:(_Bool)arg2 forced:(_Bool)arg3;	// IMP=0x000000010014643c
- (_Bool)isPodcastUpdatable:(id)arg1 userInitiated:(_Bool)arg2;	// IMP=0x000000010014642c
- (_Bool)_updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 useBackgroundFetch:(_Bool)arg3 tryRedirectURL:(_Bool)arg4;	// IMP=0x000000010014640c
- (_Bool)_updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 useBackgroundFetch:(_Bool)arg3;	// IMP=0x00000001001463f4
- (void)updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 forced:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100146138
- (void)updatePodcastWithUUID:(id)arg1 userInitiated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001001460dc
- (void)updatePodcastsWithUUIDs:(id)arg1 userInitiated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100145ea4
- (void)updateAllPodcastsForBackgroundFetch:(CDUnknownBlockType)arg1;	// IMP=0x0000000100145cbc
- (void)updateAllPodcasts:(CDUnknownBlockType)arg1;	// IMP=0x0000000100145ad4

@end

