//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MTResultsControllerDelegate.h"

@class MTCompositeResultsController, MTCoreDataResultsController, NSString;

@interface MTFetchedTableWithSectionsViewController : UITableViewController <MTResultsControllerDelegate>
{
    long long _userDrivenCounter;	// 8 = 0x8
    _Bool _inSwipeToDeleteMode;	// 16 = 0x10
    MTCompositeResultsController *_compositeResultsController;	// 24 = 0x18
}

@property(retain, nonatomic) MTCompositeResultsController *compositeResultsController; // @synthesize compositeResultsController=_compositeResultsController;
@property(nonatomic) _Bool inSwipeToDeleteMode; // @synthesize inSwipeToDeleteMode=_inSwipeToDeleteMode;
- (void).cxx_destruct;	// IMP=0x0000000100065e84
- (void)_updateTableAnimated:(_Bool)arg1;	// IMP=0x0000000100065838
- (void)refetchWithPredicate:(id)arg1;	// IMP=0x00000001000657b8
- (void)refetchWithSortDescriptors:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100065720
- (void)refetchWithPredicate:(id)arg1 sortDescriptors:(id)arg2 animated:(_Bool)arg3;	// IMP=0x0000000100065638
@property(readonly, nonatomic) MTCoreDataResultsController *frc;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x0000000100065308
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x000000010006504c
- (void)controllerWillChangeContent:(id)arg1;	// IMP=0x0000000100064fe8
- (_Bool)hideHeaderForEmptySection:(long long)arg1;	// IMP=0x0000000100064fe0
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x0000000100064fa0
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100064f9c
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x0000000100064f30
- (id)reuseIdentifierForRow:(id)arg1;	// IMP=0x0000000100064f14
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x0000000100064ea0
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x0000000100064d90
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064c74
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100064bd4
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100064b80
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100064b0c
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064ad0
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064aac
- (unsigned long long)_sectionForController:(id)arg1;	// IMP=0x0000000100064a34
- (id)_controllerForSection:(unsigned long long)arg1;	// IMP=0x00000001000649d8
- (id)indexPathForObject:(id)arg1;	// IMP=0x00000001000648bc
- (id)indexPathsForObject:(id)arg1;	// IMP=0x0000000100064834
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x00000001000647b0
@property(nonatomic) _Bool changeIsUserDriven;
- (void)viewDidLoad;	// IMP=0x0000000100064690
- (void)dealloc;	// IMP=0x0000000100064614
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100064604
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000645f4
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000645e4
- (id)initWithCompositeFetchedResultsController:(id)arg1;	// IMP=0x0000000100064540
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 propertyKeys:(id)arg4;	// IMP=0x00000001000643b8
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3;	// IMP=0x000000010006433c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

