//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableViewCell.h"

#import "MTCellProtocol.h"

@class MTArtworkView, MTLabelStackView, NSString, UIView;

@interface MTGenericCell : MTTableViewCell <MTCellProtocol>
{
    _Bool _hidesSideViewWhenEditing;	// 24 = 0x18
    _Bool _sideViewHidden;	// 25 = 0x19
    _Bool _showsArtwork;	// 26 = 0x1a
    UIView *_sideView;	// 32 = 0x20
    MTArtworkView *_artworkView;	// 40 = 0x28
    MTLabelStackView *_textStackView;	// 48 = 0x30
}

+ (id)reuseIdentifier;	// IMP=0x0000000100053760
+ (Class)textStackViewClass;	// IMP=0x00000001000533d8
+ (_Bool)showsArtwork;	// IMP=0x00000001000533d0
+ (struct CGSize)artworkSizeForViewWidth:(double)arg1;	// IMP=0x0000000100053370
+ (double)maxHeight;	// IMP=0x000000010005335c
+ (double)heightForWidth:(double)arg1;	// IMP=0x00000001000531f4
@property(nonatomic) _Bool showsArtwork; // @synthesize showsArtwork=_showsArtwork;
@property(nonatomic, getter=_isSideViewHidden, setter=_setSideViewHidden:) _Bool sideViewHidden; // @synthesize sideViewHidden=_sideViewHidden;
@property(retain, nonatomic) MTLabelStackView *textStackView; // @synthesize textStackView=_textStackView;
@property(retain, nonatomic) MTArtworkView *artworkView; // @synthesize artworkView=_artworkView;
@property(nonatomic) _Bool hidesSideViewWhenEditing; // @synthesize hidesSideViewWhenEditing=_hidesSideViewWhenEditing;
@property(retain, nonatomic) UIView *sideView; // @synthesize sideView=_sideView;
- (void).cxx_destruct;	// IMP=0x00000001000545c0
- (void)_updateSideViewHiddenForState:(unsigned long long)arg1;	// IMP=0x00000001000543b0
- (void)_updateSideViewHiddenForCurrentState;	// IMP=0x0000000100054378
- (double)textViewMaxXForArtworkFrame:(struct CGRect)arg1 sideViewFrame:(struct CGRect)arg2;	// IMP=0x0000000100054294
- (double)textViewMinXForArtworkFrame:(struct CGRect)arg1 sideViewFrame:(struct CGRect)arg2;	// IMP=0x00000001000541b0
- (struct CGRect)textStackFrameForContentViewSize:(struct CGSize)arg1 artworkFrame:(struct CGRect)arg2 sideViewFrame:(struct CGRect)arg3;	// IMP=0x000000010005408c
- (struct CGRect)sideViewFrameForContentViewSize:(struct CGSize)arg1;	// IMP=0x0000000100053fa4
- (struct CGRect)artworkFrameForContentViewSize:(struct CGSize)arg1;	// IMP=0x0000000100053ef0
- (void)setEnabled:(_Bool)arg1;	// IMP=0x0000000100053e2c
- (void)willTransitionToState:(unsigned long long)arg1;	// IMP=0x0000000100053dd4
- (void)prepareForReuse;	// IMP=0x0000000100053d4c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100053d0c
- (void)layoutSubviews;	// IMP=0x0000000100053aa8
- (void)updateFonts;	// IMP=0x00000001000538bc
- (void)updateColors;	// IMP=0x00000001000538b8
- (void)configureSubviews;	// IMP=0x0000000100053764
@property(retain, nonatomic) NSString *artworkKey;
@property(retain, nonatomic) NSString *subtitle;
@property(retain, nonatomic) NSString *title;
- (void)updateWithObject:(id)arg1;	// IMP=0x0000000100053498
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100053430

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

