//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableView.h"

#import "MTTableViewRowDataDelegate.h"

@class NSString, UIView, UIView<MTLockupHeaderViewProtocol>;

@interface MTLockupHeaderTableView : MTTableView <MTTableViewRowDataDelegate>
{
    _Bool _needsToUpdateLayout;	// 8 = 0x8
    _Bool _forcePinned;	// 9 = 0x9
    _Bool _forceTucked;	// 10 = 0xa
    struct CGPoint _forcedContentOffset;	// 16 = 0x10
    _Bool _alwaysPinnedToTop;	// 32 = 0x20
    _Bool _lockupViewShouldPin;	// 33 = 0x21
    _Bool _headerPinned;	// 34 = 0x22
    double _heightForLockupViewPinning;	// 40 = 0x28
    UIView<MTLockupHeaderViewProtocol> *_lockupHeaderView;	// 48 = 0x30
    UIView *_tuckingHeaderView;	// 56 = 0x38
    double _navBarMaxY;	// 64 = 0x40
}

@property(readonly, nonatomic) double navBarMaxY; // @synthesize navBarMaxY=_navBarMaxY;
@property(readonly, nonatomic, getter=isHeaderPinned) _Bool headerPinned; // @synthesize headerPinned=_headerPinned;
@property(nonatomic) _Bool lockupViewShouldPin; // @synthesize lockupViewShouldPin=_lockupViewShouldPin;
@property(nonatomic) _Bool alwaysPinnedToTop; // @synthesize alwaysPinnedToTop=_alwaysPinnedToTop;
@property(retain, nonatomic) UIView *tuckingHeaderView; // @synthesize tuckingHeaderView=_tuckingHeaderView;
@property(retain, nonatomic) UIView<MTLockupHeaderViewProtocol> *lockupHeaderView; // @synthesize lockupHeaderView=_lockupHeaderView;
- (void).cxx_destruct;	// IMP=0x00000001000c5b3c
- (double)tabBarHeight;	// IMP=0x00000001000c5a28
- (double)navBarHeight;	// IMP=0x00000001000c5974
- (_Bool)_needsToReorderHeader;	// IMP=0x00000001000c5834
- (void)_reorderHeaders;	// IMP=0x00000001000c5660
- (void)reorderHeadersIfNeeded;	// IMP=0x00000001000c561c
- (void)setNavBarMaxY:(double)arg1;	// IMP=0x00000001000c5540
- (void)updateNavBarMaxY;	// IMP=0x00000001000c5440
- (void)updateLayoutForCurrentContentOffset;	// IMP=0x00000001000c4fc4
- (void)updateLayout;	// IMP=0x00000001000c4b7c
- (struct CGRect)adjustedVisibleRect:(struct CGRect)arg1 forFloatingSectionHeaderInTableView:(id)arg2 heightCanBeGuessed:(_Bool)arg3;	// IMP=0x00000001000c4aa0
- (void)_updateVisibleHeadersAndFootersNow:(_Bool)arg1;	// IMP=0x00000001000c4a48
- (void)_notifyDidScroll;	// IMP=0x00000001000c49e8
- (void)setPinnableHeaderView:(id)arg1;	// IMP=0x00000001000c49e4
- (void)setPinsHeaderToTop:(_Bool)arg1;	// IMP=0x00000001000c49e0
- (void)setPinsHeaderToTop:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000c49dc
- (void)layoutSubviews;	// IMP=0x00000001000c4964
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x00000001000c48bc
- (void)setHeaderPinned:(_Bool)arg1;	// IMP=0x00000001000c46f8
@property(nonatomic, getter=isTuckingEnabled) _Bool tuckingEnabled;
@property(nonatomic) double heightForLockupViewPinning; // @synthesize heightForLockupViewPinning=_heightForLockupViewPinning;
- (struct CGPoint)contentOffsetForPinningHeaderPinned;	// IMP=0x00000001000c4454
- (struct CGPoint)contentOffsetForTuckingHeaderVisible;	// IMP=0x00000001000c4360
- (struct CGPoint)contentOffsetForTuckingHeaderTucked;	// IMP=0x00000001000c4228
- (void)_clearForcedFlags;	// IMP=0x00000001000c41f4
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000c416c
- (void)scrollToRowAtIndexPath:(id)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000c40dc
- (void)setBounds:(struct CGRect)arg1;	// IMP=0x00000001000c408c
- (void)setContentOffset:(struct CGPoint)arg1;	// IMP=0x00000001000c3ee4
- (void)setContentOffsetForced:(struct CGPoint)arg1;	// IMP=0x00000001000c3e88
- (void)setNeedsToUpdateLayout;	// IMP=0x00000001000c3e6c
- (void)scrollHeaderPinnedAnimated:(_Bool)arg1;	// IMP=0x00000001000c3d70
- (void)scrollHeaderVisibleAnimated:(_Bool)arg1;	// IMP=0x00000001000c3d34
- (void)scrollHeaderTuckedAnimated:(_Bool)arg1;	// IMP=0x00000001000c3cb0
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x00000001000c3c30
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000c3b60

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <MTLockupHeaderTableViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

