//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTListResultsController.h"

@class MTPlayerManifest;

@interface MTManifestResultsController : MTListResultsController
{
    MTPlayerManifest *_manifest;	// 8 = 0x8
}

@property(retain, nonatomic) MTPlayerManifest *manifest; // @synthesize manifest=_manifest;
- (void).cxx_destruct;	// IMP=0x0000000100165fa0
- (void)_manifestDidChange;	// IMP=0x0000000100165f0c
- (void)reloadData;	// IMP=0x0000000100165d68
- (unsigned long long)startingIndexForDisplay;	// IMP=0x0000000100165d14
- (void)dealloc;	// IMP=0x0000000100165be8
- (id)init;	// IMP=0x0000000100165aec

@end

