//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTResultsController.h"

@class MTPlayerItem;

@interface MTNowPlayingResultsController : MTResultsController
{
    MTPlayerItem *_currentItem;	// 8 = 0x8
}

@property(retain, nonatomic) MTPlayerItem *currentItem; // @synthesize currentItem=_currentItem;
- (void).cxx_destruct;	// IMP=0x000000010008c734
- (id)allObjects;	// IMP=0x000000010008c650
- (unsigned long long)numberOfObjectsInSection:(unsigned long long)arg1;	// IMP=0x000000010008c614
- (id)indexPathForObject:(id)arg1;	// IMP=0x000000010008c568
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x000000010008c4ec
- (void)reloadData;	// IMP=0x000000010008c210
- (void)dealloc;	// IMP=0x000000010008c194
- (id)init;	// IMP=0x000000010008c01c

@end

