//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class MTOptionSetting;

@interface MTOptionsTableViewController : UITableViewController
{
    CDUnknownBlockType _optionSelectedBlock;	// 8 = 0x8
    MTOptionSetting *_option;	// 16 = 0x10
}

+ (id)footerFont;	// IMP=0x00000001000c1b2c
+ (id)optionFont;	// IMP=0x00000001000c1b0c
+ (double)rowHeight;	// IMP=0x00000001000c1aa8
@property(retain, nonatomic) MTOptionSetting *option; // @synthesize option=_option;
@property(copy, nonatomic) CDUnknownBlockType optionSelectedBlock; // @synthesize optionSelectedBlock=_optionSelectedBlock;
- (void).cxx_destruct;	// IMP=0x00000001000c2f54
- (id)metricsName;	// IMP=0x00000001000c2e54
- (unsigned long long)selectedIndex;	// IMP=0x00000001000c2d7c
- (id)headerText;	// IMP=0x00000001000c2c1c
- (id)footerText;	// IMP=0x00000001000c2abc
- (id)newFooterView;	// IMP=0x00000001000c283c
- (void)_updateTextColorForCell:(id)arg1 selected:(_Bool)arg2;	// IMP=0x00000001000c277c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000c2514
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;	// IMP=0x00000001000c2458
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x00000001000c244c
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;	// IMP=0x00000001000c22c8
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;	// IMP=0x00000001000c21e4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000c1f64
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000c1ed0
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000c1ec8
- (void)updateRowHeight;	// IMP=0x00000001000c1e2c
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x00000001000c1dd8
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x00000001000c1cac
- (void)dealloc;	// IMP=0x00000001000c1c30
- (id)initWithOption:(id)arg1;	// IMP=0x00000001000c1b50

@end

