//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMGridCollectionViewCell.h"

@class UILabel, UIView;

@interface MTPodcastCollectionViewCell : IMGridCollectionViewCell
{
    _Bool _needsAttention;	// 125 = 0x7d
    UIView *_coverUpView;	// 128 = 0x80
    UILabel *_titleLabel;	// 136 = 0x88
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *coverUpView; // @synthesize coverUpView=_coverUpView;
@property(nonatomic) _Bool needsAttention; // @synthesize needsAttention=_needsAttention;
- (void).cxx_destruct;	// IMP=0x00000001000fd6f8
- (void)configureMotionEffects;	// IMP=0x00000001000fd424
- (void)showContent;	// IMP=0x00000001000fd3a4
- (void)hideContent;	// IMP=0x00000001000fd220
- (id)badgeView;	// IMP=0x00000001000fd080
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001000fd07c
- (void)prepareForReuse;	// IMP=0x00000001000fcfc8
- (void)layoutSubviews;	// IMP=0x00000001000fc7d0
- (void)setSelected:(_Bool)arg1;	// IMP=0x00000001000fc7cc
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000fc690
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000fc1f4

@end

