//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IMActionControllerDelegate.h"
#import "MTEpisodeCellDelegate.h"
#import "MTReachabilityObserver.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MTKeyboardStateObserver, MTTextQuery, NSArray, NSString, UILabel, UISearchBar, UITableView, UIView;

@interface MTSearchDisplayController : UIViewController <IMActionControllerDelegate, UITableViewDelegate, UITableViewDataSource, MTReachabilityObserver, MTEpisodeCellDelegate, UISearchBarDelegate>
{
    struct {
        unsigned int delegateWillBeginSearch:1;
        unsigned int delegateWillEndSearch:1;
        unsigned int delegateDidSelectPodcast:1;
        unsigned int delegateDidSelectEpisode:1;
        unsigned int delegateDidRecognize:1;
    } _delegateFlags;	// 8 = 0x8
    UILabel *_noResults;	// 16 = 0x10
    struct CGSize _cachedFixedRowSize;	// 24 = 0x18
    struct CGSize _cachedPodcastCellSize;	// 40 = 0x28
    _Bool _active;	// 56 = 0x38
    _Bool _visible;	// 57 = 0x39
    CDUnknownBlockType _searchBeginBlock;	// 64 = 0x40
    CDUnknownBlockType _searchEndBlock;	// 72 = 0x48
    id <MTSearchDisplayControllerDelegate> _delegate;	// 80 = 0x50
    UISearchBar *_searchBar;	// 88 = 0x58
    UITableView *_tableView;	// 96 = 0x60
    UIViewController *_contentsController;	// 104 = 0x68
    NSArray *_podcastResults;	// 112 = 0x70
    NSArray *_episodeResults;	// 120 = 0x78
    MTTextQuery *_query;	// 128 = 0x80
    UIView *_dismissView;	// 136 = 0x88
    NSString *_expandedEpisodeUuid;	// 144 = 0x90
    unsigned long long _cellStyle;	// 152 = 0x98
    MTKeyboardStateObserver *_keyboardStateObserver;	// 160 = 0xa0
    struct CGSize _episodeCellSize;	// 168 = 0xa8
    struct UIEdgeInsets _containerEdgeInsets;	// 184 = 0xb8
}

@property(retain, nonatomic) MTKeyboardStateObserver *keyboardStateObserver; // @synthesize keyboardStateObserver=_keyboardStateObserver;
@property(nonatomic) unsigned long long cellStyle; // @synthesize cellStyle=_cellStyle;
@property(nonatomic) struct CGSize episodeCellSize; // @synthesize episodeCellSize=_episodeCellSize;
@property(nonatomic, getter=isVisible) _Bool visible; // @synthesize visible=_visible;
@property(retain, nonatomic) NSString *expandedEpisodeUuid; // @synthesize expandedEpisodeUuid=_expandedEpisodeUuid;
@property(retain, nonatomic) UIView *dismissView; // @synthesize dismissView=_dismissView;
@property(retain, nonatomic) MTTextQuery *query; // @synthesize query=_query;
@property(retain, nonatomic) NSArray *episodeResults; // @synthesize episodeResults=_episodeResults;
@property(retain, nonatomic) NSArray *podcastResults; // @synthesize podcastResults=_podcastResults;
@property(nonatomic) __weak UIViewController *contentsController; // @synthesize contentsController=_contentsController;
@property(nonatomic) struct UIEdgeInsets containerEdgeInsets; // @synthesize containerEdgeInsets=_containerEdgeInsets;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) id <MTSearchDisplayControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType searchEndBlock; // @synthesize searchEndBlock=_searchEndBlock;
@property(copy, nonatomic) CDUnknownBlockType searchBeginBlock; // @synthesize searchBeginBlock=_searchBeginBlock;
- (void).cxx_destruct;	// IMP=0x0000000100038f40
- (void)didPerformActionInSheet:(id)arg1;	// IMP=0x0000000100038af4
- (void)cellDidChangeSize:(id)arg1;	// IMP=0x0000000100038a78
- (void)cell:(id)arg1 moreButtonTapped:(id)arg2;	// IMP=0x00000001000389e4
- (void)layoutSubviews;	// IMP=0x0000000100038750
- (void)updateActionSheetsAndPopovers;	// IMP=0x00000001000385cc
- (void)dismissActionSheetsAndPopovers;	// IMP=0x0000000100038448
- (id)indexPathForEpisodeUuid:(id)arg1;	// IMP=0x00000001000382f4
- (void)toggleExpansionForEpisodeUuid:(id)arg1;	// IMP=0x00000001000380a4
- (void)playEpisodeAtIndexPath:(id)arg1;	// IMP=0x0000000100037f4c
- (void)selectedEpisodeAtIndexPath:(id)arg1;	// IMP=0x0000000100037d60
- (void)performSearch:(id)arg1;	// IMP=0x0000000100037900
- (void)searchBarCancelButtonClicked:(id)arg1;	// IMP=0x000000010003786c
- (void)searchBarSearchButtonClicked:(id)arg1;	// IMP=0x000000010003785c
- (_Bool)searchBarShouldEndEditing:(id)arg1;	// IMP=0x0000000100037854
- (_Bool)searchBarShouldBeginEditing:(id)arg1;	// IMP=0x00000001000377c4
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;	// IMP=0x0000000100037744
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010003751c
- (void)updateEstimatedRowHeight;	// IMP=0x00000001000373a8
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x000000010003732c
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100037058
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100036e70
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100036d88
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100036d80
- (void)configureCell:(id)arg1 indexPath:(id)arg2;	// IMP=0x00000001000369e4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000367d8
- (void)dismissSearch:(id)arg1;	// IMP=0x0000000100036524
- (void)reachabilityChangedFrom:(_Bool)arg1 to:(_Bool)arg2;	// IMP=0x0000000100036418
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x0000000100036360
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010003621c
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000361cc
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100036148
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000360f4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100035d88
- (void)viewDidLoad;	// IMP=0x000000010003596c
- (void)dealloc;	// IMP=0x00000001000358b0
- (id)init;	// IMP=0x00000001000357ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

