//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MTSettingsGroup : NSObject
{
    NSString *_groupTitle;	// 8 = 0x8
    NSString *_groupFooter;	// 16 = 0x10
    CDUnknownBlockType _settingsHandler;	// 24 = 0x18
    NSArray *_groupSettings;	// 32 = 0x20
}

+ (id)groupWithTitle:(id)arg1 footerText:(id)arg2 settingsHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000e8ac8
+ (id)groupWithTitle:(id)arg1 footerText:(id)arg2 settings:(id)arg3;	// IMP=0x00000001000e8910
@property(copy, nonatomic) NSArray *groupSettings; // @synthesize groupSettings=_groupSettings;
@property(copy, nonatomic) CDUnknownBlockType settingsHandler; // @synthesize settingsHandler=_settingsHandler;
@property(copy, nonatomic) NSString *groupFooter; // @synthesize groupFooter=_groupFooter;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
- (void).cxx_destruct;	// IMP=0x00000001000e8d5c

@end

