//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTSiriUtil : NSObject
{
}

+ (unsigned long long)episodeOrderFromString:(id)arg1;	// IMP=0x000000010006d520
+ (id)_latestOrOldestUserEpisodeForPodcastUuid:(id)arg1 latest:(_Bool)arg2 ctx:(id)arg3;	// IMP=0x000000010006d274
+ (id)_oldestUserEpisodeForPodcastUuid:(id)arg1 ctx:(id)arg2;	// IMP=0x000000010006d210
+ (id)_latestUserEpisodeForPodcastUuid:(id)arg1 ctx:(id)arg2;	// IMP=0x000000010006d1ac
+ (id)_episodeToPlayForPodcastUuid:(id)arg1 playbackOrder:(unsigned long long)arg2 ctx:(id)arg3;	// IMP=0x000000010006d0dc
+ (id)_uuidForEpisode:(id)arg1;	// IMP=0x000000010006cf08
+ (id)_podcastManifestWithInitialEpisode:(id)arg1;	// IMP=0x000000010006cc60
+ (id)_manifestForPlayPodcastUuid:(id)arg1 playbackOrder:(unsigned long long)arg2;	// IMP=0x000000010006cb74
+ (id)_manifestForPlayPodcastUuid:(id)arg1;	// IMP=0x000000010006cb64
+ (id)_manifestForPlayMyPodcastsWithPlaybackOrder:(unsigned long long)arg1;	// IMP=0x000000010006cb08
+ (id)_manifestForPlayMyOldestPodcasts;	// IMP=0x000000010006cab0
+ (id)_manifestForPlayMyLatestPodcasts;	// IMP=0x000000010006ca58
+ (id)_manifestForPlayMyPodcasts;	// IMP=0x000000010006c950
+ (_Bool)_playManifest:(id)arg1 reason:(unsigned long long)arg2 interactive:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010006c888
+ (_Bool)playPodcastUuid:(id)arg1 reason:(unsigned long long)arg2 interactive:(_Bool)arg3 playbackOrder:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010006c7c0
+ (_Bool)playMyPodcastsWithPlaybackOrder:(unsigned long long)arg1 reason:(unsigned long long)arg2 interactive:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010006c720
+ (id)manifestForPlayPodcastUuid:(id)arg1;	// IMP=0x000000010006c714
+ (id)manifestForPlayMyPodcasts;	// IMP=0x000000010006c708
+ (_Bool)playStationUuid:(id)arg1 reason:(unsigned long long)arg2 interactive:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010006c630
+ (_Bool)playPodcastUuid:(id)arg1 reason:(unsigned long long)arg2 interactive:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010006c578
+ (_Bool)playMyPodcastsReason:(unsigned long long)arg1 interactive:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010006c4e0
+ (_Bool)playWithSiriPlaybackURL:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010006c1d0
+ (_Bool)isSiriPlaybackURL:(id)arg1;	// IMP=0x000000010006c068

@end

