//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIActivityIndicatorView, UILabel;

@interface MTSplashViewController : UIViewController
{
    UIViewController *_vc;	// 8 = 0x8
    UIActivityIndicatorView *_spinner;	// 16 = 0x10
    UILabel *_label;	// 24 = 0x18
    _Bool _visible;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010013ef60
- (void)viewDidLayoutSubviews;	// IMP=0x000000010013ec1c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010013ebdc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010013e67c
- (void)viewDidLoad;	// IMP=0x000000010013e45c

@end

