//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISOperationQueue, NSOperationQueue;

@interface MTStoreInfoUpdater : NSObject
{
    NSOperationQueue *_updateOperationQueue;	// 8 = 0x8
    ISOperationQueue *_storeOperationQueue;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x000000010015e6d0
@property(retain, nonatomic) ISOperationQueue *storeOperationQueue; // @synthesize storeOperationQueue=_storeOperationQueue;
@property(retain, nonatomic) NSOperationQueue *updateOperationQueue; // @synthesize updateOperationQueue=_updateOperationQueue;
- (void).cxx_destruct;	// IMP=0x00000001001611e8
- (void)getStoreInfoForEpisodesWithAdamIds:(id)arg1 callback:(CDUnknownBlockType)arg2;	// IMP=0x0000000100160ae8
- (void)getStoreInfoForPodcastWithAdamId:(long long)arg1 callback:(CDUnknownBlockType)arg2;	// IMP=0x00000001001602d4
- (id)episodesWithMissingAdamIdsForPodcast:(id)arg1 withContext:(id)arg2;	// IMP=0x00000001001600f4
- (_Bool)updateAdamId:(id)arg1 forEpisode:(id)arg2;	// IMP=0x000000010015ffc0
- (void)updateStoreInfoForEpisodesInPodcast:(id)arg1 withEpisodeIds:(id)arg2 andEpisodesWithGuid:(id)arg3;	// IMP=0x000000010015f554
- (void)updateStoreInfoForEpisodesAndPodcast:(id)arg1 skipPodcastLastCheckDate:(_Bool)arg2;	// IMP=0x000000010015eda8
- (void)updateStoreInfoForPodcast:(id)arg1;	// IMP=0x000000010015e890
- (id)init;	// IMP=0x000000010015e784

@end

