//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTItemListManifest.h"

@class NSArray;

@interface MTStoreManifest : MTItemListManifest
{
    NSArray *_adamIds;	// 8 = 0x8
}

+ (id)storeMediaDictionariesToPlayerItems:(id)arg1;	// IMP=0x0000000100039dd0
+ (id)activityTypeSuffix;	// IMP=0x0000000100039da4
+ (id)createManifestForActivity:(id)arg1;	// IMP=0x0000000100039c28
@property(retain, nonatomic) NSArray *adamIds; // @synthesize adamIds=_adamIds;
- (void).cxx_destruct;	// IMP=0x000000010003a844
- (id)activity;	// IMP=0x0000000100039b34
- (void)_loadItemsWithInitialIndex:(unsigned long long)arg1;	// IMP=0x0000000100039610
- (id)initWithItems:(id)arg1 initialIndex:(unsigned long long)arg2;	// IMP=0x00000001000393a4
- (id)initWithStoreMediaDictionaries:(id)arg1 initialIndex:(unsigned long long)arg2;	// IMP=0x000000010003930c
- (id)initWithAdamIds:(id)arg1 initialIndex:(unsigned long long)arg2;	// IMP=0x0000000100039274

@end

