//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableViewCell.h"

@class UISwitch;

@interface MTSwitchCell : MTTableViewCell
{
    CDUnknownBlockType _toggleChanged;	// 24 = 0x18
    UISwitch *_toggle;	// 32 = 0x20
}

+ (id)titleFont;	// IMP=0x0000000100031304
@property(retain, nonatomic) UISwitch *toggle; // @synthesize toggle=_toggle;
@property(copy, nonatomic) CDUnknownBlockType toggleChanged; // @synthesize toggleChanged=_toggleChanged;
- (void).cxx_destruct;	// IMP=0x00000001000313d8
- (void)toggleChanged:(id)arg1;	// IMP=0x0000000100031324
- (void)setupCell;	// IMP=0x0000000100031178
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001000310f8
- (void)toggleOn:(_Bool)arg1;	// IMP=0x00000001000310b0

@end

