//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIActivityItemSource.h"

@class MTShareUtilDataSource, NSString;

@interface MTTextActivityItemProvider : NSObject <UIActivityItemSource>
{
    MTShareUtilDataSource *_dataSource;	// 8 = 0x8
}

@property(retain, nonatomic) MTShareUtilDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x0000000100014a50
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;	// IMP=0x0000000100014840
- (id)activityViewControllerPlaceholderItem:(id)arg1;	// IMP=0x00000001000147ec
- (id)initWithDataSource:(id)arg1;	// IMP=0x0000000100014760

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

