//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISplitViewController.h"

@interface MTTVSettingsSplitViewController : UISplitViewController
{
}

+ (double)rightViewControllerTopMargin;	// IMP=0x0000000100023c08
- (void)layoutRightViewController;	// IMP=0x0000000100023c94
- (void)setupColumnWidth;	// IMP=0x0000000100023c10
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100023bb8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100023b44
- (void)viewDidLoad;	// IMP=0x0000000100023af4

@end

