//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTVContentUnavailableViewController.h"

@interface MTTVMyPodcastsNoPodcastsViewController : MTTVContentUnavailableViewController
{
}

- (void)buttonPressed:(id)arg1;	// IMP=0x00000001000692e8
- (id)init;	// IMP=0x00000001000690e4

@end

