//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UILabel;

@interface MTTVNoContentTableViewCell : UITableViewCell
{
    NSString *_message;	// 8 = 0x8
    UILabel *_messageLabel;	// 16 = 0x10
}

+ (id)messageFont;	// IMP=0x0000000100084518
+ (double)marginBottomForStyle:(unsigned long long)arg1;	// IMP=0x0000000100084504
+ (double)heightForStyle:(unsigned long long)arg1;	// IMP=0x0000000100084484
+ (id)reuseIdentifier;	// IMP=0x0000000100084458
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;	// IMP=0x0000000100084c24
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100084b50
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100084a80
- (void)layoutSubviews;	// IMP=0x0000000100084944
- (void)updateTextColors;	// IMP=0x00000001000848d4
- (void)configureSubviews;	// IMP=0x00000001000846f0
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100084614
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x00000001000845fc
- (id)initWithMessage:(id)arg1;	// IMP=0x000000010008459c
- (id)init;	// IMP=0x0000000100084538

@end

