//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableSectionHeaderView.h"

@interface MTTVThinStyleSectionHeaderView : MTTableSectionHeaderView
{
}

+ (id)font;	// IMP=0x00000001000a63c8
+ (double)height;	// IMP=0x00000001000a63bc
- (void)layoutSubviews;	// IMP=0x00000001000a6554
- (id)backdropView;	// IMP=0x00000001000a654c
- (id)blurMaskView;	// IMP=0x00000001000a6544
- (id)dividerBar;	// IMP=0x00000001000a653c
- (id)thinTextLabel;	// IMP=0x00000001000a6534
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x00000001000a63ec

@end

