//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MTPodcast, MTTVPodcastDetailsSectionControl, UILabel;

@interface MTTVPodcastHeaderView : UIView
{
    UILabel *_titleLabel;	// 8 = 0x8
    MTTVPodcastDetailsSectionControl *_sectionControl;	// 16 = 0x10
    MTPodcast *_podcast;	// 24 = 0x18
    id <MTTVPodcastHeaderViewDelegate> _delegate;	// 32 = 0x20
}

@property(nonatomic) __weak id <MTTVPodcastHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MTPodcast *podcast; // @synthesize podcast=_podcast;
- (void).cxx_destruct;	// IMP=0x00000001000d36ac
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000d35a0
- (id)preferredFocusedView;	// IMP=0x00000001000d3590
- (_Bool)canBecomeFocused;	// IMP=0x00000001000d3544
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000d33e0
- (void)layoutSubviews;	// IMP=0x00000001000d323c
- (void)updateTextColors;	// IMP=0x00000001000d3070
- (void)sectionControlDidChange:(id)arg1;	// IMP=0x00000001000d3004
@property(nonatomic) unsigned long long selectedTab; // @dynamic selectedTab;
- (void)configureSubviews;	// IMP=0x00000001000d2d04
- (id)initWithPodcast:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001000d2c3c
- (id)init;	// IMP=0x00000001000d2c28

@end

