//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTOptionsTableViewController.h"

@interface MTTVOptionsTableViewController : MTOptionsTableViewController
{
}

+ (id)footerFont;	// IMP=0x000000010008ac88
- (void)_updateTextColorForCell:(id)arg1 selected:(_Bool)arg2;	// IMP=0x000000010008b0ac
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010008b01c
- (void)viewWillLayoutSubviews;	// IMP=0x000000010008aca8

@end

