//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MTTVStationsPlusButtonView, UILabel;

@interface MTTVStationPlusButtonCollectionViewCell : UICollectionViewCell
{
    MTTVStationsPlusButtonView *_plusButtonView;	// 8 = 0x8
    UILabel *_newStationLabel;	// 16 = 0x10
}

+ (id)reuseIdentifier;	// IMP=0x00000001001149fc
@property(retain, nonatomic) UILabel *newStationLabel; // @synthesize newStationLabel=_newStationLabel;
@property(retain, nonatomic) MTTVStationsPlusButtonView *plusButtonView; // @synthesize plusButtonView=_plusButtonView;
- (void).cxx_destruct;	// IMP=0x00000001001151b8
- (id)_textColor;	// IMP=0x0000000100114f88
- (void)_addNewStationLabel;	// IMP=0x0000000100114e34
- (void)_addPlusButtonView;	// IMP=0x0000000100114d68
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100114ca4
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100114b98
- (void)layoutSubviews;	// IMP=0x0000000100114a94
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100114a18

@end

