//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTEpisodeListViewController.h"

#import "MTTVListViewControllerProtocol.h"

@class MTTVEpisodeActionController, MTTVEpisodeListHeaderView, NSIndexPath, NSString, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface MTTVEpisodeListViewController : MTEpisodeListViewController <MTTVListViewControllerProtocol>
{
    NSIndexPath *_selectedIndexPath;	// 8 = 0x8
    NSIndexPath *_lastFocusedIndexPath;	// 16 = 0x10
    UITapGestureRecognizer *_playButtonRecognizer;	// 24 = 0x18
    UILongPressGestureRecognizer *_longPressRecognizer;	// 32 = 0x20
    MTTVEpisodeListHeaderView *_episodeListHeaderView;	// 40 = 0x28
    MTTVEpisodeActionController *_actionController;	// 48 = 0x30
}

+ (double)episodeCellHeight;	// IMP=0x000000010007895c
+ (Class)episodeCellClass;	// IMP=0x0000000100078948
@property(retain, nonatomic) MTTVEpisodeActionController *actionController; // @synthesize actionController=_actionController;
@property(retain, nonatomic) MTTVEpisodeListHeaderView *episodeListHeaderView; // @synthesize episodeListHeaderView=_episodeListHeaderView;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *playButtonRecognizer; // @synthesize playButtonRecognizer=_playButtonRecognizer;
@property(retain, nonatomic) NSIndexPath *lastFocusedIndexPath; // @synthesize lastFocusedIndexPath=_lastFocusedIndexPath;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
- (void).cxx_destruct;	// IMP=0x0000000100079eb4
- (void)unregisterForArtworkChangeNotifications:(id)arg1;	// IMP=0x0000000100079cf0
- (void)registerForArtworkChangeNotifications:(id)arg1;	// IMP=0x0000000100079c58
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;	// IMP=0x0000000100079bac
- (_Bool)tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x0000000100079ba4
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100079b08
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100079a6c
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x0000000100079784
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100079760
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000795d8
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x0000000100079534
- (id)preferredFocusedView;	// IMP=0x00000001000794c0
- (id)rightButtonItems;	// IMP=0x0000000100079418
- (void)setCellStyle:(unsigned long long)arg1;	// IMP=0x0000000100079414
- (void)selectedItemAtIndexPath:(id)arg1;	// IMP=0x0000000100079390
- (void)longPressAction:(id)arg1;	// IMP=0x00000001000791e8
- (void)playPauseButtonAction:(id)arg1;	// IMP=0x0000000100079088
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100078d00
- (void)viewDidLoad;	// IMP=0x00000001000789d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

