//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface MTTVDeleteTableViewCell : UITableViewCell
{
}

- (void)updateColors;	// IMP=0x00000001000cf500
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000cf3fc
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000cf3ac
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000cf35c
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000cf268

@end

