//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTVCollectionViewSectionHeader.h"

@interface MTTVCollectionViewGlobalHeader : MTTVCollectionViewSectionHeader
{
}

+ (struct CGSize)estimatedSize:(struct CGSize)arg1 firstSectionHasHeader:(_Bool)arg2;	// IMP=0x0000000100046e0c
+ (struct CGSize)estimatedSize:(struct CGSize)arg1;	// IMP=0x0000000100046dfc
+ (id)titleFont;	// IMP=0x0000000100046ddc
- (void)layoutSubviews;	// IMP=0x0000000100046e28

@end

