//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPlaybackViewController.h"

#import "IMActionControllerDelegate.h"
#import "TVPlaybackViewControllerDelegate.h"

@class IMActionController, MTTVPlayback, NSString;

@interface MTTVNowPlayingViewController : TVPlaybackViewController <TVPlaybackViewControllerDelegate, IMActionControllerDelegate>
{
    _Bool _remoteViewService;	// 8 = 0x8
    MTTVPlayback *_playback;	// 16 = 0x10
    IMActionController *_actionController;	// 24 = 0x18
}

@property(retain, nonatomic) IMActionController *actionController; // @synthesize actionController=_actionController;
@property(nonatomic, getter=isRemoteViewService) _Bool remoteViewService; // @synthesize remoteViewService=_remoteViewService;
@property(retain, nonatomic) MTTVPlayback *playback; // @synthesize playback=_playback;
- (void).cxx_destruct;	// IMP=0x0000000100074664
- (id)rootNavigationController;	// IMP=0x0000000100074524
- (void)playMediaItemAtIndex:(long long)arg1;	// IMP=0x000000010007448c
- (id)_menuItemsForActionController:(id)arg1;	// IMP=0x000000010007421c
- (void)contextMenuForMediaItem:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100073fe0
- (void)willMoveToParentViewController:(id)arg1;	// IMP=0x0000000100073f84
- (id)init;	// IMP=0x0000000100073e80

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

