//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTHeaderCollectionReusableView.h"

@class IMTVVibrantLabel, UILabel;

@interface MTTVCollectionViewSectionHeader : MTHeaderCollectionReusableView
{
    _Bool _avoiding;	// 8 = 0x8
    IMTVVibrantLabel *_vibrantLabel;	// 16 = 0x10
    UILabel *_headerLabel;	// 24 = 0x18
}

+ (id)titleFont;	// IMP=0x000000010006a744
+ (struct CGSize)estimatedSize:(struct CGSize)arg1;	// IMP=0x000000010006a6cc
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(nonatomic) _Bool avoiding; // @synthesize avoiding=_avoiding;
@property(retain, nonatomic) IMTVVibrantLabel *vibrantLabel; // @synthesize vibrantLabel=_vibrantLabel;
- (void).cxx_destruct;	// IMP=0x000000010006ace4
- (void)prepareForReuse;	// IMP=0x000000010006ac10
- (void)layoutSubviews;	// IMP=0x000000010006aabc
- (id)titleView;	// IMP=0x000000010006a9ec
- (id)title;	// IMP=0x000000010006a998
- (void)setTitle:(id)arg1;	// IMP=0x000000010006a92c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010006a764

@end

