//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSingleton.h"

@class NSArray, NSMutableArray;

@interface MTUpNextController : MTSingleton
{
    NSMutableArray *_uuids;	// 8 = 0x8
    unsigned long long _updateCount;	// 16 = 0x10
}

+ (id)_filePath;	// IMP=0x00000001000ce794
@property(nonatomic) unsigned long long updateCount; // @synthesize updateCount=_updateCount;
@property(retain, nonatomic) NSMutableArray *uuids; // @synthesize uuids=_uuids;
- (void).cxx_destruct;	// IMP=0x00000001000ce884
- (id)_restoreUpNext;	// IMP=0x00000001000ce6f4
- (void)_upNextDidChange;	// IMP=0x00000001000ce600
- (void)_reportUpNextChangeType:(id)arg1 forEpisodeUuid:(id)arg2 withData:(id)arg3;	// IMP=0x00000001000ce1a8
- (unsigned long long)_currentUpNextIndex;	// IMP=0x00000001000ce12c
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *episodeUuids;
- (void)endUpdates;	// IMP=0x00000001000ce02c
- (void)beginUpdates;	// IMP=0x00000001000cdff4
- (unsigned long long)upNextOffset;	// IMP=0x00000001000cdfd8
- (_Bool)isPlayingFromUpNext;	// IMP=0x00000001000cdfb0
- (void)clear;	// IMP=0x00000001000cdf3c
- (void)moveEpisodeFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;	// IMP=0x00000001000cdd4c
- (void)removeEpisodesForUuid:(id)arg1;	// IMP=0x00000001000cdbe8
- (void)removeEpisodeAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000cda78
- (_Bool)containsEpisodeUuid:(id)arg1;	// IMP=0x00000001000cd9fc
- (void)addEpisodeUuidToPlayNext:(id)arg1;	// IMP=0x00000001000cd898
- (void)addEpisodeUuidToUpNext:(id)arg1;	// IMP=0x00000001000cd7f8
- (id)init;	// IMP=0x00000001000cd778

@end

