//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTURLResolver : NSObject
{
}

+ (_Bool)_handleLegacyCoreSpotlightURL:(id)arg1;	// IMP=0x000000010009db70
+ (_Bool)_isLegacyCoreSpotlightURL:(id)arg1;	// IMP=0x000000010009da78
+ (_Bool)_handleNowPlayingURL:(id)arg1;	// IMP=0x000000010009d8b8
+ (void)showSearchControllerWithSearchText:(id)arg1;	// IMP=0x000000010009d780
+ (void)handlePodcastsUrlScheme:(id)arg1;	// IMP=0x000000010009d3a0
+ (void)handleiTMSUrlScheme:(id)arg1;	// IMP=0x000000010009cfb0
+ (id)appController;	// IMP=0x000000010009cf9c

@end

