//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (IMAdditions)
+ (id)imDataFromHexString:(id)arg1;	// IMP=0x00000001001cc124
- (id)md5;	// IMP=0x00000001001cc42c
- (id)sha1;	// IMP=0x00000001001cc350
- (id)hexString;	// IMP=0x00000001001cc2a4
@end

