//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Base64)
+ (id)dataWithBase64EncodedString:(id)arg1;	// IMP=0x0000000100197818
- (id)base64Encoding;	// IMP=0x0000000100197a60
@end

