//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSIndexPath.h"

@interface NSIndexPath (MTAdditions)
- (_Bool)isBefore:(id)arg1;	// IMP=0x00000001000e6470
- (_Bool)isAfter:(id)arg1;	// IMP=0x00000001000e644c
- (unsigned long long)lastIndex;	// IMP=0x00000001000e63f0
- (id)indexPathByChangingSection:(long long)arg1;	// IMP=0x00000001000e638c
@end

