//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@interface NSManagedObject (IMAdditions)
+ (id)fetchObjectsFromMOC:(id)arg1 withPredicate:(id)arg2 sortBy:(id)arg3 ascending:(_Bool)arg4 fetchLimit:(int)arg5;	// IMP=0x0000000100207444
+ (id)fetchObjectsFromMOC:(id)arg1 withPredicate:(id)arg2 sortBy:(id)arg3 ascending:(_Bool)arg4 fetchLimit:(int)arg5 prefetchRelationships:(id)arg6;	// IMP=0x00000001002073c8
+ (id)fetchObjectsFromMOC:(id)arg1 withPredicateFormat:(id)arg2;	// IMP=0x0000000100207338
+ (id)fetchObjectFromMOC:(id)arg1 withPredicateFormat:(id)arg2;	// IMP=0x000000010020727c
+ (id)newObjectFromMOC:(id)arg1;	// IMP=0x0000000100207244
@end

