//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObjectContext.h"

@interface NSManagedObjectContext (MTPlaylist)
- (id)playlistForUuid:(id)arg1;	// IMP=0x00000001000af464
- (id)playlistIdWithUuid:(id)arg1;	// IMP=0x00000001000af44c
- (void)deletePlaylist:(id)arg1;	// IMP=0x00000001000af2d0
- (id)existingPlaylistWithID:(id)arg1;	// IMP=0x00000001000af210
- (id)playlistWithID:(id)arg1;	// IMP=0x00000001000af204
@end

