//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (IMFlipTransitionDelegate)
- (void)flipTransition:(id)arg1 didRotateFromInterfaceOrientation:(long long)arg2;	// IMP=0x00000001001ac684
- (void)flipTransition:(id)arg1 willRotateToInterfaceOrientation:(long long)arg2 duration:(double)arg3;	// IMP=0x00000001001ac680
- (void)flipTransitionDidReachHalfClosed:(id)arg1;	// IMP=0x00000001001ac67c
- (void)flipTransitionDidClose:(id)arg1;	// IMP=0x00000001001ac678
- (void)flipTransitionDidReachHalfOpen:(id)arg1;	// IMP=0x00000001001ac674
- (void)flipTransitionDidOpen:(id)arg1;	// IMP=0x00000001001ac670
@end

