//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPredicate.h"

@interface NSPredicate (MTAdditions)
+ (id)truePredicate;	// IMP=0x0000000100142b04
+ (id)falsePredicate;	// IMP=0x0000000100142ad8
- (id)OR:(id)arg1;	// IMP=0x0000000100142a08
- (id)AND:(id)arg1;	// IMP=0x000000010014292c
@end

