//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (MTAdditions)
+ (id)combineImages:(id)arg1 rowCount:(long long)arg2 size:(struct CGSize)arg3 border:(_Bool)arg4;	// IMP=0x000000010007aa5c
+ (void)drawBorder:(struct CGRect)arg1 withContext:(struct CGContext *)arg2;	// IMP=0x000000010007a944
+ (id)infoIcon;	// IMP=0x000000010007a894
+ (id)multiUncheckIcon;	// IMP=0x000000010007a7e4
+ (id)multiCheckIcon;	// IMP=0x000000010007a734
+ (id)playedIcon;	// IMP=0x000000010007a72c
+ (id)backCatalogPartiallyPlayedIconForTintColor:(id)arg1;	// IMP=0x000000010007a5b0
+ (id)backCatalogPartiallyPlayedIconForDarkBackground:(_Bool)arg1;	// IMP=0x000000010007a540
+ (id)backCatalogPartiallyPlayedIconForTheme:(id)arg1;	// IMP=0x000000010007a4d8
+ (id)backCatalogIconForTintColor:(id)arg1;	// IMP=0x000000010007a35c
+ (id)backCatalogIconForDarkBackground:(_Bool)arg1;	// IMP=0x000000010007a2ec
+ (id)backCatalogIconForTheme:(id)arg1;	// IMP=0x000000010007a284
+ (id)halfPlayedIconForDarkBackground:(_Bool)arg1;	// IMP=0x000000010007a200
+ (id)halfPlayedIconForTheme:(id)arg1;	// IMP=0x000000010007a1c4
+ (id)halfPlayedIcon;	// IMP=0x000000010007a1b4
+ (id)unplayedIconForDarkBackground:(_Bool)arg1;	// IMP=0x000000010007a130
+ (id)unplayedIconForTheme:(id)arg1;	// IMP=0x000000010007a0f4
+ (id)unplayedIcon;	// IMP=0x000000010007a0e4
+ (id)nowPlayingIconPaused;	// IMP=0x000000010007a014
+ (id)nowPlayingIcon;	// IMP=0x0000000100079f44
- (id)scaleToSize:(struct CGSize)arg1 addBorder:(_Bool)arg2;	// IMP=0x000000010007ac74
@end

