//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPopoverController.h"

@interface UIPopoverController (SPI_UIPopoverController)
- (void)spi_setPopoverBackgroundStyleClear;	// IMP=0x00000001001cfc1c
- (void)spi_setPopoverBackgroundStyleCream;	// IMP=0x00000001001cfc0c
@end

