//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (MTAdditions)
+ (struct UIEdgeInsets)mt_layoutMarginsForWidth:(double)arg1;	// IMP=0x00000001000810ec
+ (double)mt_horizontalMarginsForWidth:(double)arg1;	// IMP=0x00000001000810c0
+ (_Bool)mt_areMarginsGenerousForWidth:(double)arg1;	// IMP=0x00000001000810ac
- (_Bool)mt_isRTL;	// IMP=0x0000000100081124
- (_Bool)mt_areMarginsGenerous;	// IMP=0x0000000100081060
- (struct UIEdgeInsets)mt_layoutMarginsForWidth:(double)arg1;	// IMP=0x0000000100080fec
- (struct UIEdgeInsets)mt_layoutMargins;	// IMP=0x0000000100080fb4
@end

