//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DAComponent.h"

@interface DABluetoothComponent : DAComponent
{
}

- (id)bluetoothAddress;	// IMP=0x0000000100006e98
- (id)profile;	// IMP=0x0000000100006d84
- (_Bool)isPresent;	// IMP=0x0000000100006d78
- (id)type;	// IMP=0x0000000100006d68

@end

