//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DAPresenceCheckProtocol.h"

@class NSMutableDictionary, NSString;

@interface DAComponent : NSObject <DAPresenceCheckProtocol>
{
    NSString *_type;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    NSMutableDictionary *_data;	// 24 = 0x18
}

@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;	// IMP=0x000000010000c9d4
- (id)checkPresence;	// IMP=0x000000010000c8e4
- (_Bool)isValidIdentifier:(id)arg1;	// IMP=0x000000010000c8dc
- (id)profile;	// IMP=0x000000010000c744
- (_Bool)isPresent;	// IMP=0x000000010000c6bc
- (id)initWithIdentifier:(id)arg1;	// IMP=0x000000010000c604
- (id)init;	// IMP=0x000000010000c5f4
@property(readonly, nonatomic) NSString *serialNumber;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

