//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString, UIImage, UINavigationController;

@protocol DADisplayProtocol <NSObject>
@property(retain, nonatomic) UINavigationController *primaryNavigationController;
- (_Bool)isRemoteApplication;
- (void)displayTestSuiteImage:(UIImage *)arg1;
- (void)displayTestSuiteCancel;
- (void)displayTestSuiteComplete:(NSString *)arg1 description:(NSString *)arg2;
- (void)displayTestSuiteStart:(NSString *)arg1 description:(NSString *)arg2;
- (_Bool)displayDeviceIdentifier:(NSString *)arg1 error:(id *)arg2;
- (_Bool)setDeviceIdentifierVisible:(_Bool)arg1 error:(id *)arg2;
- (void)displayProgress:(NSNumber *)arg1;
- (void)displayFailure:(NSString *)arg1;
- (void)displayArchived;
- (void)displayWaiting;
@end

