//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface DAProximityManager : NSObject
{
    _Bool _updating;	// 8 = 0x8
    NSDictionary *_sensorRegion;	// 16 = 0x10
    struct __MTDevice *_deviceRef;	// 24 = 0x18
    CDUnknownBlockType _handler;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x000000010001da98
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) struct __MTDevice *deviceRef; // @synthesize deviceRef=_deviceRef;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(readonly, nonatomic) NSDictionary *sensorRegion; // @synthesize sensorRegion=_sensorRegion;
- (void).cxx_destruct;	// IMP=0x000000010001e198
- (void)deviceSetDataStream:(unsigned char)arg1;	// IMP=0x000000010001e0f4
- (void)unregisterProximityChangedCallback;	// IMP=0x000000010001e0d0
- (void)registerProximityChangedCallback;	// IMP=0x000000010001e058
- (void)deviceStop;	// IMP=0x000000010001e01c
- (void)deviceStart;	// IMP=0x000000010001dfdc
- (_Bool)stopProximitySensorUpdates;	// IMP=0x000000010001df24
- (void)handleNewProximityValue:(int)arg1;	// IMP=0x000000010001dea8
- (_Bool)startProximitySensorUpdatesWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001de04
- (void)dealloc;	// IMP=0x000000010001ddac
- (id)init;	// IMP=0x000000010001db18

@end

