//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSNumber, NSString;

@protocol DAPresenceCheckProtocol <NSObject>
@property(readonly, nonatomic) NSString *serialNumber;
@property(retain, nonatomic) NSMutableDictionary *data;
@property(retain, nonatomic) NSString *identifier;
@property(retain, nonatomic) NSString *type;
- (_Bool)isValidIdentifier:(NSString *)arg1;
- (NSNumber *)checkPresence;
@end

