//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DADisplayNetworkRequiredDelegate.h"
#import "DADisplayProtocol.h"
#import "TVDMainViewDelegate.h"

@class NSMutableArray, NSString, TVDAppDelegate, TVDMainView, UINavigationController, _UIContentUnavailableView;

@interface TVDViewController : UIViewController <TVDMainViewDelegate, DADisplayProtocol, DADisplayNetworkRequiredDelegate>
{
    _Bool _termsAndConditionsStarted;	// 8 = 0x8
    UINavigationController *_primaryNavigationController;	// 16 = 0x10
    TVDAppDelegate *_appDelegate;	// 24 = 0x18
    TVDMainView *_mainView;	// 32 = 0x20
    _UIContentUnavailableView *_noFreeSpaceView;	// 40 = 0x28
    _UIContentUnavailableView *_failureView;	// 48 = 0x30
    _UIContentUnavailableView *_networkRequiredView;	// 56 = 0x38
    unsigned long long _currentViewControllerState;	// 64 = 0x40
    NSMutableArray *_history;	// 72 = 0x48
}

@property(retain, nonatomic) NSMutableArray *history; // @synthesize history=_history;
@property(nonatomic) _Bool termsAndConditionsStarted; // @synthesize termsAndConditionsStarted=_termsAndConditionsStarted;
@property(nonatomic) unsigned long long currentViewControllerState; // @synthesize currentViewControllerState=_currentViewControllerState;
@property(retain, nonatomic) _UIContentUnavailableView *networkRequiredView; // @synthesize networkRequiredView=_networkRequiredView;
@property(retain, nonatomic) _UIContentUnavailableView *failureView; // @synthesize failureView=_failureView;
@property(retain, nonatomic) _UIContentUnavailableView *noFreeSpaceView; // @synthesize noFreeSpaceView=_noFreeSpaceView;
@property(retain, nonatomic) TVDMainView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) TVDAppDelegate *appDelegate; // @synthesize appDelegate=_appDelegate;
@property(retain, nonatomic) UINavigationController *primaryNavigationController; // @synthesize primaryNavigationController=_primaryNavigationController;
- (void).cxx_destruct;	// IMP=0x00000001000164c0
- (void)updateViewConstraints;	// IMP=0x0000000100016004
- (void)setupView;	// IMP=0x0000000100015a84
- (void)openSettings;	// IMP=0x0000000100015a04
- (void)showImageViewWithImage:(id)arg1;	// IMP=0x0000000100015a00
- (void)hideEverything;	// IMP=0x000000010001594c
- (void)hideWiFiRequired;	// IMP=0x0000000100015940
- (void)displayWiFiRequired;	// IMP=0x0000000100015934
- (void)hideNetworkRequired;	// IMP=0x0000000100015878
- (void)displayNetworkRequired;	// IMP=0x00000001000154fc
- (void)mainViewDidReceiveHistoryAction:(id)arg1;	// IMP=0x000000010001535c
- (void)mainViewDidReceiveDoneAction:(id)arg1;	// IMP=0x000000010001531c
- (void)mainViewDidReceiveCloseAction:(id)arg1;	// IMP=0x00000001000150a0
- (_Bool)isRemoteApplication;	// IMP=0x0000000100015098
- (_Bool)displayDeviceIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100015018
- (_Bool)setDeviceIdentifierVisible:(_Bool)arg1 error:(id *)arg2;	// IMP=0x0000000100014fb4
- (void)displayFailure:(id)arg1;	// IMP=0x0000000100014b08
- (void)displayArchived;	// IMP=0x00000001000148a8
- (void)displayProgress:(id)arg1;	// IMP=0x0000000100014644
- (void)displayTestSuiteImage:(id)arg1;	// IMP=0x0000000100014638
- (void)displayTestSuiteCancel;	// IMP=0x000000010001462c
- (void)displayTestSuiteComplete:(id)arg1 description:(id)arg2;	// IMP=0x000000010001449c
- (void)displayTestSuiteStart:(id)arg1 description:(id)arg2;	// IMP=0x00000001000141a8
- (void)displayWaiting;	// IMP=0x0000000100014018
- (void)hideOutOfSpace;	// IMP=0x0000000100013f5c
- (void)displayOutOfSpace;	// IMP=0x0000000100013c00
- (_Bool)checkIfFreeSpaceAvailable;	// IMP=0x0000000100013ae0
- (void)updateViewsIfSpaceAvailable;	// IMP=0x000000010001394c
- (unsigned long long)getFreeUserSpaceThreshold;	// IMP=0x0000000100013874
- (unsigned long long)getFreeSystemSpaceThreshold;	// IMP=0x000000010001379c
- (void)didDisagreeToTerms;	// IMP=0x000000010001375c
- (void)didAgreeToTerms;	// IMP=0x00000001000136d8
- (void)presentSecondaryConsent;	// IMP=0x0000000100013428
- (void)presentTermsAndConditions;	// IMP=0x00000001000131bc
- (id)preferredFocusedItem;	// IMP=0x00000001000130b4
- (void)applicationDidResume;	// IMP=0x0000000100013064
- (void)viewDidLoad;	// IMP=0x0000000100012f3c
- (id)init;	// IMP=0x0000000100012e50

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

