//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSPreviewTableViewController.h"

@interface TVHSAudiobooksTableViewController : TVHSPreviewTableViewController
{
}

- (id)_previewViewControllerForContentItem:(id)arg1;	// IMP=0x0000000100020440
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100020354
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100020188
- (void)viewDidLoad;	// IMP=0x00000001000200f4
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100020034

@end

