//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSDataQueryViewController.h"

#import "TVSDataClientResultsControllerDataSource.h"

@class NSString, TVSDataCollection;

@interface TVHSAudiobookChaptersDataQueryViewController : TVHSDataQueryViewController <TVSDataClientResultsControllerDataSource>
{
    TVSDataCollection *_audiobook;	// 8 = 0x8
}

@property(retain, nonatomic) TVSDataCollection *audiobook; // @synthesize audiobook=_audiobook;
- (void).cxx_destruct;	// IMP=0x000000010002b748
- (id)queryForController:(id)arg1;	// IMP=0x000000010002b69c
- (id)initWithAudiobook:(id)arg1;	// IMP=0x000000010002b43c
- (id)initWithDataClientResultsController:(id)arg1;	// IMP=0x000000010002b42c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

