//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSMediaBrowseTableItem.h"

@interface TVHSMusicBrowseTableItem : TVHSMediaBrowseTableItem
{
}

- (id)newViewController;	// IMP=0x00000001000258c0
- (id)title;	// IMP=0x0000000100025850
- (unsigned long long)mediaCategory;	// IMP=0x0000000100025848
- (id)initWithDataClient:(id)arg1;	// IMP=0x00000001000257b4

@end

