//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSDataQueryViewController.h"

@interface TVHSPlaylistsViewController : TVHSDataQueryViewController
{
}

- (id)_playlistsFromPlaylistsDictionary:(id)arg1;	// IMP=0x000000010001500c
- (id)_playlistDictionaryWithPlaylistDataCollections:(id)arg1;	// IMP=0x0000000100014ea0
- (unsigned long long)_proccessResultsForQuery:(id)arg1;	// IMP=0x0000000100014a78
- (id)initWithDataClientResultsController:(id)arg1;	// IMP=0x00000001000149b8

@end

