//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSDataQueryNavigationTableViewController.h"

#import "TVDataQueryViewControllerDelegate.h"
#import "TVSDataClientResultsControllerDataSource.h"

@class NSString, TVHSTVShowsNavigationViewController;

@interface TVHSTVShowsMainViewController : TVHSDataQueryNavigationTableViewController <TVDataQueryViewControllerDelegate, TVSDataClientResultsControllerDataSource>
{
    TVHSTVShowsNavigationViewController *_tvShowsNavigationViewController;	// 8 = 0x8
}

@property(retain, nonatomic) TVHSTVShowsNavigationViewController *tvShowsNavigationViewController; // @synthesize tvShowsNavigationViewController=_tvShowsNavigationViewController;
- (void).cxx_destruct;	// IMP=0x000000010003fef0
- (id)_tvShowEpisodesSortedByDateReleasedFromTVShowEpisodes:(id)arg1;	// IMP=0x000000010003fe94
- (id)queryForController:(id)arg1;	// IMP=0x000000010003fe80
- (unsigned long long)dataQueryViewController:(id)arg1 didChangeResultsForQuery:(id)arg2;	// IMP=0x000000010003fa88
- (id)initWithDataClient:(id)arg1;	// IMP=0x000000010003f880

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

