//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TVHSTVShow : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSArray *_episodes;	// 16 = 0x10
    NSArray *_seasons;	// 24 = 0x18
}

+ (CDUnknownBlockType)_seasonsDescendingDateReleasedSortComparator;	// IMP=0x00000001000242b4
+ (CDUnknownBlockType)_seasonsAscendingDateReleasedSortComparator;	// IMP=0x0000000100024184
+ (CDUnknownBlockType)_seasonsAscendingDisplayNameSortComparator;	// IMP=0x0000000100024054
+ (CDUnknownBlockType)_seasonsAscendingSeasonNumberSortComparator;	// IMP=0x0000000100023ea0
+ (id)unwatchedTVShowsFromTVShows:(id)arg1;	// IMP=0x0000000100023c0c
+ (id)TVShowsSortedByNameFromTVShowEpisodesSortedByShowName:(id)arg1;	// IMP=0x0000000100023b80
@property(copy, nonatomic) NSArray *seasons; // @synthesize seasons=_seasons;
@property(copy, nonatomic) NSArray *episodes; // @synthesize episodes=_episodes;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;	// IMP=0x0000000100024428
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100023df8
- (id)seasonWithIdentifier:(id)arg1;	// IMP=0x00000001000239e0
@property(readonly, nonatomic) unsigned long long blueDotState;
@property(readonly, copy, nonatomic) NSArray *unwatchedEpisodes;
@property(readonly, copy, nonatomic) NSArray *unwatchedSeasons;
- (id)initWithName:(id)arg1;	// IMP=0x00000001000232ec
- (id)init;	// IMP=0x00000001000232a8

@end

