//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVHSImageFactory : NSObject
{
}

+ (id)photoCollectionPlaceholderImage;	// IMP=0x0000000100019d7c
+ (id)unplayedBadgeImage;	// IMP=0x0000000100019d60
+ (id)photosThumbnailImage;	// IMP=0x0000000100019d44
+ (id)partiallyPlayedBadgeImage;	// IMP=0x0000000100019d28
+ (id)facesThumbnailImage;	// IMP=0x0000000100019d0c
+ (id)eventsThumbnailImage;	// IMP=0x0000000100019cf0

@end

