//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSMoviesByNameNavigationItem.h"

@interface TVHSHomeVideosByNameNavigationItem : TVHSMoviesByNameNavigationItem
{
}

- (id)_playlistsViewController;	// IMP=0x0000000100028960
- (id)_playlistsPreviewDataClientResultsController;	// IMP=0x00000001000288fc

@end

