//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSPlaylistItemsViewController.h"

@interface TVHSMoviesPlaylistItemsViewController : TVHSPlaylistItemsViewController
{
}

- (id)initWithPlaylist:(id)arg1;	// IMP=0x000000010002685c
- (id)initWithPlaylist:(id)arg1 dataClientResultsController:(id)arg2;	// IMP=0x0000000100026800

@end

