//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSPhotoCollectionsGridViewController.h"

@interface TVHSPhotoFacesGridViewController : TVHSPhotoCollectionsGridViewController
{
}

+ (Class)_photoCollectionGridItemClass;	// IMP=0x0000000100008d14
- (id)initWithDataClient:(id)arg1 dataCollection:(id)arg2;	// IMP=0x0000000100008c2c

@end

