//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVDataQueryViewController.h"

@interface TVHSDataQueryNavigationTableViewController : TVDataQueryViewController
{
}

- (void)_handleNowPlayingViewDidDisappearNotification:(id)arg1;	// IMP=0x0000000100015318
- (void)_handleNowPlayingViewWillAppearNotification:(id)arg1;	// IMP=0x000000010001530c
- (_Bool)_automaticallyPauseUpdatingHandling;	// IMP=0x0000000100015304
- (void)dealloc;	// IMP=0x0000000100015288
- (id)initWithDataClientResultsController:(id)arg1;	// IMP=0x00000001000151bc

@end

