//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHSPhotoThumbnailsGridViewController.h"

@class NSArray;

@interface TVHSPhotoCollectionsGridViewController : TVHSPhotoThumbnailsGridViewController
{
    NSArray *_photoCollectionGridItems;	// 8 = 0x8
}

+ (Class)_collectionViewCellClass;	// IMP=0x000000010001a244
+ (double)_collectionViewMinimumLineSpacing;	// IMP=0x000000010001a238
+ (struct CGSize)_collectionViewItemSize;	// IMP=0x000000010001a224
+ (Class)_photoCollectionGridItemClass;	// IMP=0x0000000100019fd8
@property(retain, nonatomic) NSArray *photoCollectionGridItems; // @synthesize photoCollectionGridItems=_photoCollectionGridItems;
- (void).cxx_destruct;	// IMP=0x000000010001a4d4
- (id)_photoCollectionGridItemAtIndexPath:(id)arg1;	// IMP=0x000000010001a410
- (id)_newPhotoCollectionGridItemWithDataCollection:(id)arg1;	// IMP=0x000000010001a394
- (void)_configureCell:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x000000010001a258
- (void)setThumbnailItems:(id)arg1;	// IMP=0x0000000100019fec
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100019ef8

@end

