//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVPlaybackViewControllerDelegate.h"

@class NSString, TVPlaybackViewController;

@interface TVHSNowPlayingManager : NSObject <TVPlaybackViewControllerDelegate>
{
    TVPlaybackViewController *_playbackViewController;	// 8 = 0x8
}

+ (id)_dataItemForMediaItem:(id)arg1;	// IMP=0x0000000100012bb8
+ (id)_displayCollectionViewControllerForDataItem:(id)arg1 collectionType:(id)arg2;	// IMP=0x0000000100012af0
+ (id)sharedInstance;	// IMP=0x0000000100011d78
@property(retain, nonatomic) TVPlaybackViewController *playbackViewController; // @synthesize playbackViewController=_playbackViewController;
- (void).cxx_destruct;	// IMP=0x0000000100012c80
- (id)_displayCollectionURLForDataItem:(id)arg1 collectionType:(id)arg2;	// IMP=0x00000001000129a0
- (void)_displayCollectionForDataItem:(id)arg1 collectionType:(id)arg2;	// IMP=0x0000000100012818
- (id)_viewArtistMenuWithMediaItem:(id)arg1;	// IMP=0x00000001000125d0
- (id)_viewAlbumMenuWithMediaItem:(id)arg1;	// IMP=0x0000000100012388
- (void)_handleNowPlayingViewDidDisappearNotification:(id)arg1;	// IMP=0x00000001000122c4
- (void)_handleNowPlayingViewWillAppearNotification:(id)arg1;	// IMP=0x0000000100012240
- (void)contextMenuForMediaItem:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100012044
- (void)showPlaybackControllerIfNeeded;	// IMP=0x0000000100011f7c
- (void)dealloc;	// IMP=0x0000000100011ec4
- (id)init;	// IMP=0x0000000100011df8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

