//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVHSMoviesQueryFactory : NSObject
{
}

+ (id)_moviesQuery;	// IMP=0x0000000100010ee0
+ (id)moviesQueryWithPlaylist:(id)arg1;	// IMP=0x0000000100010e54
+ (id)moviePlaylistsQuery;	// IMP=0x0000000100010e34
+ (id)moviesQueryWithGenre:(id)arg1;	// IMP=0x0000000100010d5c
+ (id)movieQueryWithID:(id)arg1;	// IMP=0x0000000100010ca8
+ (id)genresQuery;	// IMP=0x0000000100010bd8
+ (id)moviesPreviewQuery;	// IMP=0x0000000100010b8c
+ (id)moviesLimitedMetadataQuery;	// IMP=0x0000000100010b80
+ (id)moviesQuery;	// IMP=0x0000000100010b20

@end

